### ISSUE TITLE
Конструктор запросов: не работает кнопка "Параметры виртуальной таблицы"

### ISSUE THREAD

**Issue by VAGoncharov** [1C-Company/1c-edt-issues#1066]
### Описание ошибки

Открываю схему СКД. Открываю конструктор запроса схемы. 
Выбирают пакет запроса, где есть срез последних для регистра сведений. Пытаюсь открыть параметры вирт. таблицы через кнопку "Параметры виртуальной таблицы". Ничего не происходит, в журнале выскакивает сообщение:
`
!ENTRY com._1c.g5.v8.dt.qw.ui 4 0 2023-07-10 10:45:45.219
!MESSAGE Error in query wizard command execution
!STACK 0
com._1c.g5.v8.dt.qw.ui.utils.QuerySchemaBuilder$QuerySchemaBuilderException: {(591, 1)}: Синтаксическая ошибка. Пропущена лексема
	at com._1c.g5.v8.dt.qw.ui.utils.QuerySchemaBuilder.buildQuerySchema(QuerySchemaBuilder.java:209)
	at com._1c.g5.v8.dt.qw.ui.utils.QuerySchemaBuilder.buildQuerySchema(QuerySchemaBuilder.java:161)
	at com._1c.g5.v8.dt.qw.ui.dialogs.VirtTableParamsDialog.createControlForParam(VirtTableParamsDialog.java:322)
	at com._1c.g5.v8.dt.qw.ui.dialogs.VirtTableParamsDialog.createControls(VirtTableParamsDialog.java:256)
	at com._1c.g5.v8.dt.qw.ui.dialogs.VirtTableParamsDialog.createDialogArea(VirtTableParamsDialog.java:111)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:767)
...

Текст запроса корректный, выполняется без ошибок.

### Как воспроизвести

-

### Ожидаемое поведение

Кнопка работает

### Лог рабочей области

[ошибка редактора запросов.log](https://github.com/1C-Company/1c-edt-issues/files/11999205/default.log)

### Версия 1С:EDT

2022.2.5

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by MaksimDzyuba** [comment]
Здравствуйте, а можно текст запроса и место в запросе, где хотели редактировать параметры виртуальной таблицы, пожалуйста, не могу пока воспроизвести(

**Comment by MaksimDzyuba** [comment]
Здравствуйте, с Вашей помощью воспроизвести удалось, исправил, исправление войдут в 2023.2, спасибо большое!
