### ISSUE TITLE
Не открывается редактор СКД (в логе: Unhandled event loop exception)

### ISSUE THREAD

**Issue by alxint** [1C-Company/1c-edt-issues#1102]
### Описание ошибки

При открытие в редакторе СКД макетов отчетов в которых участвуют виртуальный таблицы Обороты или ОстаткиИОбороты с выбранной периодичностью Авто, и в полях запроса есть следующие поля

ПериодГод,
ПериодДекада,
ПериодКвартал,
ПериодМесяц,
ПериодПолугодие

открывается пустая форма или форма с заголовками страниц, в логе появляется ошибка Unhandled event loop exception (java.lang.AssertionError: PeriodFieldPresentationProvider adapter can be attached only to objects of 'DbViewFieldFieldDefWithPeriod' class)

### Как воспроизвести

1. Создать новый отчет
2. Добавить в отчет виртуальную таблицу Обороты или ОстаткиИОбороты
3. Выбрать периодичность Авто
4. Добавить в поля отчета поле ПериодГод
5. Поля запроса не заполняются
6. Сохранить макет
7. Попытаться открыть его заново

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/1776565/0d926f0b-c42c-4e4e-a208-59e9fb92ecda)

![image](https://github.com/1C-Company/1c-edt-issues/assets/1776565/328a63b9-5294-4b07-8bf9-7999f337382e)

### Ожидаемое поведение

Открывать макеты СКД для редактирования

### Лог рабочей области

null
org.eclipse.ui
Ошибка
Fri Jul 28 00:51:45 VLAT 2023
Unhandled event loop exception

java.lang.AssertionError: PeriodFieldPresentationProvider adapter can be attached only to objects of 'DbViewFieldFieldDefWithPeriod' class
	at com._1c.g5.v8.dt.md.resource.presentation.PeriodFieldPresentationProvider.getPresentation(PeriodFieldPresentationProvider.java:65)
	at com._1c.g5.v8.dt.metadata.dbview.impl.DbViewElementImpl.getPresentation(DbViewElementImpl.java:89)
	at com._1c.g5.v8.dt.dcs.DcsDataSetInfoV8LocalQuery.synonym(DcsDataSetInfoV8LocalQuery.java:917)
	at com._1c.g5.v8.dt.dcs.DcsDataSetInfoV8LocalQuery.multiPartSynonymCut(DcsDataSetInfoV8LocalQuery.java:883)
	at com._1c.g5.v8.dt.dcs.DcsDataSetInfoV8LocalQuery.multiPartSynonym(DcsDataSetInfoV8LocalQuery.java:850)
	at com._1c.g5.v8.dt.dcs.DcsDataSetInfoV8LocalQuery.synonym(DcsDataSetInfoV8LocalQuery.java:754)
	at com._1c.g5.v8.dt.dcs.DcsDataSetInfoV8LocalQuery.getFields(DcsDataSetInfoV8LocalQuery.java:1918)
	at com._1c.g5.v8.dt.dcs.DcsDataSetInfoV8LocalQuery.loadSelectInfo(DcsDataSetInfoV8LocalQuery.java:3126)
	at com._1c.g5.v8.dt.dcs.DcsDataSetInfoV8LocalQuery.loadSelect(DcsDataSetInfoV8LocalQuery.java:423)
	at com._1c.g5.v8.dt.dcs.DcsDataSetInfoV8LocalQuery.init(DcsDataSetInfoV8LocalQuery.java:332)
	at com._1c.g5.v8.dt.dcs.DcsDataSetInfoV8LocalQuery.init(DcsDataSetInfoV8LocalQuery.java:246)
	at com._1c.g5.v8.dt.dcs.ui.DataCompositionSchemaEditor.doCreateContent(DataCompositionSchemaEditor.java:650)
	at com._1c.g5.v8.dt.dcs.ui.ModelEditor.createPartControl(ModelEditor.java:137)
	at com._1c.g5.v8.dt.dcs.ui.DataCompositionSchemaEditor.createPartControl(DataCompositionSchemaEditor.java:1)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorEmbeddedEditorPage.createPageControls(DtGranularEditorEmbeddedEditorPage.java:145)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.createFormContentInternal(DtGranularEditorPage.java:553)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.lambda$2(DtGranularEditorPage.java:394)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:6012)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.lambda$1(DtGranularEditorPage.java:393)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.createFormContent(DtGranularEditorPage.java:390)
	at org.eclipse.ui.forms.editor.FormPage.lambda$0(FormPage.java:166)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.forms.editor.FormPage.createPartControl(FormPage.java:166)
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:480)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.pageChange(DtGranularEditor.java:1038)
	at com._1c.g5.v8.dt.internal.md.ui.editors.template.TemplateEditor.pageChange(TemplateEditor.java:227)
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1030)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:612)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:518)
	at com._1c.g5.v8.dt.internal.md.ui.editors.template.TemplateEditor.showEditorInput(TemplateEditor.java:113)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.createPages(DtGranularEditor.java:980)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.lambda$5(DtGranularEditor.java:635)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5101)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4584)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

### Версия 1С:EDT

Ruby 2023.1.0

### Операционная система

Linux

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

Возможно дублирует https://github.com/1C-Company/1c-edt-issues/issues/703, но там другая версия EDT и другая ошибка

**Comment by tretyakevich** [comment]
Исправлено 2023.1
