### ISSUE TITLE
[1CEDT] Ошибка при попытке обновить конфигурацию ИБ в ЕДТ 2023.1.0

### ISSUE THREAD

**Issue by TimurDD** [1C-Company/1c-edt-issues#1109]
```
Пробую перейти с ЕДТ/1С 2022.1.5 / 8.3.21.1993 на 2023.1.0 / 8.3.22.1923. При попытке обновить конфигурацию возникает ошибка (см. скрин).
Product name: 1C:Enterprise Development Tools
Product version: 1.28.0.289
Java home: C:\Program Files\BellSoft\LibericaJDK-11-Full
Java vm name: OpenJDK 64-Bit Server VM
Java vm info: mixed mode
Java version: 11.0.9
Java vendor: BellSoft
OS: win32
Total mem: 8 866
Free mem: 4 733
Cores: 24
***********************************
*	Файлы, приложенные к задаче, отправлены разработчикам. Ссылка в задаче не отображается./t*
***********************************
```

**Comment by nikolay-martynov** [comment]
Здравствуйте, Тимур. Если вы всё ещё можете воспроизвести ошибку, то пожалуйста скопируйте сюда (в виде файла или используя блок кода `` ) полное содержимое нижней части окна её отображающего. Интересует именно текстовое содержимое нижней части. К сожалению, по верхней части, представленной вами на картинке, установить причину ошибки не удается.
![image](https://github.com/1C-Company/1c-edt-issues/assets/13433348/643fb8be-dd4f-4d2b-860c-88072f88d673)

**Comment by TimurDD** [comment]
[Ошибка при загрузке ИБ (ЕДТ).txt](https://github.com/1C-Company/1c-edt-issues/files/12376387/default.txt)
Добрый! Вот полный текст (стек) ошибки.

**Comment by vadimeg** [comment]
Очень похоже на https://github.com/1C-Company/1c-edt-issues/issues/1115

**Comment by TimurDD** [comment]
@vadimeg да, очень похоже. Запускал на 2023.1.1 (файл ошибки).

**Comment by nikolay-martynov** [comment]
Здравствуйте, Тимур. Благодарю за снимок стека. Его вершина идентична тому, что в #1115 отличия только в способе запуска обновления. Исправление уже доступно в версии [2023.1.2](https://releases.1c.ru/version_files?nick=DevelopmentTools10&ver=2023.1.2)
Дополнительно в 2023.2 будет доступно улучшение диагностики для ошибочных ситуаций во время экспорта в формат платформы перед загрузкой конфигурации в информационную базу. В подобных ситуациях разбираться станет проще.
Пожалуйста подтвердите, что на 2023.1.2 проблема более не возникает.

**Comment by TimurDD** [comment]
Здравствуйте. Подтверждаю, в 2023.1.2 ошибки не возникает. Загрузка проекта (полная и частичная) выполняется без ошибок.

**Comment by nikolay-martynov** [comment]
Тимур, благодарю за подтверждение.

**Comment by Blazer574** [comment]
Во время выполнения операции экспорта произошло несколько ошибок
	java.util.concurrent.ExecutionException: com._1c.g5.v8.bm.common.check.BmAssertionException: The object does not belong to any namespace
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.awaitCompletion(ExportService.java:278)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.export(ExportService.java:226)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.work(ExportService.java:166)
	at com._1c.g5.v8.dt.internal.export.ExportOperation.run(ExportOperation.java:131)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.exportToXml(AbstractInfobaseConnection.java:662)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:268)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadConfiguration(ParticipantAwareInfobaseConnection.java:89)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadConfiguration(ReconnectableInfobaseConnection.java:142)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:107)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.updateConnectedInfobase(InfobaseSynchronization.java:609)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.reloadInfobase(InfobaseSynchronizationManager.java:320)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.reloadInfobase(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployConfiguration(DeployConfigurationWizard.java:517)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.createAndDeployNewApplication(DeployConfigurationWizard.java:236)



пробовал в 2023.1.2/1.3/1.4 везде идентичная ошибка. Пытаюсь загрузить проект с гита, при первом запуске базы предлагает полностью загрузить конфигурацию и потом выдает эту ошибку
