### ISSUE TITLE
2023.1.1 Ошибка загрузки и обновления конфигурации

### ISSUE THREAD

**Issue by a2080016** [1C-Company/1c-edt-issues#1115]
### Описание ошибки

Ошибка загрузки и обновления конфигурации

Во время выполнения операции экспорта произошла ошибка: 
	java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.awaitCompletion(ExportService.java:278)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.export(ExportService.java:226)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.work(ExportService.java:166)
	at com._1c.g5.v8.dt.internal.export.ExportOperation.run(ExportOperation.java:131)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.exportToXml(AbstractInfobaseConnection.java:662)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:268)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadConfiguration(ParticipantAwareInfobaseConnection.java:89)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadConfiguration(ReconnectableInfobaseConnection.java:142)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:107)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.updateConnectedInfobase(InfobaseSynchronization.java:609)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.reloadInfobase(InfobaseSynchronizationManager.java:320)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.reloadInfobase(Unknown Source)
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationBehaviourDelegate.publish(InfobaseApplicationBehaviourDelegate.java:95)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.publish(ApplicationManager.java:275)
	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.publish(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployConfiguration(DeployConfigurationWizard.java:595)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployExistingApplications(DeployConfigurationWizard.java:213)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.lambda$0(DeployConfigurationWizard.java:166)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.NullPointerException

### Как воспроизвести

1. Нажимаем "обновить конфигурацию..." в контекстном меню приложения
2. Выбираем загрузить конфигурацию полностью
3. Через пару секунд ошибка

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/24942027/9a1e3a8c-5b16-4181-ac1d-3b7db90b3bc3)

### Ожидаемое поведение

Конфа обновляется.
на 2022.2 обновляется без проблем

### Лог рабочей области

[1.log](https://github.com/1C-Company/1c-edt-issues/files/12322674/1.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/12322675/trace.log)

### Версия 1С:EDT

2023.1.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by tretyakevich** [comment]
Ошибка связана с конкретным состоянием конфигурации (в данном случае какая-то проблема с общим реквизитом). Не могли бы вы предоставить конфигурацию для воспроизведения?

**Comment by a2080016** [comment]
@tretyakevich  
Отправил в телеграмм. 
Пробовал реимпорт конфигурации под новой версией EDT, ошибка сохраняется.

**Comment by tretyakevich** [comment]
Исправлена в 2023.1.2
