### ISSUE TITLE
Не получается собрать проект с элементами транслируемого языка. Ошибка при выгрузке в XML 1C

### ISSUE THREAD

**Issue by JaneGlass73** [1C-Company/1c-edt-issues#1151]
### Описание ошибки

При попытке обновить конфигурацию базы данных из проекта из ветки, где добавлен транслируемый язык в процессе выгрузки файлов в XML возникает ошибка:
Во время выполнения операции экспорта произошла ошибка: 
	java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.awaitCompletion(ExportService.java:278)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.export(ExportService.java:226)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.work(ExportService.java:166)
	at com._1c.g5.v8.dt.internal.export.ExportOperation.run(ExportOperation.java:131)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.exportToXml(AbstractInfobaseConnection.java:662)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:268)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadConfiguration(ParticipantAwareInfobaseConnection.java:89)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadConfiguration(ReconnectableInfobaseConnection.java:142)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:107)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.updateConnectedInfobase(InfobaseSynchronization.java:609)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.reloadInfobase(InfobaseSynchronizationManager.java:320)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.reloadInfobase(Unknown Source)
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationBehaviourDelegate.publish(InfobaseApplicationBehaviourDelegate.java:95)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.publish(ApplicationManager.java:275)
	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.publish(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployConfiguration(DeployConfigurationWizard.java:595)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployExistingApplications(DeployConfigurationWizard.java:213)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.lambda$0(DeployConfigurationWizard.java:166)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.NullPointerException
	at com._1c.g5.v8.dt.internal.core.naming.SymbolicNameService.generateSymbolicName(SymbolicNameService.java:127)
	at com._1c.g5.v8.dt.core.naming.ISymbolicNameService$pbryglu.generateSymbolicName(Unknown Source)
	at com._1c.g5.v8.dt.export.xml.writer.ReferenceWriter.getReferenceRepresentation(ReferenceWriter.java:80)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.support.GraphicalSchemeItemAddressingAttributeWriter.writeReferenceValue(GraphicalSchemeItemAddressingAttributeWriter.java:125)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.support.GraphicalSchemeItemAddressingAttributeWriter.writeAttribute(GraphicalSchemeItemAddressingAttributeWriter.java:108)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.support.GraphicalSchemeItemAddressingAttributeWriter.write(GraphicalSchemeItemAddressingAttributeWriter.java:67)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.writers.GraphicalSchemeSpecifiedElementWriter.write(GraphicalSchemeSpecifiedElementWriter.java:72)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.writers.GraphicalSchemeXmlWriter.writeGraphicalSchemeActivityParams(GraphicalSchemeXmlWriter.java:254)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.writers.GraphicalSchemeXmlWriter.writeGraphicalSchemeFigureParams(GraphicalSchemeXmlWriter.java:226)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.writers.GraphicalSchemeXmlWriter.writeGraphicalSchemeItemProperties(GraphicalSchemeXmlWriter.java:140)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.writers.GraphicalSchemeXmlWriter.writeGraphicalSchemeItem(GraphicalSchemeXmlWriter.java:111)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.writers.GraphicalSchemeXmlWriter.writeGraphicalSchemeItems(GraphicalSchemeXmlWriter.java:101)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.writers.GraphicalSchemeXmlWriter.writeContent(GraphicalSchemeXmlWriter.java:73)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.writers.GraphicalSchemeXmlWriter.write(GraphicalSchemeXmlWriter.java:65)
	at com._1c.g5.v8.dt.bp.scheme.xml.serialization.export.BpSchemeExportUtil.export(BpSchemeExportUtil.java:92)
	at com.e1c.langtool.v8.dt.internal.bp.scheme.i18n.xml.extension.GraphicalSchemeXmlExporterExtension.copyTemplateWithLineFeedConversion(GraphicalSchemeXmlExporterExtension.java:108)
	at com._1c.g5.v8.dt.md.export.xml.impl.XmlExporterExtensionManager.copyTemplateWithLineFeedConversion(XmlExporterExtensionManager.java:50)
	at com._1c.g5.v8.dt.md.export.xml.impl.FlowchartXmlExporter.copyFlowChartFile(FlowchartXmlExporter.java:136)
	at com._1c.g5.v8.dt.md.export.xml.impl.FlowchartXmlExporter.work(FlowchartXmlExporter.java:98)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:364)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Как воспроизвести

1. Клонировать проект из репозитория [https://gitlab.xn--e1agfaq7azal4a.xn--p1ai/check/VD](https://gitlab.xn--e1agfaq7azal4a.xn--p1ai/check/VD) он публичный из ветки **dev_en/101**
2. По окончании импорта проекта в навигаторе выбрать вариант Экспорт --> Конфигурация в XML файлы. Через некоторое время после выгрузки появится указанная выше ошибка. Если переключить на ветку **dev/101** очистить проект и снова выгрузить то ошибки не будет.

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/a9333051-7aeb-4ff7-93ad-02bd536304d2)

### Ожидаемое поведение

Корректно выгруженная конфигурация в файлы XML или обновленная ИБ

### Лог рабочей области

[logs.zip](https://github.com/1C-Company/1c-edt-issues/files/12563657/logs.zip)

### Версия 1С:EDT

2023.1.4
2023.2.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by JaneGlass73** [comment]
@Erik773, подскажите есть надежда что в следующем релизе проблема будет устранена? Может хоть какое то будет понимание на каком объекте спотыкается выгрузка (оно происходит когда идёт выгрузка регламентированных отчетов) мы бы его как-нибудь подкорректировали или вырезали из конфигурации.

**Comment by Erik773** [comment]
Евгения, здравствуйте!
Задача с критическим лейблом и имеет высокий приоритет, поэтому будет рассмотрена при планировании одной из первых.
Как только она будет запланирована, в "Milestone" текущей задачи вы сможете увидеть в какой версии планируется исправление.
К сожалению, на данный момент более точную информацию предоставить не могу.

**Comment by JaneGlass73** [comment]
Спасибо.

**Comment by beg7** [comment]
Проблема известная, с ней сейчас работаем. 
Конфигурация в порядке. Сейчас Вам должен помочь Project -> Clean
Мы постараемся это исправить в ближайшей 2023.3.2

**Comment by JaneGlass73** [comment]
> Сейчас Вам должен помочь Project -> Clean

Добрый день! @beg7 И я конечно же это тоже пробовала. Но оно не помогает, иначе степень критичности была иная.

**Comment by MaksimDzyuba** [comment]
@JaneGlass73 Здравствуйте, а Вы пользуетесь snapshot, мы тут нашли с ними проблему, которая приводит к ошибка как у Вас. До выхода 2023.2.2 предлагаю отказаться от них, сделать очистку проекта полную, или удалить проект из рабочей области, а потом добавить его обратно, проблемы должны уйти

**Comment by JaneGlass73** [comment]
Здравствуйте @MaksimDzyuba !
> а Вы пользуетесь snapshot

![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/7d66d837-362f-4a62-a659-79d0bfa14ce1)
Так то да, пользовалась, но в этот раз нет, судя по тому, что папка пустая. Да и настройку папок в снимках сделала уже позже.

> сделать очистку проекта полную

Это тоже уже делала, Михаилу чуть выше об этом писала - не помогло. 


> удалить проект из рабочей области, а потом добавить его обратно

Максим,  я конечно же попробую и так тоже, только либо не поняла что именно нужно сделать, либо наши вселенные параллельные. Я прикладывала ссылку на репо, скажите, Вы пробовали по ней клонировать репозиторий и экспортировать файлы в XML? Или то что проблема должна уйти только предположение? Просто ситуация была такова, что репозиторий не я создавала, а коллеги по проекту. Я создала новую рабочую область, клонировала проект от коммита a9af5afc55397c740ced6c6513bb5860d51be3ad стартанула свою ветку dev_en/101 и попробовала перевести проект. По сути и переключений то не было, точнее я позже, после неудачи возвращалась на ветку dev/101 чтобы попробовать полную сборку сделать там - без изменений по трансляции, после возврата (снимки точно не использовала) делала полную очистку проекта, и только после этого файлы успешно конвертировались в XML. Переключение на ветку dev_en/101 с последующей очисткой проекта точно не приводило к безошибочной выгрузке. 

Что сейчас (ну не совсем сейчас, а сей4ас) сделала: создала новый воркспейс клонировала туда по ссылке проект сразу с ветки dev_en/101, в процессе клонирования меня EDT предупредил о том что ему не хватает "природы" трансляции, установила её с сайта https://edt.1c.ru/downloads/releases/plugins/language-tool/ версию 2023.2.0 перезапустила воркспейс после установки, выполнила очистку всех проектов, провела выгрузку в файлы, вот результат - в самом конце выгрузки сообщение об ошибке.
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/ca268965-2587-404a-9081-e0fb2b57415a)

Удалила оба проекта из навигатора 1С, но не удаляла их с диска, далее импортировала из клонированного Git снова эти два проекта (второй - расширение), дождалась обновления вторичных данных и снова запустила выгрузку 
Результат тот же самый: (40 секунд видео, самый конец перед ошибкой)

https://github.com/1C-Company/1c-edt-issues/assets/144486006/aded9f91-7207-4f8a-ba1d-ad8f11c47502

**Comment by JaneGlass73** [comment]
Обновила хранилище, коллеги с октября перешли на 23ю платформу и накатили последние релизы от поставщика, от метки 1.0.3.4 сделала новую ветку, проверила выгрузку в XML - всё экспортируется
![image](https://github.com/1C-Company/1c-edt-issues/assets/144486006/a3353c9a-4689-4c30-b519-76add24295f2)
Добавила транслируемый язык, и добавила синонимы для трёх объектов - Подсистема Администрирование, справочники Контрагенты, Банки. Запустила экспорт конфигурации в XML. Как вижу - результата тот же, см. видео 12 с. Изменения зафиксировала в ветку dev_en/103 ссылка на хранилище в первичном обращении. 

https://github.com/1C-Company/1c-edt-issues/assets/144486006/877c7e99-6b21-4f4a-9273-2a3644bacf65

Убедительная просьба всё таки клонировать хранилище с копии репозитория (оно с открытым доступом), в пустую новую рабочую область, ветку dev_en/103 увидите проблему во всей её красе. Я уже не знаю что ещё нужно предоставить, чтобы мне поверили. 
[Logs.zip](https://github.com/1C-Company/1c-edt-issues/files/13452578/Logs.zip)

**Comment by JaneGlass73** [comment]
А вот теперь самое интересное: несмотря на ошибку, файлы в XML всё же были выгружены в каталог, прежде чем удалить его, я посмотрела содержимое, и как мне показалось вроде как все файлы на месте, по крайней мере configuration.xml в корне присутствовал и был похож на нормальный. Я попыталась их загрузить в пустую базу, и тут тоже интересные чудеса ibcmd (8.3.23.1912) подвис без признаков жизни на 10й секунде загрузки, оставила его в таком состоянии может к утру и скажет чего ему не хватает, а вот конфигуратор (я то надеялась что хоть конфигуратор выругается чего не хватает) той же версии вполне успешно файлы загрузил и база запустилась, как с англоязычным интерфейсом, так и с русскоязычным. Те объекты, у которых синонимы "перевела" действительно получили в итоге свои синонимы, а в модулях строки НСтр изменились (отформатировались), т.е. по всем признакам трансляция всё же произошла как ожидалось.
![1700770603379](https://github.com/1C-Company/1c-edt-issues/assets/144486006/0857a6b9-dbc1-4d95-b28a-6bfbe1411312)
В режиме исполнения тоже ожидаемые изменения увидела:
![1700770707887](https://github.com/1C-Company/1c-edt-issues/assets/144486006/ace56608-c234-4ae6-a552-f13d40e3165f)
Возможно и в прошлый раз бы тоже загрузилось...
Осталось решить всё таки откуда появляется ошибка в самом конце экспорта в XML, судя по всему не будь её агент конфигуратора так же молча бы собрал оттранслированную конфигурацию. И почему виснет ibcmd, но это уже даже не знаю куда об этом писать, причём на файлах выгрузки без трансляции он не виснет и благополучно загружает все XML в ИБ, результат сравнения я выше привела на снимках.

**Comment by MaksimDzyuba** [comment]
@JaneGlass73 по поводу ibcmd, могу сказать точно, что там еще на 8.3.23 сохраняется ошибка,которая может приводить к зависанию, как у Вас, коллеги из платформы в курсе, решают ее (вроде как даже решили, но еще нет переноса в 8.3.23).

**Comment by MaksimDzyuba** [comment]
@JaneGlass73 по поводу https://github.com/1C-Company/1c-edt-issues/issues/1151#issuecomment-1824603516, я пройду Ваш путь еще раз, вчера у меня проблемы не было, но я не много не так делал, а тут еще и lang-tool, отпишусь по результату

**Comment by NikitaMikhaylovSB** [comment]
В текущей публичной 8.3.23.1997 исправили одну из самых критичных ошибок (зависание)
проверено

**Comment by MaksimDzyuba** [comment]
@JaneGlass73 здравствуйте, ошибку подтверждаю, она воспроизводится, если установлен плагин lang-tool, обход сейчас есть, но нужно изменить данные, а именно  в графической схеме "VD\znvuh32modeling\src\BusinessProcesses\ЭкспертизаЗаявкиНаОбеспечение\Flowchart.scheme" нужно удалить все теги 
"<AddressingAttribute ref=", которые содержат значения вида "<Value xsi:nil="true"/>".

![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/5cb4c385-a228-42fe-9634-f20371995b8d)
![image](https://github.com/1C-Company/1c-edt-issues/assets/77277424/f880c9e3-7c73-4c52-93fa-a991a1edcb8c).

Но важно, после того, как мы выпустим фикс. вернуть изменения обратно. Еще возможность пока не пользоваться плагином lang-tool

С нашей стороны, мы поправим ошибку в ближайшей 2023.2.

**Comment by JaneGlass73** [comment]
@MaksimDzyuba , я лучше подожду, был момент когда было наивысрочно, но сейчас уже немного переиграли приоритеты и время пока ещё есть. Если вдруг приспичит - обход Вы написали. Огромное спасибо!

**Comment by MaksimDzyuba** [comment]
Вам спасибо за терпение, затянули мы сильно с правками

**Comment by tretyakevich** [comment]
Исправлено в 2023.3

**Comment by JaneGlass73** [comment]
@tretyakevich , здравствуйте! Исправлено в 2023.3.3? Я в логе новостей и исправленных ошибок (https://dl03.1c.ru/content/DevelopmentTools/2023_3_3/1cv8upd_2023_3_3.htm#i156__err.2023.3.3) не нашла упоминания о решении этой проблемы

**Comment by MaksimDzyuba** [comment]
@JaneGlass73 Здравствуйте, вообще она исправлена в 2023.2.3, но реально запись в апдейт об этом не попала, разбираемся, исправление точно есть в 2023.3.0 и старше

**Comment by JaneGlass73** [comment]
@MaksimDzyuba , Спасибо за информацию!

**Comment by bostanov** [comment]
Доброго времени суток.
Увы в 2023.3.6 та же проблема. Описанный выше вариант не сработал. Есть какие то еще варианты ?

**Comment by MaksimDzyuba** [comment]
Здравствуйте, я верно понял, что во время экспорта летит ошибка про NullPointerException и экспорт не проходит?

**Comment by JaneGlass73** [comment]
@MaksimDzyuba , @bostanov  Максим, здравствуйте! Мы можем предоставить ссылку на хранилище (private) и логин с паролем с доступом к нему, чтобы вы могли клонировать и воспроизвести проблему. От Вас нужен только почтовый адрес или УЗ телеграмм, куда отправить логин и пароль. Могу Алмазу Насибуллину @AlmazNasibullin отправить в телегу. У меня есть его контакт можно мне написать в телегу @JaneGlass73.

**Comment by MaksimDzyuba** [comment]
@JaneGlass73 Здравствуйте, написал Вам в телеграмме
