### ISSUE TITLE
<bdi>[1CEDT] Ошибка при попытке обновить конфигурацию ИБ в ЕДТ 2023.1.2</bdi><span></span>

### ISSUE THREAD

**Issue by Blazer574** [1C-Company/1c-edt-issues#1181]
### Описание ошибки

Копирую проект с гита, создаю новую ИБ для запуска и пытаюсь ее обновить, и выскакивает ошибка:
[Скачать полный текст ошибки](https://drive.google.com/file/d/1fWK88f8tkWwaCkgvc9w9QTdz1pX8q6hv/view?usp=drive_link)

Во время выполнения операции экспорта произошло несколько ошибок
	java.util.concurrent.ExecutionException: com._1c.g5.v8.bm.common.check.BmAssertionException: The object does not belong to any namespace
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.awaitCompletion(ExportService.java:278)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.export(ExportService.java:226)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.work(ExportService.java:166)
	at com._1c.g5.v8.dt.internal.export.ExportOperation.run(ExportOperation.java:131)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.exportToXml(AbstractInfobaseConnection.java:662)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:268)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadConfiguration(ParticipantAwareInfobaseConnection.java:89)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadConfiguration(ReconnectableInfobaseConnection.java:142)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:107)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.updateConnectedInfobase(InfobaseSynchronization.java:609)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.reloadInfobase(InfobaseSynchronizationManager.java:320)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.reloadInfobase(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployConfiguration(DeployConfigurationWizard.java:517)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.createAndDeployNewApplication(DeployConfigurationWizard.java:236)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.lambda$0(DeployConfigurationWizard.java:170)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: com._1c.g5.v8.bm.common.check.BmAssertionException: The object does not belong to any namespace
	at com._1c.g5.v8.bm.core.internal.transaction.BmPlatformTransaction.toTransactionObject(BmPlatformTransaction.java:153)
	at com._1c.g5.v8.dt.md.export.xml.impl.CommonPictureXmlExporter$1.execute(CommonPictureXmlExporter.java:141)
	at com._1c.g5.v8.dt.md.export.xml.impl.CommonPictureXmlExporter$1.execute(CommonPictureXmlExporter.java:1)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:842)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:777)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeReadOnlyTask(Reactor.java:151)
	at com._1c.g5.v8.dt.internal.core.platform.bm.BmModelManager.executeReadOnlyTask(BmModelManager.java:473)
	at com._1c.g5.v8.dt.core.platform.IBmModelManager$pbryglu.executeReadOnlyTask(Unknown Source)
	at com._1c.g5.v8.dt.md.export.xml.impl.CommonPictureXmlExporter.writeCommonPicturePictureXml(CommonPictureXmlExporter.java:134)
	at com._1c.g5.v8.dt.md.export.xml.impl.CommonPictureXmlExporter.work(CommonPictureXmlExporter.java:82)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:364)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Как воспроизвести

1. Перейдите в `...`
2. Кликните по `....`
3. Прокрутите вниз до `....`
4. Смотрите ошибку в `....`

### Ожидаемое поведение

должна загрузиться база

### Лог рабочей области

Во время выполнения операции экспорта произошло несколько ошибок
	java.util.concurrent.ExecutionException: com._1c.g5.v8.bm.common.check.BmAssertionException: The object does not belong to any namespace
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.awaitCompletion(ExportService.java:278)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.export(ExportService.java:226)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.work(ExportService.java:166)
	at com._1c.g5.v8.dt.internal.export.ExportOperation.run(ExportOperation.java:131)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.exportToXml(AbstractInfobaseConnection.java:662)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:268)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadConfiguration(ParticipantAwareInfobaseConnection.java:89)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadConfiguration(ReconnectableInfobaseConnection.java:142)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:107)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.updateConnectedInfobase(InfobaseSynchronization.java:609)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.reloadInfobase(InfobaseSynchronizationManager.java:320)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.reloadInfobase(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployConfiguration(DeployConfigurationWizard.java:517)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.createAndDeployNewApplication(DeployConfigurationWizard.java:236)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.lambda$0(DeployConfigurationWizard.java:170)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: com._1c.g5.v8.bm.common.check.BmAssertionException: The object does not belong to any namespace
	at com._1c.g5.v8.bm.core.internal.transaction.BmPlatformTransaction.toTransactionObject(BmPlatformTransaction.java:153)
	at com._1c.g5.v8.dt.md.export.xml.impl.CommonPictureXmlExporter$1.execute(CommonPictureXmlExporter.java:141)
	at com._1c.g5.v8.dt.md.export.xml.impl.CommonPictureXmlExporter$1.execute(CommonPictureXmlExporter.java:1)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:842)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:777)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeReadOnlyTask(Reactor.java:151)
	at com._1c.g5.v8.dt.internal.core.platform.bm.BmModelManager.executeReadOnlyTask(BmModelManager.java:473)
	at com._1c.g5.v8.dt.core.platform.IBmModelManager$pbryglu.executeReadOnlyTask(Unknown Source)
	at com._1c.g5.v8.dt.md.export.xml.impl.CommonPictureXmlExporter.writeCommonPicturePictureXml(CommonPictureXmlExporter.java:134)
	at com._1c.g5.v8.dt.md.export.xml.impl.CommonPictureXmlExporter.work(CommonPictureXmlExporter.java:82)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:364)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Версия 1С:EDT

версия 2023.1.2/версия 2023.1.3/версия 2023.1.4

### Операционная система

Windows

**Comment by Erik773** [comment]
Здравствуйте @Blazer574!

> Перейдите в ...
> Кликните по ....
> Прокрутите вниз до ....
> Смотрите ошибку в ....

Могли бы Вы, пожалуйста, уточнить сценарий. Еще, если возможно прикрепите, пожалуйста, файлы логов рабочей области ЕДТ  (.log, .bak.log и trace.log в папке \.metadata проекта).
Вы используете типовую конфигурацию? Есть ли у Вас возможность предоставить проект конфигурации на котором воспроизводится проблема?

**Comment by Erik773** [comment]
Закрыто, так как не предоставлены запрошенные данные для воспроизведения проблемы.
При предоставлении данных, просьба задачу переоткрыть.
