### ISSUE TITLE
Model check thrown an exception

### ISSUE THREAD

**Issue by Desar14** [1C-Company/1c-edt-issues#12]
## Опишите ошибку

Исключение после очистки проекта и его повторной проверке.

## Скриншоты

![image](https://user-images.githubusercontent.com/66671103/137322766-7515986b-d9d7-4ffc-94d9-cd45290a611b.png)

## Окружение (пожалуйста укажите информацию):

 - OS: Win10
 - Версия 1C:Code-Style-V8 0.1.0.131
 - Версия 1C:EDT 2021.2.6

## Дополнительная информация
 
java.util.concurrent.CancellationException
	at com._1c.g5.v8.derived.computer.DerivedDataComputerMonitorHolder.dropIfCancelled(DerivedDataComputerMonitorHolder.java:35)
	at com._1c.g5.v8.dt.internal.form.datasourceinfo.property.DynamicListPropertyInfoProvider.dynamicListProperty(DynamicListPropertyInfoProvider.java:453)
	at com._1c.g5.v8.dt.internal.form.datasourceinfo.property.DynamicListPropertyInfoProvider.addDynamicFieldsPropertyInfos(DynamicListPropertyInfoProvider.java:201)
	at com._1c.g5.v8.dt.internal.form.datasourceinfo.property.DynamicListPropertyInfoProvider.getPropertyInfo(DynamicListPropertyInfoProvider.java:115)
	at com._1c.g5.v8.dt.form.model.impl.PropertyInfoProviderRegistryImpl.getPropertyInfo(PropertyInfoProviderRegistryImpl.java:118)
	at com._1c.g5.v8.dt.form.model.impl.FormPropertyInfoExtension.gatherOrdinaryPropertyInfoCollection(FormPropertyInfoExtension.java:197)
	at com._1c.g5.v8.dt.form.model.impl.FormPropertyInfoExtension.getPropertyInfoBySource(FormPropertyInfoExtension.java:60)
	at com._1c.g5.v8.dt.form.model.PropertyInfo.getPropertyInfos(PropertyInfo.java:216)
	at com._1c.g5.v8.dt.form.service.datasourceinfo.impl.DataSourceInfoAssociationService.get(DataSourceInfoAssociationService.java:413)
	at com._1c.g5.v8.dt.form.service.datasourceinfo.impl.DataSourceInfoAssociationService.findPropertyInfo(DataSourceInfoAssociationService.java:70)
	at com._1c.g5.v8.dt.form.service.datasourceinfo.IDataSourceInfoAssociationService$pbryglu.findPropertyInfo(Unknown Source)
	at com.e1c.v8codestyle.form.check.DataPathReferredObjectCheck.check(DataPathReferredObjectCheck.java:123)
	at com.e1c.g5.v8.dt.check.components.BasicCheck.check(BasicCheck.java:76)
	at com.e1c.g5.v8.dt.internal.check.CheckExecutor.validateModel(CheckExecutor.java:297)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer.check(ModelCheckDerivedDataComputer.java:130)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer.doFullRebuildForObject(ModelCheckDerivedDataComputer.java:233)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer.doFullRebuild(ModelCheckDerivedDataComputer.java:190)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer$1.execute(ModelCheckDerivedDataComputer.java:104)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer$1.execute(ModelCheckDerivedDataComputer.java:1)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:706)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:667)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeReadOnlyTask(Reactor.java:146)
	at com._1c.g5.v8.bm.integration.internal.BmModel.executeReadonlyTask(BmModel.java:227)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer.compute(ModelCheckDerivedDataComputer.java:110)
	at com._1c.g5.v8.internal.derived.WorkerManager$TaskProcessor.processContextBatch(WorkerManager.java:330)
	at com._1c.g5.v8.internal.derived.WorkerManager$TaskProcessor.call(WorkerManager.java:165)
	at com._1c.g5.v8.internal.derived.WorkerManager$TaskProcessor.call(WorkerManager.java:1)
	at com._1c.g5.v8.internal.derived.scheduler.DerivedDataExecutorPool$2.get(DerivedDataExecutorPool.java:256)
	at com._1c.g5.v8.internal.derived.scheduler.DerivedDataExecutorPool$2.get(DerivedDataExecutorPool.java:1)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Desar14** [comment]
После обновления до версии плагина v8-code-slyle 0.1.0.145 данная ошибка перестала возникать. Подозреваю, что после исправления вот этого ишуза https://github.com/1C-Company/v8-code-style/issues/850
