### ISSUE TITLE
EDT 2023.2.1 не открывается СКД в расширении

### ISSUE THREAD

**Issue by NekoUnreal** [1C-Company/1c-edt-issues#1214]
### Описание ошибки

EDT 2023.2.1 не открывается СКД ни одного отчета в расширении, в самой конфигурации всё открывается нормально. Если отчеты перести во внешний или в конфигурацию СКД открывается нормально. Очистка и перезагрузка расширения не дают эффекта.

### Как воспроизвести

Открыть любу схему компоновки данных в расширении

### Скриншоты

![image_2023-10-21_11-11-06](https://github.com/1C-Company/1c-edt-issues/assets/94066963/7b6fd5c9-9ace-4b54-b64d-d302640f228e)

### Ожидаемое поведение

Должно появится окно редактирования запроса

### Лог рабочей области

!ENTRY org.eclipse.ui 4 0 2023-10-21 11:05:18.410
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at com._1c.g5.v8.dt.moxel.sheet.SheetFactory.createLanguageSettings(SheetFactory.java:286)
	at com._1c.g5.v8.dt.moxel.sheet.SheetFactory.createLanguageSettings(SheetFactory.java:130)
	at com._1c.g5.v8.dt.moxel.sheet.SheetFactory.createEmbeddedSpreadsheetDocument(SheetFactory.java:96)
	at com._1c.g5.v8.dt.dcs.ui.templates.Templates$4.execute(Templates.java:652)
	at com._1c.g5.v8.dt.dcs.ui.templates.Templates$4.execute(Templates.java:1)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.LegacyTaskWrapper.execute(LegacyTaskWrapper.java:48)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:842)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:777)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:160)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.BmModel.execute(BmModel.java:203)
	at com._1c.g5.v8.dt.dcs.ui.templates.Templates.getOrCreateSpreadsheetDocument(Templates.java:643)
	at com._1c.g5.v8.dt.dcs.ui.templates.Templates.createSpreadsheetSashPart(Templates.java:597)
	at com._1c.g5.v8.dt.dcs.ui.templates.Templates.<init>(Templates.java:188)
	at com._1c.g5.v8.dt.dcs.ui.DataCompositionSchemaEditor.createTemplates(DataCompositionSchemaEditor.java:1256)
	at com._1c.g5.v8.dt.dcs.ui.DataCompositionSchemaEditor.doCreateContent(DataCompositionSchemaEditor.java:667)
	at com._1c.g5.v8.dt.dcs.ui.ModelEditor.createPartControl(ModelEditor.java:137)
	at com._1c.g5.v8.dt.dcs.ui.DataCompositionSchemaEditor.createPartControl(DataCompositionSchemaEditor.java:1)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorEmbeddedEditorPage.createPageControls(DtGranularEditorEmbeddedEditorPage.java:145)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.createFormContentInternal(DtGranularEditorPage.java:553)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.lambda$2(DtGranularEditorPage.java:394)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4779)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.lambda$1(DtGranularEditorPage.java:393)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.createFormContent(DtGranularEditorPage.java:390)
	at org.eclipse.ui.forms.editor.FormPage.lambda$0(FormPage.java:166)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.forms.editor.FormPage.createPartControl(FormPage.java:166)
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:480)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.pageChange(DtGranularEditor.java:1038)
	at com._1c.g5.v8.dt.internal.md.ui.editors.template.TemplateEditor.pageChange(TemplateEditor.java:227)
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1030)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:612)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:518)
	at com._1c.g5.v8.dt.internal.md.ui.editors.template.TemplateEditor.showEditorInput(TemplateEditor.java:113)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.createPages(DtGranularEditor.java:980)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.lambda$5(DtGranularEditor.java:635)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4035)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3635)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

### Версия 1С:EDT

Ruby 2023.2.1

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

### Дополнительная информация

КА 2.4.13.282
Режим совместимости конфигурации и расширения 8.3.23

**Comment by Erik773** [comment]
Здравствуйте @NekoUnreal!
Подскажите, пожалуйста, каким образом вы добавляете макет в расширение?
Могли бы вы, пожалуйста, приложить полный логи рабочей области?

**Comment by NekoUnreal** [comment]
> Здравствуйте @NekoUnreal! Подскажите, пожалуйста, каким образом вы добавляете макет в расширение? Могли бы вы, пожалуйста, приложить полные логи рабочей области?

Это касается и заимствованных из основной конфигурации отчетов, и созданных в расширении отчетов, это лог когда в расширении просто создал новый отчет, добавил основную схему компоновки данных. И всё больше ничего сделать не даёт. Причем если создать внешний отчет привязанный к этой же конфигурации то всё работает как положено.

[Error.log](https://github.com/1C-Company/1c-edt-issues/files/13066864/Error.log)

![image](https://github.com/1C-Company/1c-edt-issues/assets/94066963/95ccd41c-f00c-4ec8-b37e-0148c04c01cb)

**Comment by wolfandw** [comment]
Проверьте у конфигурации расширения свойство Основной язык. Должно быть заполнено

**Comment by NekoUnreal** [comment]
> Проверьте у конфигурации расширения свойство Основной язык. Должно быть заполнено. Хотя, это в случае если свойство на контроле, тогда поможет. Если нет, то не поможет. В принципе, ошибку зарегистрировали, нашли и поправили.

O_ooo, нет слов одни эмоции. Достаточно было в расширении указать Основной язык, и подтянуть значение из конфигурации. И чудо СКД начали открываться и редактироваться макеты. Странный конечно баг...

![image](https://github.com/1C-Company/1c-edt-issues/assets/94066963/57500df8-adc2-45da-8260-18598fbf16ca)

**Comment by wolfandw** [comment]
Вошло в 2023.2.2
