### ISSUE TITLE
При переходе на новую версию EDT и повышении версии платформы до 8.3.23 не импортируется новый проект из ИБ

### ISSUE THREAD

**Issue by mrscylla** [1C-Company/1c-edt-issues#1246]
### Описание ошибки

Не инициализируется контекст проекта после импорта в новый проект из ИБ, после повышения версии EDT и платформы 1С

**В новый чистый воркспейс импорт происходит корректно**

### Как воспроизвести

Дано: Был установлен EDT 2023.1.4 и в нем же создан воркспэйс.
1. Установлен EDT 2023.2.1 и загружен тот же воркспейс
2. Единственный проект был удален
3. Запущен импорт нового проекта из ИБ (несколько попыток и с расширениями и без)

Экспорт файлов происходит, иногда не создается приложение иногда создается но проект не связывается с ним

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/402495/0f188235-80ca-47c8-b7dc-b3c71c501f30)

### Ожидаемое поведение

* импорт должен доходить до конца (должен инициализироваться контекст проекта)
* закрытие и открытие проекта должно доходить до конца
* проект и приложение в итоге должны быть связанны и дерево метаданных должно отображаться

### Лог рабочей области

com._1c.g5.v8.dt.lifecycle.LifecycleException: Failed to perform phase LINKING for context com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator$LinkingContext@68728e7e
  at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.performPhase(ServicesOrchestrator.java:281)
  at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startContext(ServicesOrchestrator.java:186)
  at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startServices(ServicesOrchestrator.java:78)
  at com._1c.g5.v8.dt.lifecycle.IServicesOrchestrator$pbryglu.startServices(Unknown Source)
  at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startContext(WorkspaceOrchestrator.java:763)
  at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startWorkspaceProjects(WorkspaceOrchestrator.java:371)
  at com._1c.g5.v8.dt.internal.core.lifecycle.DtProjectResourceLifecycleBootstrap$DefaultContextsStartJob.run(DtProjectResourceLifecycleBootstrap.java:698)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.RuntimeException: com._1c.g5.v8.dt.validation.marker.MarkerException: Failed to initialize index
  at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:224)
  at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:1)
  at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.performPhase(ServicesOrchestrator.java:270)
  ... 7 more
Caused by: com._1c.g5.v8.dt.validation.marker.MarkerException: Failed to initialize index
  at com._1c.g5.v8.dt.internal.validation.marker.MarkerManager.wrapAndRethrow(MarkerManager.java:1037)
  at com._1c.g5.v8.dt.internal.validation.marker.MarkerManager.linking(MarkerManager.java:267)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:214)
  ... 9 more
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by another program: D:\Users\EDT\.metadata\.plugins\com._1c.g5.v8.dt.validation\index\write.lock
  at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:130)
  at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
  at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
  at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:729)
  at com._1c.g5.v8.dt.internal.validation.marker.MarkerManager.init(MarkerManager.java:927)
  at com._1c.g5.v8.dt.internal.validation.marker.MarkerManager.linking(MarkerManager.java:250)
  ... 14 more

### Версия 1С:EDT

1C:Enterprise Development Tools, версия 2023.2.1

### Операционная система

Windows

**Comment by dsavenko** [comment]
Проверили, в 2023.3 ошибка не повторяется.
