### ISSUE TITLE
Ошибка при импорте шаблонов строенного языка

### ISSUE THREAD

**Issue by AnanyevAl** [1C-Company/1c-edt-issues#1252]
### Описание ошибки

Ошибка в том что при импорте шаблонов наблюдается зависание, потом ни чего не происходит.
В версии 2023.2.1 импорт проходит без проблем

### Как воспроизвести

1. Перейдите в параметры -> встроенный язык -> шаблоны
2. Кликните по `Импортировать` и выберите файл
3. Смотрите ошибку в .log

### Ожидаемое поведение

шаблоны должны быть импортированы

### Лог рабочей области

!ENTRY org.eclipse.ui 4 0 2023-11-26 10:55:44.379
!MESSAGE Unhandled event loop exception
!STACK 0
com._1c.g5.wiring.ServiceUnavailableException: Service wait timed out after 60 000 milliseconds
	at com._1c.g5.internal.wiring.ConfigurableImportDecorator$ConfigurableImport.get(ConfigurableImportDecorator.java:80)
	at org.ops4j.peaberry.util.DelegatingImport.get(DelegatingImport.java:44)
	at org.ops4j.peaberry.util.decorators.StickyDecorator$StickyImport.get(StickyDecorator.java:81)
	at com._1c.g5.ides.monitoring.IMonitoringEventDispatcher$pbryglu.dispatchEvent(Unknown Source)
	at com.e1c.g5.v8.dt.bsl.ui.templates.preferences.BslTemplatePreferencePage.addEventToMonitoring(BslTemplatePreferencePage.java:335)
	at com.e1c.g5.v8.dt.bsl.ui.templates.preferences.BslTemplatePreferencePage.handleImport(BslTemplatePreferencePage.java:197)
	at com.e1c.g5.v8.dt.lcore.ui.templates.preferences.AbstractTemplatePreferencePage.lambda$3(AbstractTemplatePreferencePage.java:225)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

### Версия 1С:EDT

Ruby 2023.2.2

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

[ШаблоныEDT.zip](https://github.com/1C-Company/1c-edt-issues/files/13465950/EDT.zip)
файл шаблонов

**Comment by MaksimDzyuba** [comment]
Здравствуйте, попробовал на 2023.3.0, не удалось воспроизвести. Если проблема все еще актуально, то просьба переоткрыть ошибку и приложить полный лог системы
![bandicam-2024-03-06-17-21-52-248](https://github.com/1C-Company/1c-edt-issues/assets/77277424/c081e7a1-aec6-4b26-afde-c2948fb8ad63)
