### ISSUE TITLE
EDT запустила пересборку всех проектов рабочей области при импорте проекта конфигурации

### ISSUE THREAD

**Issue by LesN1ck** [1C-Company/1c-edt-issues#1302]
### Описание ошибки

При импорте проекта конфигурации EDT поймала ошибку, в результате которой среда решила пересобрать все проекты, размещенные в рабочей области.

В логе есть следующий текст:

```
!ENTRY com._1c.g5.v8.dt.lifecycle 1 0 2024-01-31 15:48:41.462
!MESSAGE Starting phase POST_RESOURCE_LOADING of context ProjectContext: UPP_SALAIR

!ENTRY com._1c.g5.v8.dt.core 4 0 2024-01-31 15:48:41.657
!MESSAGE Запрошено восстановление проектов по причине ошибок, возникших в DefaultContextStartJob
!STACK 0
com._1c.g5.v8.dt.lifecycle.LifecycleException: Failed to perform phase POST_RESOURCE_LOADING for context ProjectContext: UPP_SALAIR
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.performPhase(ServicesOrchestrator.java:281)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startContext(ServicesOrchestrator.java:209)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startServices(ServicesOrchestrator.java:78)
	at com._1c.g5.v8.dt.lifecycle.IServicesOrchestrator$pbryglu.startServices(Unknown Source)
	at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startContext(WorkspaceOrchestrator.java:771)
	at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startWorkspaceProjects(WorkspaceOrchestrator.java:371)
	at com._1c.g5.v8.dt.internal.core.lifecycle.DtProjectResourceLifecycleBootstrap$DefaultContextsStartJob.run(DtProjectResourceLifecycleBootstrap.java:714)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Узел параметров "com.e1c.g5.v8.dt.check" был удален.
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:224)
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:1)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.performPhase(ServicesOrchestrator.java:270)
	... 7 more
Caused by: java.lang.IllegalStateException: Узел параметров "com.e1c.g5.v8.dt.check" был удален.
	at org.eclipse.core.internal.preferences.EclipsePreferences.checkRemoved(EclipsePreferences.java:165)
	at org.eclipse.core.internal.resources.ProjectPreferences.internalGet(ProjectPreferences.java:435)
	at org.eclipse.core.internal.preferences.EclipsePreferences.getBoolean(EclipsePreferences.java:451)
	at com.e1c.g5.v8.dt.internal.check.git.GitMarkerFilterPreferences.isHideGitBasedCheckResults(GitMarkerFilterPreferences.java:50)
	at com.e1c.g5.v8.dt.internal.check.git.GitChangesProcessor.getChangeInfo(GitChangesProcessor.java:145)
	at com.e1c.g5.v8.dt.internal.check.git.GitMarkerFilterManager.isFiltrationEnabledForProject(GitMarkerFilterManager.java:254)
	at com.e1c.g5.v8.dt.internal.check.git.GitMarkerFilterManager.processProject(GitMarkerFilterManager.java:561)
	at com.e1c.g5.v8.dt.internal.check.git.GitMarkerFilterManager.start(GitMarkerFilterManager.java:207)
	at jdk.internal.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:214)
	... 9 more

```
В файле телеметрии при этом обнаружена следующая запись:

```
<<<<<Telemetry dump reason: Error during DefaultContextStartJob
Exception: 
com._1c.g5.v8.dt.lifecycle.LifecycleException: Failed to perform phase POST_RESOURCE_LOADING for context ProjectContext: UPP_SALAIR
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.performPhase(ServicesOrchestrator.java:281)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startContext(ServicesOrchestrator.java:209)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startServices(ServicesOrchestrator.java:78)
	at com._1c.g5.v8.dt.lifecycle.IServicesOrchestrator$pbryglu.startServices(Unknown Source)
	at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startContext(WorkspaceOrchestrator.java:771)
	at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startWorkspaceProjects(WorkspaceOrchestrator.java:371)
	at com._1c.g5.v8.dt.internal.core.lifecycle.DtProjectResourceLifecycleBootstrap$DefaultContextsStartJob.run(DtProjectResourceLifecycleBootstrap.java:714)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Узел параметров "com.e1c.g5.v8.dt.check" был удален.
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:224)
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:1)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.performPhase(ServicesOrchestrator.java:270)
	... 7 more
Caused by: java.lang.IllegalStateException: Узел параметров "com.e1c.g5.v8.dt.check" был удален.
	at org.eclipse.core.internal.preferences.EclipsePreferences.checkRemoved(EclipsePreferences.java:165)
	at org.eclipse.core.internal.resources.ProjectPreferences.internalGet(ProjectPreferences.java:435)
	at org.eclipse.core.internal.preferences.EclipsePreferences.getBoolean(EclipsePreferences.java:451)
	at com.e1c.g5.v8.dt.internal.check.git.GitMarkerFilterPreferences.isHideGitBasedCheckResults(GitMarkerFilterPreferences.java:50)
	at com.e1c.g5.v8.dt.internal.check.git.GitChangesProcessor.getChangeInfo(GitChangesProcessor.java:145)
	at com.e1c.g5.v8.dt.internal.check.git.GitMarkerFilterManager.isFiltrationEnabledForProject(GitMarkerFilterManager.java:254)
	at com.e1c.g5.v8.dt.internal.check.git.GitMarkerFilterManager.processProject(GitMarkerFilterManager.java:561)
	at com.e1c.g5.v8.dt.internal.check.git.GitMarkerFilterManager.start(GitMarkerFilterManager.java:207)
	at jdk.internal.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:214)
	... 9 more

```
Ошибку считаю критической, поскольку операция импорта одного проекта привела к невозможности работы в других проектах рабочей области до тех пор, пока не выполнится их пересборка.

Фрагменты лога и файла трассировки прилагаю.

### Как воспроизвести

-

### Ожидаемое поведение

Прежде всего, непонятна сама природа ошибки, но кажется, что пересборка проекта после его импорта в штатном режиме происходить не должна. Также крайне неприятно, что запускается пересборка ВСЕХ проектов в рабочей области - даже тех, которые никак не связаны с импортируемым проектом.

### Лог рабочей области

[log.log](https://github.com/1C-Company/1c-edt-issues/files/14112601/log.log)
[telemetry.log](https://github.com/1C-Company/1c-edt-issues/files/14112603/telemetry.log)

### Версия 1С:EDT

Ruby 2023.3.0

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Проблема возникла при импорте проекта конфигурации УПП в рабочую область на платформе 8.3.23.1997, версия проекта - 8.3.23. При этом проблема не является регулярно повторяемой - какое-то время назад импорт той же самой конфигурации выполнялся успешно. Более того, исходя из записи в логе трассировки, нет уверенности, что ошибка связана именно с содержимым конфигурации.

**Comment by Erik773** [comment]
Здравствуйте @LesN1ck.
Могли бы вы, пожалуйста, предоставить все файлы логов рабочей области ЕДТ формата .bak_*.log и trace.log.
Также, скажите, пожалуйста:
1. Производились ли в конфигурации изменения связанные с изменениями режима совместимости?
2. Перед импортом, проекты в ЕДТ были импортированы из гит репозитория или из информационной базы?

**Comment by LesN1ck** [comment]
> Здравствуйте @LesN1ck. Могли бы вы, пожалуйста, предоставить все файлы логов рабочей области ЕДТ формата .bak_*.log и trace.log. Также, скажите, пожалуйста:
> 
> 1. Производились ли в конфигурации изменения связанные с изменениями режима совместимости?
> 2. Проекты в ЕДТ были импортированы из гит репозитория или из информационной базы?

Трассировку уже полностью перезаписало за ночь во время пересборки рабочей области (в рабочей области проектов 7 конфигураций, больше 10 проектов внешних отчетов и обработок, а также несколько десятков проектов расширений). Лог трассировки прилагаю.
[telemetry.zip](https://github.com/1C-Company/1c-edt-issues/files/14121837/telemetry.zip)

По вашим вопросам:
1. Нет, уже наученный горьким опытом, стараюсь не делать вообще ничего в рабочей области, пока импорт конфигурации не выполнится полностью (включая выполнение всех проверок).
2. Проекты были импортированы из информационной базы.
