### ISSUE TITLE
Подключение к репозиторию GIT не позволяет задать порт, отличный от типового

### ISSUE THREAD

**Issue by KigBan** [1C-Company/1c-edt-issues#1418]
### Описание ошибки

При настройке подключения к репозиторию ввожу путь подключения в иде:
[git@gitlab.mycompany.ru:2223]:developer/test.git
При разборе путь к репозиторию начинается с: "2223]:"
Поле порт не заполняется
Поле пользователь: "%5bgit"
При подключении ошибка: Can't connect to any repository: %5bgit@gitlab.mycompany.ru:2223]:developer/test.git .... :22] Failed (IOException) to execute: Превышен таймаут семафора.

Так же при установке в поле порт значения оно не сохраняется. При подключении не используется.

### Как воспроизвести

1. Перейдите в `...`
2. Кликните по `....`
3. Прокрутите вниз до `....`
4. Смотрите ошибку в `....`

### Скриншоты

![image](https://github.com/1C-Company/1c-edt-issues/assets/69096531/768250ab-8a75-47c2-9a8c-ce6257e38cc0)

### Ожидаемое поведение

Есть способ указать другой порт.

### Лог рабочей области

!ENTRY org.eclipse.egit.ui 4 0 2024-05-02 18:11:58.597
!MESSAGE git@gitlab.mycompany.ru:developer/test.git: DefaultConnectFuture[git@gitlab.mycompany.ru/92.63.110.178:22]: Failed (IOException) to execute: Превышен таймаут семафора.

!STACK 0
org.eclipse.jgit.api.errors.TransportException: git@gitlab.mycompany.ru:developer/test.git: DefaultConnectFuture[git@gitlab.mycompany.ru/92.63.110.178:22]: Failed (IOException) to execute: Превышен таймаут семафора.

	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:189)
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:128)
	at org.eclipse.egit.core.op.ListRemoteOperation.run(ListRemoteOperation.java:116)
	at org.eclipse.egit.ui.internal.clone.SourceBranchPage$9.run(SourceBranchPage.java:377)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.jgit.errors.TransportException: git@gitlab.mycompany.ru:developer/test.git: DefaultConnectFuture[git@gitlab.mycompany.ru/92.63.110.178:22]: Failed (IOException) to execute: Превышен таймаут семафора.

	at org.eclipse.jgit.transport.sshd.SshdSessionFactory.getSession(SshdSessionFactory.java:264)
	at org.eclipse.jgit.transport.sshd.SshdSessionFactory.getSession(SshdSessionFactory.java:1)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:281)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:153)
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:167)
	... 4 more
Caused by: org.apache.sshd.common.SshException: DefaultConnectFuture[git@gitlab.mycompany.ru/92.63.110.178:22]: Failed (IOException) to execute: Превышен таймаут семафора.

	at org.apache.sshd.common.future.AbstractSshFuture.lambda$verifyResult$1(AbstractSshFuture.java:131)
	at org.apache.sshd.common.future.AbstractSshFuture.formatExceptionMessage(AbstractSshFuture.java:185)
	at org.apache.sshd.common.future.AbstractSshFuture.verifyResult(AbstractSshFuture.java:130)
	at org.apache.sshd.client.future.DefaultConnectFuture.verify(DefaultConnectFuture.java:42)
	at org.apache.sshd.client.future.DefaultConnectFuture.verify(DefaultConnectFuture.java:34)
	at org.eclipse.jgit.transport.sshd.SshdSession.connect(SshdSession.java:195)
	at org.eclipse.jgit.transport.sshd.SshdSession.connect(SshdSession.java:144)
	at org.eclipse.jgit.transport.sshd.SshdSession.connect(SshdSession.java:99)
	at org.eclipse.jgit.transport.sshd.SshdSessionFactory.getSession(SshdSessionFactory.java:251)
	... 9 more
Caused by: java.io.IOException: Превышен таймаут семафора.

	at java.base/sun.nio.ch.Iocp.translateErrorToIOException(Iocp.java:299)
	at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:389)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Версия 1С:EDT

2023.1.4, 2023.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

### Дополнительная информация

Через Git Extension всё работает корректно.

**Comment by tretyakevich** [comment]
Пожалуйста, поясните - откуда взялся формат с [] в адресе.

**Comment by tretyakevich** [comment]
Закрывается до предоставления дополнительных данных
