### ISSUE TITLE
Не устанавливает мобильную платформу

### ISSUE THREAD

**Issue by DitriXNew** [1C-Company/1c-edt-issues#143]
### Описание ошибки

Все подключил, все настроил, но, если на устройстве нет мобильной платформы - ЕДТ не устанавливает ее а выдает ошибку

### Как воспроизвести

Удалить на телефоне мобильную платформу
Попробовтаь установить ее через ЕДТ

### Ожидаемое поведение

На телефон должна установиться платформа

### Лог рабочей области

```
com._1c.g5.v8.dt.platform.services.mobile.MobileDeviceException: Unknown failure
	at com._1c.g5.v8.dt.internal.platform.services.mobile.android.AndroidFileSystemSupport.installLocalPackage(AndroidFileSystemSupport.java:96)
	at com._1c.g5.v8.dt.internal.platform.services.mobile.android.AndroidApplicationLauncher.deployRuntime(AndroidApplicationLauncher.java:77)
	at com._1c.g5.v8.dt.internal.platform.services.mobile.android.AndroidApplicationLauncher.deployRuntime(AndroidApplicationLauncher.java:1)
	at com._1c.g5.v8.dt.internal.launching.mobile.launchconfigurations.MobileApplicationLaunchDelegate.doLaunch(MobileApplicationLaunchDelegate.java:130)
	at com._1c.g5.v8.dt.debug.core.launchconfigurations.CustomErrorHandlingLaunchDelegate.launch(CustomErrorHandlingLaunchDelegate.java:56)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

### Версия 1С:EDT

2021.2.10

### Операционная система

Windows

### Дополнительная информация

Android 10
adb через wifi
Права все дал, на установку приложение, через adb install все ставится корректно

**Comment by vkarelin** [comment]
До сих пор воспроизводится.
Пытаюсь поставить мобильную платформу через EDT на виртуальное устройство Android Emulator (который в Android Studio).
Возникает аналогичное сообщение об ошибке.
Версии EDT пробовал разные, в том числе и 2021.3.3.

**Comment by DmitryBelov-e1c** [comment]
Исправлено в версии 2023.2
