### ISSUE TITLE
На MacOS 13 не запускается отладка

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1447]
ЕДТ 2023.3.5
1С 8.3.24.1548
![bug](https://github.com/1C-Company/1c-edt-issues/assets/38705255/9ef7a3d0-678e-40fd-b275-20b0a1c81f96)

[logs.zip](https://github.com/user-attachments/files/15522580/logs.zip)

В логах видны ещё проблемы с сохранением пароля к базе - это тоже баг:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=391455

**Comment by Roffild** [comment]
Пароли при перезапуске теряются. Похоже ЕДТ теряет сам доступ к хранилищу паролей. Приходится "чистить" и вводить снова.

**Comment by Erik773** [comment]
> "Импорт" Конфы проходит нормально, а дебаг не запускается...

Приложите, пожалуйста, логи рабочей области на момент возникновения проблемы, т.е. непосредственно после попытки запуска отладки.

> Пароли при перезапуске теряются. Похоже ЕДТ теряет сам доступ к хранилищу паролей. Приходится "чистить" и вводить снова.

Это известная проблема #943, задача в процессе исследования.

**Comment by Roffild** [comment]
![bug](https://github.com/1C-Company/1c-edt-issues/assets/38705255/9ddbe5fc-7181-4c42-b0df-560a0c71ffe3)

>Приложите, пожалуйста, логи рабочей области на момент возникновения проблемы, т.е. непосредственно после попытки запуска отладки.

В конце лога:
```
!ENTRY com._1c.g5.v8.dt.platform.services.ui 4 0 2024-06-01 19:19:13.298
!MESSAGE Ошибка запуска приложения.
!STACK 0
com._1c.g5.v8.dt.platform.services.core.runtimes.environments.MatchingRuntimeNotFound: Не обнаружено подходящих зарегистрированных версий платформы, либо они не подходят по разрядности.
Возможно, необходимые версии установлены в системе, но не зарегистрированы.
Чтобы проверить список зарегистрированных версий платформы, нажмите на кнопку "Версии платформы...".
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.environments.ExecutionEnvironmentInstallationResolver.filterVersionMaskSupportedInstallations(ExecutionEnvironmentInstallationResolver.java:106)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.environments.ExecutionEnvironmentInstallationResolver.resolve(ExecutionEnvironmentInstallationResolver.java:86)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.environments.ExecutionEnvironmentProvider.get(ExecutionEnvironmentProvider.java:184)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.environments.ExecutionEnvironment.get(ExecutionEnvironment.java:139)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.environments.ExecutionEnvironmentResolvable.get(ExecutionEnvironmentResolvable.java:98)
	at com.e1c.g5.dt.applications.ui.contributors.AbstractApplicationClientDelegate.open(AbstractApplicationClientDelegate.java:117)
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationClientDelegate.open(InfobaseApplicationClientDelegate.java:63)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.lambda$25(ApplicationManager.java:415)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.lambda$21(ApplicationManager.java:415)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.open(ApplicationManager.java:404)
	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.open(Unknown Source)
	at com._1c.g5.v8.dt.internal.launching.core.launchconfigurations.RuntimeClientLaunchDelegate.lambda$0(RuntimeClientLaunchDelegate.java:231)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runWithSubMonitor(ProgressMonitors.java:361)
	at com._1c.g5.v8.dt.internal.launching.core.launchconfigurations.RuntimeClientLaunchDelegate.doLaunch(RuntimeClientLaunchDelegate.java:139)
	at com._1c.g5.v8.dt.debug.core.launchconfigurations.CustomErrorHandlingLaunchDelegate.launch(CustomErrorHandlingLaunchDelegate.java:56)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY com._1c.g5.v8.dt.ui 1 0 2024-06-01 19:22:24.891
!MESSAGE EDT закрывается```

**Comment by Erik773** [comment]
Здравствуйте @Roffild!
К сожалению, не удается локализовать проблему, не достаточно данных.
Могли бы вы, пожалуйста, приложить скриншоты панели "Приложения" с приложением и его свойствами, а также панель с характеристиками информационной базы, полный скриншот окна с версиями платформы. А если возможно, то приложите, пожалуйста, видео с воспроизведением проблемы.

**Comment by Roffild** [comment]
Я .metadata с Винды скопировал без com._1c.g5.v8.* но оставил com._1c.g5.v8.*.ui чтоб не настраивать с нуля.

"Версии платформы..." просканировал. Базу нормально импортировал. Записи о Отладках и Запусках все удалил.

По Ф5 выбрал "создать Отладку для Толстого клиента". Синхрон кода отработал. Запуск - ошибка.

Ищите в исходнике Запуска: откуда он путь берёт.

**Comment by MaksimDzyuba** [comment]
@Roffild  Здравствуйте, без предоставления полный логов еще раз, мы не сможем Вам помочь, предоставте, пожалуйста, что у Вас просил @Erik773. 
Работает ли запуск отладки для тонкого клиента, а не для толстого?

**Comment by tretyakevich** [comment]
Закрыта до предоставления дополнительных данных
