### ISSUE TITLE
1c edt ошибка проверки учетных данных пользователя при импорте конфигурации

### ISSUE THREAD

**Issue by 0xdeface** [1C-Company/1c-edt-issues#1457]
### Описание ошибки

Ошибка в том что не подходит пароль пользователя при импорте конфигурации.
```
java.lang.reflect.InvocationTargetException
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ExtensionsViewer.loadExtensions(ExtensionsViewer.java:201)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizardPage.lambda$19(ImportConfigurationWizardPage.java:645)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.RuntimeOperationSupport.execRuntimeOperation(RuntimeOperationSupport.java:110)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizardPage.lambda$18(ImportConfigurationWizardPage.java:644)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.util.concurrent.ExecutionException: com._1c.g5.v8.dt.platform.services.core.runtimes.execution.InfobaseUserAuthenticationException: Журнал процесса платформы [код ошибки 1]:
Пользователь ИБ не идентифицирован
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com._1c.g5.v8.dt.platform.services.core.ProgressMonitorAwareExecutor.syncExec(ProgressMonitorAwareExecutor.java:95)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ExtensionsViewer.loadExtensions(ExtensionsViewer.java:175)
	... 4 more
Caused by: com._1c.g5.v8.dt.platform.services.core.runtimes.execution.InfobaseUserAuthenticationException: Журнал процесса платформы [код ошибки 1]:
Пользователь ИБ не идентифицирован
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.AbstractRuntimeComponentExecutor.executeRuntimeProcessCommand(AbstractRuntimeComponentExecutor.java:371)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.AbstractRuntimeComponentExecutor.executeRuntimeProcessCommand(AbstractRuntimeComponentExecutor.java:102)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.ThickClientLauncher.listConfigurationExtensions(ThickClientLauncher.java:755)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.listConfigurationExtensions(DesignerSessionThickClientLauncher.java:1006)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ExtensionsViewer.lambda$1(ExtensionsViewer.java:181)
	at com._1c.g5.v8.dt.platform.services.core.ProgressMonitorAwareExecutor.lambda$0(ProgressMonitorAwareExecutor.java:61)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
arhlinux x11 kde plasma 6 liberica 11

### Как воспроизвести

1. Перейдите в edt
2. Кликните по импортировать конфигурацию
3. выберите базу, появится окно ввода данных. Тип авторизации infobase (доменная авторизация для пользователя отключена)

### Ожидаемое поведение

пароль должен подойди

### Лог рабочей области

[
[edt.log](https://github.com/user-attachments/files/15949633/edt.log)
](url)

### Версия 1С:EDT

2023.3.5

### Операционная система

Linux

### Версия платформы 1С:Предприятие 8

8.3.22

### Установленные плагины

Нет плагинов

**Comment by Erik773** [comment]
Здравствуйте @0xdeface!
Подскажите, пожалуйста, совпадают ли версии платформы информационной базы и проекта ЕДТ?
Попробуйте задать не пустой пароль и убрать галочку "Linux Integration" в настройках защищенного хранилища.
![photo_2024-06-24_08-26-08](https://github.com/1C-Company/1c-edt-issues/assets/93516265/d2516af5-2d1e-48c9-aec9-3ee885f6dc68)
Напишите, пожалуйста, удастся ли в результате решить проблему.

**Comment by 0xdeface** [comment]
Да. версия платформы 8.3.22.1923. Спасибо, судя по всему это помогло и расширения отобразились. Попробую продолжить импорт

**Comment by Erik773** [comment]
> Открыть новое ишью с новым логом?

да, пожалуйста, создайте другую задачу с подробным описанием проблемы и актуальными логами, а эту предлагаю закрыть, так как проблема из описания решена.

**Comment by 0xdeface** [comment]
Ну я не уверен насчет закрытия, потому что все таки это не очевидное и не нормальное поведение программы, а решение это скорее метод обхода проблемы.

**Comment by Erik773** [comment]
@0xdeface, могли бы вы, пожалуйста, при регистрации задачи про ошибку, при которой "во время импорта edt закрылась" помимо логов, также приложить файлы формата hs_err_pid*, чаще всего они лежат в  директории с клиентом 1C:EDT.

**Comment by Erik773** [comment]
Эту задачу закрываем как дубль #943

**Comment by smirnovrv** [comment]
Я решил проблему так:
Окно>Параметры>Общие>Защита>Защитное хранилище
там на вкладке Пароль, нажимаем кнопку Восстановить значение по умолчанию 

![image](https://github.com/user-attachments/assets/e9a56842-5fc7-48d8-80ff-d08ce09ed039)


*Правда предварительно я очистил все пароли, но это не помогло

**Comment by ipyguru** [comment]
Очистка secure storage и перезапуск EDT должен помочь...
![image](https://github.com/user-attachments/assets/41b7d44e-2840-43d2-8309-f71f08a0e4c8)
