### ISSUE TITLE
Во время операции экспорта произошла ошибка

### ISSUE THREAD

**Issue by iyad1020** [1C-Company/1c-edt-issues#1468]
### Описание ошибки

При экспорте проекта из репозитория git происходит ошибка экспорта: 
java.lang.Exception: org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at com._1c.g5.v8.dt.common.EnhancedMultiStatus.extractException(EnhancedMultiStatus.java:258)
	at com._1c.g5.v8.dt.common.EnhancedMultiStatus.lambda$0(EnhancedMultiStatus.java:189)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com._1c.g5.v8.dt.common.EnhancedMultiStatus.getException(EnhancedMultiStatus.java:191)
	at com._1c.g5.v8.dt.platform.services.ui.runtimes.RuntimeExecutionErrorDialog.toString(RuntimeExecutionErrorDialog.java:363)
	at com._1c.g5.v8.dt.platform.services.ui.runtimes.RuntimeExecutionErrorDialog.getMessage(RuntimeExecutionErrorDialog.java:336)
	at com._1c.g5.v8.dt.platform.services.ui.runtimes.RuntimeExecutionErrorDialog.createDetailsArea(RuntimeExecutionErrorDialog.java:296)
	at com._1c.g5.v8.dt.platform.services.ui.runtimes.RuntimeExecutionErrorDialog.toggleDetailsArea(RuntimeExecutionErrorDialog.java:413)
	at com._1c.g5.v8.dt.platform.services.ui.runtimes.RuntimeExecutionErrorDialog.initializeBounds(RuntimeExecutionErrorDialog.java:259)
	at org.eclipse.jface.window.Window.create(Window.java:435)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at com._1c.g5.v8.dt.platform.services.ui.runtimes.RuntimeExecutionErrorDialog.openError(RuntimeExecutionErrorDialog.java:148)
	at com._1c.g5.v8.dt.platform.services.ui.runtimes.RuntimeExecutionErrorDialog.openError(RuntimeExecutionErrorDialog.java:103)
	at com._1c.g5.v8.dt.internal.launching.ui.statushandlers.LaunchingErrorStatusHandler.lambda$0(LaunchingErrorStatusHandler.java:31)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4035)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3635)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.util.concurrent.ExecutionException: org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.awaitCompletion(ExportService.java:291)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.export(ExportService.java:239)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.work(ExportService.java:180)
	at com._1c.g5.v8.dt.internal.export.ExportOperation.run(ExportOperation.java:152)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.lambda$19(AbstractInfobaseConnection.java:741)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.exportToXml(AbstractInfobaseConnection.java:716)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.lambda$6(AbstractInfobaseConnection.java:292)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:266)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadConfiguration(ParticipantAwareInfobaseConnection.java:96)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadConfiguration(ReconnectableInfobaseConnection.java:175)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.lambda$0(OnDemandSynchronizationStrategy.java:114)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:92)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.updateConnectedInfobase(InfobaseSynchronization.java:633)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.lambda$2(InfobaseSynchronizationManager.java:308)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.updateInfobase(InfobaseSynchronizationManager.java:283)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.updateInfobase(Unknown Source)
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationBehaviourDelegate.publish(InfobaseApplicationBehaviourDelegate.java:107)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.lambda$9(ApplicationManager.java:345)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.publish(ApplicationManager.java:333)
	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.publish(Unknown Source)
	at com.e1c.g5.dt.internal.applications.ui.ApplicationUiSupport.askUserAndUpdate(ApplicationUiSupport.java:246)
	at com.e1c.g5.dt.internal.applications.ui.ApplicationUiSupport.lambda$0(ApplicationUiSupport.java:116)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com.e1c.g5.dt.internal.applications.ui.ApplicationUiSupport.ensureUpdated(ApplicationUiSupport.java:101)
	at com.e1c.g5.dt.applications.ui.IApplicationUiSupport$pbryglu.ensureUpdated(Unknown Source)
	at com._1c.g5.v8.dt.internal.launching.ui.statushandlers.ApplicationUpdateStatusHandler.handleStatus(ApplicationUpdateStatusHandler.java:46)
	at com._1c.g5.v8.dt.debug.core.launchconfigurations.CustomErrorHandlingLaunchDelegate.handleStatus(CustomErrorHandlingLaunchDelegate.java:209)
	at com._1c.g5.v8.dt.launching.core.launchconfigurations.AbstractRuntimeDebugAwareLaunchDelegate.updateApplication(AbstractRuntimeDebugAwareLaunchDelegate.java:247)
	at com._1c.g5.v8.dt.internal.launching.core.launchconfigurations.RuntimeClientLaunchDelegate.lambda$0(RuntimeClientLaunchDelegate.java:179)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runWithSubMonitor(ProgressMonitors.java:361)
	at com._1c.g5.v8.dt.internal.launching.core.launchconfigurations.RuntimeClientLaunchDelegate.doLaunch(RuntimeClientLaunchDelegate.java:139)
	at com._1c.g5.v8.dt.debug.core.launchconfigurations.CustomErrorHandlingLaunchDelegate.launch(CustomErrorHandlingLaunchDelegate.java:56)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at com._1c.g5.v8.dt.form.pictures.PictureFqnUtil.buildFormPictureBlobFqn(PictureFqnUtil.java:43)
	at com._1c.g5.v8.dt.internal.form.naming.FormTopObjectFqnGeneratorDelegate.generateAssociatedBlobFqn(FormTopObjectFqnGeneratorDelegate.java:95)
	at com._1c.g5.v8.dt.internal.core.naming.DelegatingTopObjectFqnGenerator.generateAssociatedBlobFqn(DelegatingTopObjectFqnGenerator.java:84)
	at com._1c.g5.v8.dt.core.picture.PictureExtension.doGetType(PictureExtension.java:128)
	at com._1c.g5.v8.dt.core.picture.PictureExtension$1.execute(PictureExtension.java:120)
	at com._1c.g5.v8.dt.core.picture.PictureExtension$1.execute(PictureExtension.java:1)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:842)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:777)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeReadOnlyTask(Reactor.java:151)
	at com._1c.g5.v8.dt.internal.core.platform.bm.BmModelManager.executeReadOnlyTask(BmModelManager.java:522)
	at com._1c.g5.v8.dt.core.picture.PictureExtension.doGetType(PictureExtension.java:109)
	at com._1c.g5.v8.dt.core.picture.PictureExtension.getType(PictureExtension.java:45)
	at com._1c.g5.v8.dt.export.xml.writer.PictureWriter.writePictureDef(PictureWriter.java:174)
	at com._1c.g5.v8.dt.export.xml.writer.PictureWriter.writePicture(PictureWriter.java:149)
	at com._1c.g5.v8.dt.export.xml.writer.PictureWriter.write(PictureWriter.java:58)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormSmartFeatureWriter.write(FormSmartFeatureWriter.java:96)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormCommandWriter.write(FormCommandWriter.java:92)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormSmartFeatureWriter.write(FormSmartFeatureWriter.java:91)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormXmlWriter.writeFormContent(FormXmlWriter.java:84)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormXmlWriter.write(FormXmlWriter.java:51)
	at com._1c.g5.v8.dt.form.export.xml.exporter.FormXmlExporter.exportFormXml(FormXmlExporter.java:115)
	at com._1c.g5.v8.dt.form.export.xml.exporter.FormXmlExporter.work(FormXmlExporter.java:85)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:377)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

	java.util.concurrent.ExecutionException: org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.awaitCompletion(ExportService.java:291)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.export(ExportService.java:239)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService.work(ExportService.java:180)
	at com._1c.g5.v8.dt.internal.export.ExportOperation.run(ExportOperation.java:152)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.lambda$19(AbstractInfobaseConnection.java:741)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.exportToXml(AbstractInfobaseConnection.java:716)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.lambda$6(AbstractInfobaseConnection.java:292)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:266)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadConfiguration(ParticipantAwareInfobaseConnection.java:96)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadConfiguration(ReconnectableInfobaseConnection.java:175)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.lambda$0(OnDemandSynchronizationStrategy.java:114)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:92)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.updateConnectedInfobase(InfobaseSynchronization.java:633)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.lambda$2(InfobaseSynchronizationManager.java:308)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.updateInfobase(InfobaseSynchronizationManager.java:283)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.updateInfobase(Unknown Source)
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationBehaviourDelegate.publish(InfobaseApplicationBehaviourDelegate.java:107)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.lambda$9(ApplicationManager.java:345)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.publish(ApplicationManager.java:333)
	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.publish(Unknown Source)
	at com.e1c.g5.dt.internal.applications.ui.ApplicationUiSupport.askUserAndUpdate(ApplicationUiSupport.java:246)
	at com.e1c.g5.dt.internal.applications.ui.ApplicationUiSupport.lambda$0(ApplicationUiSupport.java:116)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:278)
	at com.e1c.g5.dt.internal.applications.ui.ApplicationUiSupport.ensureUpdated(ApplicationUiSupport.java:101)
	at com.e1c.g5.dt.applications.ui.IApplicationUiSupport$pbryglu.ensureUpdated(Unknown Source)
	at com._1c.g5.v8.dt.internal.launching.ui.statushandlers.ApplicationUpdateStatusHandler.handleStatus(ApplicationUpdateStatusHandler.java:46)
	at com._1c.g5.v8.dt.debug.core.launchconfigurations.CustomErrorHandlingLaunchDelegate.handleStatus(CustomErrorHandlingLaunchDelegate.java:209)
	at com._1c.g5.v8.dt.launching.core.launchconfigurations.AbstractRuntimeDebugAwareLaunchDelegate.updateApplication(AbstractRuntimeDebugAwareLaunchDelegate.java:247)
	at com._1c.g5.v8.dt.internal.launching.core.launchconfigurations.RuntimeClientLaunchDelegate.lambda$0(RuntimeClientLaunchDelegate.java:179)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runWithSubMonitor(ProgressMonitors.java:361)
	at com._1c.g5.v8.dt.internal.launching.core.launchconfigurations.RuntimeClientLaunchDelegate.doLaunch(RuntimeClientLaunchDelegate.java:139)
	at com._1c.g5.v8.dt.debug.core.launchconfigurations.CustomErrorHandlingLaunchDelegate.launch(CustomErrorHandlingLaunchDelegate.java:56)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at com._1c.g5.v8.dt.form.pictures.PictureFqnUtil.buildFormPictureBlobFqn(PictureFqnUtil.java:43)
	at com._1c.g5.v8.dt.internal.form.naming.FormTopObjectFqnGeneratorDelegate.generateAssociatedBlobFqn(FormTopObjectFqnGeneratorDelegate.java:95)
	at com._1c.g5.v8.dt.internal.core.naming.DelegatingTopObjectFqnGenerator.generateAssociatedBlobFqn(DelegatingTopObjectFqnGenerator.java:84)
	at com._1c.g5.v8.dt.core.picture.PictureExtension.doGetType(PictureExtension.java:128)
	at com._1c.g5.v8.dt.core.picture.PictureExtension$1.execute(PictureExtension.java:120)
	at com._1c.g5.v8.dt.core.picture.PictureExtension$1.execute(PictureExtension.java:1)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:842)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:777)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeReadOnlyTask(Reactor.java:151)
	at com._1c.g5.v8.dt.internal.core.platform.bm.BmModelManager.executeReadOnlyTask(BmModelManager.java:522)
	at com._1c.g5.v8.dt.core.picture.PictureExtension.doGetType(PictureExtension.java:109)
	at com._1c.g5.v8.dt.core.picture.PictureExtension.getType(PictureExtension.java:45)
	at com._1c.g5.v8.dt.export.xml.writer.PictureWriter.writePictureDef(PictureWriter.java:174)
	at com._1c.g5.v8.dt.export.xml.writer.PictureWriter.writePicture(PictureWriter.java:149)
	at com._1c.g5.v8.dt.export.xml.writer.PictureWriter.write(PictureWriter.java:58)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormSmartFeatureWriter.write(FormSmartFeatureWriter.java:96)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormCommandWriter.write(FormCommandWriter.java:92)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormSmartFeatureWriter.write(FormSmartFeatureWriter.java:91)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormXmlWriter.writeFormContent(FormXmlWriter.java:84)
	at com._1c.g5.v8.dt.form.export.xml.writer.FormXmlWriter.write(FormXmlWriter.java:51)
	at com._1c.g5.v8.dt.form.export.xml.exporter.FormXmlExporter.exportFormXml(FormXmlExporter.java:115)
	at com._1c.g5.v8.dt.form.export.xml.exporter.FormXmlExporter.work(FormXmlExporter.java:85)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:377)
	at com._1c.g5.v8.dt.internal.export.xml.ExportService$ExportObjectTask.call(ExportService.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Как воспроизвести

1. Создаю проект в EDT с нашей конфигурацией самописной.
2. Подключаю групповую разработку
3. Делаю git init и публикую репозиторий в github
4. Создаю новый проект (это может быть другой разработчик) 
5. Добавляю в перспективе гит репозиторий из github. Клонирую его на локальный пк.
6. После того как репозиторий клонировал нажимаю ПКМ по репозиторию и нажимаю импортировать проекты. Нажимаю готово. Никаких настроек не меняю, все оставляю в окне по умолчанию
7. После того как все завершено возвращаю в перспективу 1С Enterprise и пытаюсь запустить базу. ЕДТ Предлагает выбрать базу.
8. Выбираю базу (Пробовал и с файловой и с клиент-серной) предлагает сделать экспорт и реструктуризацию. На этапе экспорта падает с ошибкой.

### Ожидаемое поведение

Эскпорт должен был завершиться успешно или при такой ошибке должно выйти сообщение что не так сейчас с конфигурацией

### Лог рабочей области

[Журнал ошибок.log](https://github.com/user-attachments/files/16159604/default.log)

### Версия 1С:EDT

RUBY 2023.3.5

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1548

### Установленные плагины

Нет плагинов

### Дополнительная информация

У нас собственная разработка поэтому прикладываю cf для тестирования по ссылке Яндекс: https://disk.yandex.ru/d/IMg7pzfzz9pxsg

**Comment by iyad1020** [comment]
Конфу я убрал с Я.Диска. Могу куда-то лично прислать на тест.

**Comment by MaksimDzyuba** [comment]
@iyad1020 Здравствуйте, подготовлю ftp и вышлю Вам, чтобы принять конфигурацию, спасибо!

**Comment by iyad1020** [comment]
@MaksimDzyuba Максим, добрый день! А когда вышлите ftp?

**Comment by MaksimDzyuba** [comment]
@iyad1020 ftp готов, чтобы его Вам передать не публично, напишите на edt@1c.ru с просьбой выдать ftp по данной ошибке, я Вам отвечу уже ссылко

**Comment by iyad1020** [comment]
@MaksimDzyuba Максим, загрузил в FTP конфигурацию.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, да увидели, спасибо, взяли в работу

**Comment by MaksimDzyuba** [comment]
Здравствуйте, первое, что удалось выяснить. Есть некоторая проблема в конфигурации, а именно
Форма - "Контрагенты_ФормаСпискаУправляемая" в обработке "КонтурЭДО" имеет команду "КнопкаОтправитьПриглашение", так вот в этой команде указана картинка не из конфигурации, что не возможно по идеи, она на выгрузке, как безымянная валяется.
![image](https://github.com/user-attachments/assets/efa482da-a110-4d25-a09d-c0c579ccf90e)

**Comment by iyad1020** [comment]
@MaksimDzyuba Максим, добрый день!
Спасибо за информацию.
Подскажите, это единственное замечание? или нам подождать еще какие-то дополнения?

**Comment by MaksimDzyuba** [comment]
@iyad1020 Здравствуйте, да, получилось, что только это мешало, мы в 2024.1 сделали уже так, чтобы оно больше не мешало, просто сразу бы показывалась ошибка, что там недопустимая картинка, так детально, чтобы Вы сами могли ее найти, как задача зайдет в ветку, я закрою эту ошибку.

**Comment by iyad1020** [comment]
@MaksimDzyuba Понял. Спасибо!
Я тогда сейчас попробую убрать эту ошибку и заново загрузить. А эта картинка только одна у нас такая? Вы случаем не нашли других таких? Или нам самим поискать?

**Comment by MaksimDzyuba** [comment]
А еще забыл отметить, может, конечно. это специально, но у Вас в конфигурации есть ряд общих картинок, у которых нет реальной картинки, я запомнил ОбщаяКартинка1, но есть и еще, это мы тоже будем показывать, но тоже в 2024.1, это будет как варнинг в логах

**Comment by iyad1020** [comment]
@MaksimDzyuba Максим, добрый день!
Я попробовал и снова ошибка упала.
Влияет только наличие таких картинок в конфигурации или то, что такие картинки могут быть в формах указаны?

**Comment by MaksimDzyuba** [comment]
@iyad1020 Здравствуйте, извиняюсь за долгий ответ, был в отпуске, а что не получилось то, какую ошибку он выдает?

**Comment by iyad1020** [comment]
@MaksimDzyuba Максим, прошу прощения за длительный ответ. Немного отложили запуск EDT. А сейчас вернулись уже на новой версии, которая недавно вышла 2024. Там, как Вы и обещали, теперь написало об этой ошибке с картинкой. Я ее поправил и конфигурация загрузилась.
Спасибо большое за помощь!

**Comment by MaksimDzyuba** [comment]
Здравствуйте, отлично, если что, то заводите новые баги, эту закрою
