### ISSUE TITLE
Добавление WS-Ссылки

### ISSUE THREAD

**Issue by spawnax** [1C-Company/1c-edt-issues#1478]
### Описание ошибки

При добавлении WS-ссылки https://223-demo.rts-tender.ru/customer/api/RtsWebService.svc?wsdl
Конфигурация выдаёт ошибку:
![2024-07-29_15-02-00](https://github.com/user-attachments/assets/4476c9d3-1863-48da-9066-41fb11f20466)
В логах:
java.lang.NullPointerException
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.createOperations(WSDefinitionsSerializer.java:314)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readEndpoint(WSDefinitionsSerializer.java:277)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readService(WSDefinitionsSerializer.java:241)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readDefinitions(WSDefinitionsSerializer.java:196)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readRoot(WSDefinitionsSerializer.java:126)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.deserialize(WSDefinitionsSerializer.java:114)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionResource.doLoad(WSDefinitionResource.java:59)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionResourceSet.getLinkProviderResource(TransactionResourceSet.java:196)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionResourceSet.getNonBmResource(TransactionResourceSet.java:289)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionResourceSet.resolveLinkedResources(TransactionResourceSet.java:135)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionService.getExternalObjectByUri(TransactionService.java:744)
	at com._1c.g5.v8.bm.core.internal.transaction.BmPlatformTransaction.getExternalObjectByUri(BmPlatformTransaction.java:137)
	at com._1c.g5.v8.dt.ws.resource.WsDefinitionObjectReferencePersistenceContributor.doResolveTarget(WsDefinitionObjectReferencePersistenceContributor.java:120)
	at com._1c.g5.v8.dt.ws.resource.WsDefinitionObjectReferencePersistenceContributor.resolveTarget(WsDefinitionObjectReferencePersistenceContributor.java:67)
	at com._1c.g5.v8.bm.core.internal.reference.ReferenceValueResolver.doGetTargetObject(ReferenceValueResolver.java:226)
	at com._1c.g5.v8.bm.core.internal.reference.ReferenceValueResolver.resolve(ReferenceValueResolver.java:100)
	at com._1c.g5.v8.bm.core.internal.transaction.GlobalObjectDelegate.resolveTarget(GlobalObjectDelegate.java:815)
	at com._1c.g5.v8.bm.core.internal.transaction.GlobalObjectDelegate$GlobalReferenceValueGetResult.lambda$0(GlobalObjectDelegate.java:962)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionUtil.executeInReadOnlyTransaction(TransactionUtil.java:44)
	at com._1c.g5.v8.bm.core.internal.transaction.GlobalObjectDelegate$GlobalReferenceValueGetResult.getObject(GlobalObjectDelegate.java:961)
	at com._1c.g5.v8.bm.core.internal.ReferenceValueGetResult.getObject(ReferenceValueGetResult.java:45)
	at com._1c.g5.v8.bm.core.BmObject.eGet(BmObject.java:480)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1050)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1042)
	at com._1c.g5.v8.dt.aef2.bm.models.BmValue.getObjectValue(BmValue.java:238)
	at com._1c.g5.v8.dt.aef2.bm.models.BmValue.<init>(BmValue.java:84)
	at com._1c.g5.v8.dt.aef2.bm.models.BmValue.<init>(BmValue.java:64)
	at com._1c.g5.v8.dt.md.ui.aef.models.MdSingleModelFactory.createModel(MdSingleModelFactory.java:581)
	at com._1c.g5.v8.dt.md.ui.aef.models.MdSingleModelFactory.createSingleModel(MdSingleModelFactory.java:245)
	at com._1c.g5.aef2.standard.definitions.models.AbstractFeatureFieldModelFactory.createModel(AbstractFeatureFieldModelFactory.java:64)
	at com._1c.g5.aef2.standard.definitions.models.IModelFactory.createModel(IModelFactory.java:45)
	at com._1c.g5.aef2.standard.definitions.models.CompositeModelFactory.createModel(CompositeModelFactory.java:58)
	at com._1c.g5.aef2.standard.definitions.AbstractDefinition.createComponent(AbstractDefinition.java:264)
	at com._1c.g5.aef2.standard.definitions.components.DefinitionDrivenComponent.createComponents(DefinitionDrivenComponent.java:154)
	at com._1c.g5.aef2.components.Component.getComponents(Component.java:121)
	at com._1c.g5.aef2.scenes.Scene.fillEventClassToComponentMap(Scene.java:358)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at com._1c.g5.aef2.scenes.Scene.fillEventClassToComponentMap(Scene.java:358)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at com._1c.g5.aef2.scenes.Scene.fillEventClassToComponentMap(Scene.java:358)
	at com._1c.g5.aef2.scenes.Scene.refresh(Scene.java:125)
	at com._1c.g5.aef2.scenes.Scene.setComponent(Scene.java:88)
	at com._1c.g5.aef2.engines.Engine.createScene(Engine.java:86)
	at com._1c.g5.v8.dt.md.ui.editor.aef.AbstractDtGranularEditorAefPage.createPageControls(AbstractDtGranularEditorAefPage.java:400)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.createFormContentInternal(DtGranularEditorPage.java:553)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.lambda$2(DtGranularEditorPage.java:394)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4779)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.lambda$1(DtGranularEditorPage.java:393)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.createFormContent(DtGranularEditorPage.java:390)
	at org.eclipse.ui.forms.editor.FormPage.lambda$0(FormPage.java:166)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.forms.editor.FormPage.createPartControl(FormPage.java:166)
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:480)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.pageChange(DtGranularEditor.java:1038)
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1030)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:612)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:518)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.showEditorInput(DtGranularEditor.java:783)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.createPages(DtGranularEditor.java:980)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.lambda$5(DtGranularEditor.java:635)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4035)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3635)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

eclipse.buildId=2023.3.6.33
java.version=11.0.20
java.vendor=BellSoft
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\Users\a.horoshev\AppData\Local\1C\1cedtstart\projects\Цифровые закупки

This is a continuation of log file C:\Users\a.horoshev\AppData\Local\1C\1cedtstart\projects\Цифровые закупки\.metadata\.bak_0.log
Created Time: 2024-07-29 08:46:55.020

При попытке запустить конфигурацию:
java.lang.Exception: Файл объекта не существует - /WSReferences/ЭТП_РТС.xml
	at com._1c.g5.v8.dt.common.EnhancedMultiStatus.extractException(EnhancedMultiStatus.java:258)
	at com._1c.g5.v8.dt.common.EnhancedMultiStatus.lambda$0(EnhancedMultiStatus.java:189)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com._1c.g5.v8.dt.common.EnhancedMultiStatus.getException(EnhancedMultiStatus.java:191)
	at com._1c.g5.v8.dt.platform.services.ui.runtimes.RuntimeExecutionErrorDialog.openError(RuntimeExecutionErrorDialog.java:103)
	at com._1c.g5.v8.dt.internal.launching.ui.statushandlers.LaunchingErrorStatusHandler.lambda$0(LaunchingErrorStatusHandler.java:31)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4035)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3635)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

### Как воспроизвести

1. Перейдите в `...`
2. Кликните по `....`
3. Прокрутите вниз до `....`
4. Смотрите ошибку в `....`

### Ожидаемое поведение

В конфигураторе без проблем добавляется и отображается

### Лог рабочей области

[journal.log](https://github.com/user-attachments/files/16412620/journal.log)

### Версия 1С:EDT

Ruby 2023.3.6

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1586

### Установленные плагины

1C:Code style V8, 1C:Language Tool

**Comment by spawnax** [comment]
В EDT 2024.1.1 чуть больше информации выходит:

eclipse.buildId=2024.1.1.29
java.version=17.0.12
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\Users\a.horoshev\AppData\Local\1C\1cedtstart\projects\Цифровые закупки

com._1c.g5.aef2.Aef2Plugin
Ошибка
Sun Oct 13 13:05:02 MSK 2024
Exception while executing runnable in queue 'PROPERTY_PALETTE_ENGINE': Cannot invoke "com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer$PortType.getOperations()" because "portType" is null

java.lang.NullPointerException: Cannot invoke "com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer$PortType.getOperations()" because "portType" is null
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.createOperations(WSDefinitionsSerializer.java:314)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readEndpoint(WSDefinitionsSerializer.java:277)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readService(WSDefinitionsSerializer.java:241)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readDefinitions(WSDefinitionsSerializer.java:196)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readRoot(WSDefinitionsSerializer.java:126)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.deserialize(WSDefinitionsSerializer.java:114)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionResource.doLoad(WSDefinitionResource.java:59)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionResourceSet.getLinkProviderResource(TransactionResourceSet.java:196)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionResourceSet.getNonBmResource(TransactionResourceSet.java:289)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionResourceSet.resolveLinkedResources(TransactionResourceSet.java:135)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionService.getExternalObjectByUri(TransactionService.java:744)
	at com._1c.g5.v8.bm.core.internal.transaction.BmPlatformTransaction.getExternalObjectByUri(BmPlatformTransaction.java:138)
	at com._1c.g5.v8.dt.ws.resource.WsDefinitionObjectReferencePersistenceContributor.doResolveTarget(WsDefinitionObjectReferencePersistenceContributor.java:120)
	at com._1c.g5.v8.dt.ws.resource.WsDefinitionObjectReferencePersistenceContributor.resolveTarget(WsDefinitionObjectReferencePersistenceContributor.java:67)
	at com._1c.g5.v8.bm.core.internal.reference.ReferenceValueResolver.doGetTargetObject(ReferenceValueResolver.java:226)
	at com._1c.g5.v8.bm.core.internal.reference.ReferenceValueResolver.resolve(ReferenceValueResolver.java:100)
	at com._1c.g5.v8.bm.core.internal.transaction.GlobalObjectDelegate.resolveTarget(GlobalObjectDelegate.java:815)
	at com._1c.g5.v8.bm.core.internal.transaction.GlobalObjectDelegate$GlobalReferenceValueGetResult.lambda$0(GlobalObjectDelegate.java:962)
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionUtil.executeInReadOnlyTransaction(TransactionUtil.java:44)
	at com._1c.g5.v8.bm.core.internal.transaction.GlobalObjectDelegate$GlobalReferenceValueGetResult.getObject(GlobalObjectDelegate.java:961)
	at com._1c.g5.v8.bm.core.internal.ReferenceValueGetResult.getObject(ReferenceValueGetResult.java:45)
	at com._1c.g5.v8.bm.core.BmObject.eGet(BmObject.java:480)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1050)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1042)
	at com._1c.g5.v8.dt.aef2.bm.models.BmValue.getObjectValue(BmValue.java:238)
	at com._1c.g5.v8.dt.aef2.bm.models.BmValue.<init>(BmValue.java:84)
	at com._1c.g5.v8.dt.aef2.bm.models.BmValue.<init>(BmValue.java:64)
	at com._1c.g5.v8.dt.md.ui.aef.models.MdSingleModelFactory.createModel(MdSingleModelFactory.java:592)
	at com._1c.g5.v8.dt.md.ui.aef.models.MdSingleModelFactory.createSingleModel(MdSingleModelFactory.java:255)
	at com._1c.g5.aef2.standard.definitions.models.AbstractFeatureFieldModelFactory.createModel(AbstractFeatureFieldModelFactory.java:54)
	at com._1c.g5.aef2.standard.definitions.models.IModelFactory.createModel(IModelFactory.java:45)
	at com._1c.g5.aef2.standard.definitions.models.CompositeModelFactory.createModel(CompositeModelFactory.java:57)
	at com._1c.g5.aef2.standard.definitions.AbstractDefinition.createComponent(AbstractDefinition.java:264)
	at com._1c.g5.aef2.standard.definitions.components.DefinitionDrivenComponent.createComponents(DefinitionDrivenComponent.java:154)
	at com._1c.g5.aef2.components.Component.getComponents(Component.java:121)
	at com._1c.g5.aef2.standard.components.ContainerComponent.createViewModels(ContainerComponent.java:270)
	at com._1c.g5.aef2.components.Component.getViewModels(Component.java:132)
	at com._1c.g5.aef2.standard.components.ContainerComponent.createViewModels(ContainerComponent.java:272)
	at com._1c.g5.v8.dt.md.ui.properties.components.MdPropertyPaletteComponent$1.createViewModels(MdPropertyPaletteComponent.java:97)
	at com._1c.g5.aef2.components.Component.getViewModels(Component.java:132)
	at com._1c.g5.aef2.standard.components.ContainerComponent.lambda$0(ContainerComponent.java:224)
	at com._1c.g5.aef2.internal.RunnableQueue$QueueRunnable.run(RunnableQueue.java:284)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by MaksimDzyuba** [comment]
Здравствуйте, с этой ошибкой очень странно выходит - если загрузить эту схему в конфигураторе и выгрузить все в xml, а потом загрузить этот xml обратно, то он не загрузится, завел ошибку уже не только на EDT, но и на сама платформу, как они исправят, то и в EDT будет починено
