### ISSUE TITLE
Импорт ИЗ базы

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1524]
Ruby 2023.3.6

Редактор форм, макетов, ролей и т.д. лучше в Конфигураторе. (Особенно из-за бага #1395 )

Я изменил форму в Конфигураторе, а ЕДТ заставляет создать новый проект с потерей настроек (Гит, форматирование и т.д.) !!!

![bug](https://github.com/user-attachments/assets/ec1904da-1508-474f-b259-837cc97cf78d)

**Comment by Roffild** [comment]
Вот эпический конец этого Импорта:
```
java.lang.Exception: Ресурс /Trade11dev уже существует.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:309)
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:296)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:56)
	at org.eclipse.core.internal.resources.Project.create(Project.java:267)
	at org.eclipse.core.internal.resources.Project.create(Project.java:253)
	at com._1c.g5.v8.dt.internal.core.platform.V8ProjectCreator.lambda$0(V8ProjectCreator.java:90)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2315)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2340)
	at com._1c.g5.v8.dt.internal.core.platform.V8ProjectCreator.create(V8ProjectCreator.java:74)
	at com._1c.g5.v8.dt.internal.core.platform.ConfigurationProjectManager.lambda$0(ConfigurationProjectManager.java:675)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2315)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2340)
	at com._1c.g5.v8.dt.internal.core.platform.ConfigurationProjectManager.createProject(ConfigurationProjectManager.java:673)
	at com._1c.g5.v8.dt.internal.core.platform.ConfigurationProjectManager.create(ConfigurationProjectManager.java:191)
	at com._1c.g5.v8.dt.internal.core.platform.ConfigurationProjectManager.create(ConfigurationProjectManager.java:182)
	at com._1c.g5.v8.dt.core.platform.IConfigurationProjectManager$pbryglu.create(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$11(ImportConfigurationWizard.java:651)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.RuntimeOperationSupport.execRuntimeOperation(RuntimeOperationSupport.java:110)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.importInfobaseAsNewProject(ImportConfigurationWizard.java:641)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$2(ImportConfigurationWizard.java:210)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runAsTask(ProgressMonitors.java:191)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$1(ImportConfigurationWizard.java:200)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by Roffild** [comment]
1С:Предприятие 8.3 (8.3.24.1691)
Управление торговлей, редакция 11 (11.5.17.130)
Ruby 2024.1.0

В 2024.1.0 Импорт заработал, но объединение странное.

Ничего (99%) из этого списка не менялось с "нулевого" импорта Расширения.

![bug](https://github.com/user-attachments/assets/e2e4bb52-022a-4931-8c5e-e4f57455b3ec)

**Comment by Roffild** [comment]
Изменений в Гит от Конфигуратора нет.

Можно работать без проблем, если знать, что всего этого списка не существует в Расширении.

**Comment by Erik773** [comment]
> 2024.1.0 Импорт заработал, но объединение странное.

Здравствуйте @Roffild.
Могли бы Вы, пожалуйста, предоставить проект расширения конфигурации для воспроизведения проблемы. 
Файлы можно отправить письмом на edt@1c.ru или если большой объем, то можно написать письмо v8@1c.ru и попросить предоставить ftp, тут инструкция https://partners.v8.1c.ru/topics/81, после отправки нужно прислать номер обращения, к которому были прикреплены данные.

**Comment by Roffild** [comment]
1С:Предприятие 8.3 (8.3.25.1419)
Управление торговлей, редакция 11 (11.5.17.140)
Ruby 2024.1.0

[ConfigFiles.zip](https://github.com/user-attachments/files/17179423/ConfigFiles.zip)

1. Загрузить Расширение в Конфигураторе.
2. Импортировать в ЕДТ.
3. Повторить.

![bug](https://github.com/user-attachments/assets/57859fad-11f8-4039-8fce-9b61c1da6137)
