### ISSUE TITLE
СтатьиРасходов.ФормаЭлемента не отображается

### ISSUE THREAD

**Issue by Roffild** [1C-Company/1c-edt-issues#1542]
1С:Предприятие 8.3 (8.3.25.1419)
Управление торговлей, редакция 11 (11.5.17.140)
Ruby 2024.1.0

Ошибка только в ПланВидовХарактеристик.СтатьиРасходов.Форма.ФормаЭлемента из УТ.

![bug](https://github.com/user-attachments/assets/d2852f02-2efb-4f30-8e24-f6f19bbc699d)

```
LayoutProblem: 
Cannot invoke "org.eclipse.emf.ecore.EObject.eIsProxy()" because "referenceValueObject" is null

java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.ecore.EObject.eIsProxy()" because "referenceValueObject" is null
	at com._1c.g5.v8.dt.dcs.typedvalue.TypedValueFactory.getValueText(TypedValueFactory.java:603)
	at com._1c.g5.v8.dt.dcs.typedvalue.TypedValueFactory.getValueText(TypedValueFactory.java:459)
	at com._1c.g5.v8.dt.form.internal.layout.data.LogFormAdditionalInfoProvider.getFieldChoiceListPresentation(LogFormAdditionalInfoProvider.java:239)
	at com._1c.g5.v8.dt.form.layout.generation.RadioGroupGenerator.prepare(RadioGroupGenerator.java:116)
	at com._1c.g5.v8.dt.form.layout.generation.RadioGroupGenerator.prepare(RadioGroupGenerator.java:1)
	at com._1c.g5.v8.dt.form.layout.generation.base.GroupBaseGenerator.prepare(GroupBaseGenerator.java:44)
	at com._1c.g5.v8.dt.form.layout.generation.LogicGroupGenerator.prepare(LogicGroupGenerator.java:810)
	at com._1c.g5.v8.dt.form.layout.generation.LogicGroupGenerator.prepare(LogicGroupGenerator.java:1)
	at com._1c.g5.v8.dt.form.layout.generation.base.GroupBaseGenerator.prepare(GroupBaseGenerator.java:44)
	at com._1c.g5.v8.dt.form.layout.generation.PageGenerator.prepare(PageGenerator.java:158)
	at com._1c.g5.v8.dt.form.layout.generation.PageGenerator.prepare(PageGenerator.java:1)
	at com._1c.g5.v8.dt.form.layout.generation.base.GroupBaseGenerator.prepare(GroupBaseGenerator.java:44)
	at com._1c.g5.v8.dt.form.layout.generation.PagesGenerator.prepare(PagesGenerator.java:99)
	at com._1c.g5.v8.dt.form.layout.generation.PagesGenerator.prepare(PagesGenerator.java:1)
	at com._1c.g5.v8.dt.form.layout.generation.base.GroupBaseGenerator.prepare(GroupBaseGenerator.java:44)
	at com._1c.g5.v8.dt.form.layout.generation.MainElementGenerator.prepare(MainElementGenerator.java:75)
	at com._1c.g5.v8.dt.form.layout.generation.HippoGenerator.generate(HippoGenerator.java:128)
	at com._1c.g5.v8.dt.form.layout.service.HippoLayoutService.layout(HippoLayoutService.java:154)
	at com._1c.g5.v8.dt.form.layout.service.HippoLayoutService.createHippoSession(HippoLayoutService.java:124)
	at com._1c.g5.v8.dt.form.internal.presentation.wysiwyg.FormWysiwygRepresentation$1.execute(FormWysiwygRepresentation.java:328)
	at com._1c.g5.v8.dt.form.internal.presentation.wysiwyg.FormWysiwygRepresentation$1.execute(FormWysiwygRepresentation.java:1)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.LegacyTaskWrapper.execute(LegacyTaskWrapper.java:48)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:842)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeAndRollback(Reactor.java:266)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.BmModel.executeAndRollback(BmModel.java:210)
	at com._1c.g5.v8.dt.form.internal.presentation.wysiwyg.FormWysiwygRepresentation.rebuildInternal(FormWysiwygRepresentation.java:323)
	at com._1c.g5.v8.dt.form.internal.presentation.wysiwyg.FormWysiwygRepresentation$2.lambda$0(FormWysiwygRepresentation.java:379)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4046)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

**Comment by vadimeg** [comment]
@Roffild Добрый день, у меня эта форма открывается без ошибок. Попробуйте сделать очистку проекта и еще раз открыть форму. Если ошибка повторится, то пришлите, пожалуйста, исходный код формы (Form.form)

**Comment by Roffild** [comment]
[ChartsOfCharacteristicTypes.zip](https://github.com/user-attachments/files/17305261/ChartsOfCharacteristicTypes.zip)

**Comment by vadimeg** [comment]
Ошибку подтверждаю, будем исправлять.
Если нужно срочно, то можно попробовать подправить код формы. Исправленную форму прилагаю.
[ChartsOfCharacteristicTypes.zip](https://github.com/user-attachments/files/17324387/ChartsOfCharacteristicTypes.zip)

**Comment by vadimeg** [comment]
Исправлено в 2024.1.2
