### ISSUE TITLE
При использование типа ДокументОбъект или ДокументСсылка не контролируется наличие реквизитов

### ISSUE THREAD

**Issue by alxint** [1C-Company/1c-edt-issues#1555]
### Описание ошибки

При описание параметра функции как ДокументОбъект или ДокументСсылка в автодополнение подставляются реквизиты из всех документов, ошибка при обращение к реквизиту уникальному для документа не возникает.

![image](https://github.com/user-attachments/assets/51c2f40f-c26d-4106-9be3-b3bff3bd8ed3)

При этом при передаче в функцию документа у которого нет реквизита к которому  есть обращение в коде функции возникнет ошибка выполнения

### Как воспроизвести

1. Создать новый общий модуль
2. Создать функцию с параметром ДокументОбъект
3. Использовать любой из реквизитов 

### Ожидаемое поведение

Выдавать в подсказке только реквизиты общие для всех документов, разрешать обращение к реквизитам конкретного типа документа только после уточнения типа через ТипЗнач(ДокументОбъект) = Тип(). Выдавать ошибку при попытке обращения к реквизиту без уточнения типа.

### Лог рабочей области

!ENTRY org.eclipse.ui 4 0 2024-10-11 15:28:33.146
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: Argument not valid
    at org.eclipse.swt.SWT.error(SWT.java:4899)
    at org.eclipse.swt.SWT.error(SWT.java:4833)
    at org.eclipse.swt.SWT.error(SWT.java:4804)
    at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
    at org.eclipse.swt.widgets.Widget.checkParent(Widget.java:418)
    at org.eclipse.swt.widgets.Widget.<init>(Widget.java:293)
    at org.eclipse.swt.widgets.Control.<init>(Control.java:166)
    at org.eclipse.swt.widgets.Slider.<init>(Slider.java:117)
    at org.eclipse.jface.internal.text.html.BrowserInformationControl.isAvailable(BrowserInformationControl.java:93)
    at org.eclipse.xtext.ui.editor.hover.html.DefaultEObjectHoverProvider$HoverControlCreator.doCreateInformationControl(DefaultEObjectHoverProvider.java:438)
    at org.eclipse.jface.text.AbstractReusableInformationControlCreator.createInformationControl(AbstractReusableInformationControlCreator.java:46)
    at org.eclipse.jface.text.AbstractInformationControlManager.getInformationControl(AbstractInformationControlManager.java:829)
    at org.eclipse.jface.text.AbstractInformationControlManager.internalShowInformationControl(AbstractInformationControlManager.java:1138)
    at org.eclipse.jface.text.AbstractInformationControlManager.presentInformation(AbstractInformationControlManager.java:1120)
    at org.eclipse.jface.text.AbstractInformationControlManager.setInformation(AbstractInformationControlManager.java:431)
    at org.eclipse.jface.text.contentassist.AdditionalInfoController.computeInformation(AdditionalInfoController.java:567)
    at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1101)
    at org.eclipse.jface.text.AbstractInformationControlManager.showInformation(AbstractInformationControlManager.java:1091)
    at org.eclipse.jface.text.contentassist.AdditionalInfoController.showInformation(AdditionalInfoController.java:541)
    at org.eclipse.jface.text.contentassist.AdditionalInfoController$1.showInformation(AdditionalInfoController.java:478)
    at org.eclipse.jface.text.contentassist.AdditionalInfoController$Timer.lambda$1(AdditionalInfoController.java:362)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5039)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4519)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:569)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

### Версия 1С:EDT

Ruby 2024.1.1

### Операционная система

Linux

### Версия платформы 1С:Предприятие 8

8.3.24.1691

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool

**Comment by Erik773** [comment]
Здравствуйте @alxint.
Описанное в задаче поведение является на данный момент ожидаемым.
Но мы обязательно учтём Ваши пожелания. 
Задача переводится в раздел пожелания.
