### ISSUE TITLE
Зависает EDT при переходе к закладке Схема

### ISSUE THREAD

**Issue by hamec** [1C-Company/1c-edt-issues#1556]
### Описание ошибки

При переходе к закладке "Схема" - схема модуля EDT намертво зависает. При чем зависает не с 1-ого раза, а со 2-ого или 3-его. Т.Е. один раз открываешь, нормально, второй раз открыл зависло.
При этом сама EDT в момент зависания больше ничего не делает

### Как воспроизвести

1. Откройте большой модуль
2. Попытайтесь открыть Схему

### Скриншоты

![image](https://github.com/user-attachments/assets/6021df0a-c86e-4717-b2bd-f6ded8b8540e)
![image](https://github.com/user-attachments/assets/8ffd6942-7d42-4b13-9157-5c03d2a290e4)

### Ожидаемое поведение

Не зависать

### Лог рабочей области

[.log](https://github.com/user-attachments/files/17350426/default.log)
[trace.log](https://github.com/user-attachments/files/17350427/trace.log)

### Версия 1С:EDT

Ruby 2024.1.1

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1698, 8.3.15.1958

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Схема не открывается вне зависимости от размера модуля

**Comment by hamec** [comment]
Dump Java 
[threaddump.txt](https://github.com/user-attachments/files/17350484/threaddump.txt)

**Comment by Erik773** [comment]
> Судя по содержанию дамп снят не во время зависания, и лог не соответствует дампу потоков.

Похоже, что дамп снят для процесса 1cedt.exe, нужен для javaw.exe

**Comment by hamec** [comment]
Дамп снимал для вот этого процесса, javaw такого не видел, как его можно найти?
![image](https://github.com/user-attachments/assets/5830f3fa-4ff7-4001-be0c-8216903d2a89)
Воспроизведение от конфигурации не зависит. Ловил на ERP 2.4 и Рознице 2.2 в модуле АРМ Кассира
Попробую воспроизвести и снять новые данные

**Comment by Erik773** [comment]
> Дамп снимал для вот этого процесса, javaw такого не видел, как его можно найти?

Судя по скриншоту это как раз javaw.exe, значит, видимо, дамп снят не во время "зависания" или с другого процесса.

> Попробую воспроизвести и снять новые данные

Хорошо, спасибо, ждем актуальные дампы.

**Comment by hamec** [comment]
Словил. На заднем фоне зависшая EDT, в диспетчере задач PID процесса, и консоль снятия дампа. Логи так же прикладываю. Дамп снимался после зависания
[trace.log](https://github.com/user-attachments/files/17383566/trace.log)

![image](https://github.com/user-attachments/assets/37109aeb-39e9-445d-866e-41ca730bf23e)
[threaddump.txt](https://github.com/user-attachments/files/17383563/threaddump.txt)
[log.log](https://github.com/user-attachments/files/17383572/log.log)

**Comment by Erik773** [comment]
@hamec, подскажите, пожалуйста, у Вас монитор 4К и производились ли какие-то  дополнительные настройки зума монитора?

**Comment by hamec** [comment]
Монитор 2к, разрешение увеличен масштаб до 125%

**Comment by Erik773** [comment]
Есть известная проблема, когда при использовании зума eclipse может "зависать". Могли бы Вы, пожалуйста, попробовать убрать зум и посмотреть воспроизводится ли ошибка?

**Comment by hamec** [comment]
Я попробую, но на 2023.3.6 такого не было совсем. И я сижу на рабочей тачке через терминал, а зум у меня на стационарном мониторе, это может влиять?

**Comment by Erik773** [comment]
> И я сижу на рабочей тачке через терминал, а зум у меня на стационарном мониторе, это может влиять?

В таком варианте работы ошибка с eclipse не возникает.

**Comment by hamec** [comment]
Тогда не знаю, надо еще что-то предоставить?

**Comment by Erik773** [comment]
Понадобится время для изучения ошибки, если будет нужна дополнительная информация, сообщим.
Благодарим за помощь в исследовании проблемы.

**Comment by MaksimDzyuba** [comment]
Здравствуйте, пока не удается выяснить причин, есть подозрение, что приложение зависает из-за не хватки памяти, сколько выделено оперативной памяти на EDT?

**Comment by hamec** [comment]
Исходного на машине 32 Гб под EDT выделяю 16 Гб

**Comment by MaksimDzyuba** [comment]
Понял, можно столько не выделять 16 очень много, оно не нужно, 8-10 вполне должно хватать. Давайте, пожалуйста, изменим, и еще попробуем, если она еще раз зависнет, то можете, пожалуйста, снять и дамп памяти - https://its.1c.ru/db/edtdoc/content/153/hdoc

**Comment by hamec** [comment]
Словил очередное зависание, у меня дам памяти на 4 Гб получился, куда его выложить?

**Comment by tretyakevich** [comment]
> Словил очередное зависание, у меня дам памяти на 4 Гб получился, выложил на я.диск. ![image](https://private-user-images.githubusercontent.com/25643488/384106377-6961aefa-64c0-4049-a19c-4f900cd03d35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTM1MTUsIm5iZiI6MTczMTA1MzIxNSwicGF0aCI6Ii8yNTY0MzQ4OC8zODQxMDYzNzctNjk2MWFlZmEtNjRjMC00MDQ5LWExOWMtNGY5MDBjZDAzZDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA4MDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2Y2EzZjBjMmM2YmQ0OTkxMzY1Njc4ZTg2NmIxNDhjY2ZlYzJkOTA3ZmI4YjkzOTJhYWRjMTlkOTk5YzgzNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CcJcIfneRWKJP0a7IrwVK2Efm88nf5W0U-Xytfwxn-c) [log.log](https://github.com/user-attachments/files/17668216/log.log) [trace.log](https://github.com/user-attachments/files/17668215/trace.log) https://disk.yandex.ru/d/5ylae7X5K3ANQQ [threaddump.txt](https://github.com/user-attachments/files/17668298/threaddump.txt)
> 
> Из изменений в среде:
> 
> * обновился на последний релиз 2024.1.2;
> * сменил Java, была Zulu стала от Axiom

А как в этот раз зависание себя проявляло?
Экран становился "серым/белым" (как в первом скриншоте)? Мышка меняла курсор на песочные часы?

По предоставленным данным:
1. Дамп памяти в порядке. 1Гб с жесткими ссылками, остальные 3Гб по мягким ссылкам или уже мусор.  При 10Гб хипа. 
Собственно низкое потребление CPU как раз показывает, что проблем с памятью нет (иначе бы GC все скушал в попытках выкроить хоть немного свободного места в памят).
2. Дамп потоков зависания не показывает:
"main" #1 prio=6 os_prio=0 cpu=142671.88ms elapsed=250.01s tid=0x000002193ed17dc0 nid=0x5684 runnable  [0x00000030408fe000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3657)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
Т.е. просто ждет обработки событий от ОС.

3. Из всей хоть сколько-нибудь заметной активности - индексация JGit:
"Worker-9: Computing Git status for repository NPO_ERP" #143 prio=5 os_prio=0 cpu=16250.00ms elapsed=235.40s tid=0x00000219cfe84d30 nid=0x70f8 runnable  [0x000000304acfe000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileOutputStream.writeBytes(java.base@17.0.13/Native Method)
	at java.io.FileOutputStream.write(java.base@17.0.13/FileOutputStream.java:349)
	at java.io.BufferedOutputStream.flushBuffer(java.base@17.0.13/BufferedOutputStream.java:81)
	at java.io.BufferedOutputStream.flush(java.base@17.0.13/BufferedOutputStream.java:142)
	- locked <0x00000004fe79cd58> (a java.io.BufferedOutputStream)
	at org.eclipse.jgit.util.FS$StreamGobbler.copy(FS.java:2622)
	at org.eclipse.jgit.util.FS.runProcess(FS.java:2237)
	at org.eclipse.jgit.util.FS.execute(FS.java:2361)
	at org.eclipse.jgit.treewalk.WorkingTreeIterator.filterClean(WorkingTreeIterator.java:503)
	at org.eclipse.jgit.treewalk.WorkingTreeIterator.possiblyFilteredInputStream(WorkingTreeIterator.java:441)

4. Лог тоже в порядке, никаких проблемных записей.

**Comment by hamec** [comment]
Может быть продемонстрирую процесс зависания по Anydesk?
по п.2 на скрине из последнего коммента заголовок как раз и стал белым

**Comment by yaroslavgrinash** [comment]
Добрый день, коллеги. Похоже на https://github.com/1C-Company/1c-edt-issues/issues/1243 Так и не было решено

**Comment by hamec** [comment]
Коллеги, на новой версии (2024.1.3) проблема продолжает воспроизводиться. Причем теперь воспроизводится и в режиме отладки на закладке точек останова (на других не смотрел и не могу сказать, было ли такое поведение на предыдущих версиях), надо ли предоставить какую дополнительную информацию?
Опять же не знаю, была ли в прошлых логах такая запись, но появилось вот такое
`!ENTRY com._1c.g5.v8.dt.debug.core 1 0 2024-12-02 00:44:03.059
!MESSAGE Сессия отладки завершилась: RuntimeSessionThreadGroup[name=Сеанс 2, sessionId=2, sessionUuid=8bb60396-8af7-4aae-a156-fec989a5ddbd]
!STACK 0
java.lang.RuntimeException: Снимок стека
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeDebugClientTarget.lambda$10(RuntimeDebugClientTarget.java:2445)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeSessionThreadGroup.removeThread(RuntimeSessionThreadGroup.java:203)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeDebugClientTarget.removeThread(RuntimeDebugClientTarget.java:1919)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeDebugClientTarget.handleDebugTargetTerminate(RuntimeDebugClientTarget.java:1065)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeEventDispatchJob.processDebugTargetTerminateEvent(RuntimeEventDispatchJob.java:366)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeEventDispatchJob.processEvent(RuntimeEventDispatchJob.java:229)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeEventDispatchJob.run(RuntimeEventDispatchJob.java:155)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY com._1c.g5.v8.dt.debug.core 1 0 2024-12-02 00:45:11.236
!MESSAGE Сессия отладки завершилась: RuntimeSessionThreadGroup[name=Сеанс 3, sessionId=3, sessionUuid=b0894111-695d-435e-9dd4-1eb668850fa4]
!STACK 0
java.lang.RuntimeException: Снимок стека
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeDebugClientTarget.lambda$10(RuntimeDebugClientTarget.java:2445)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeSessionThreadGroup.removeThread(RuntimeSessionThreadGroup.java:203)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeDebugClientTarget.removeThread(RuntimeDebugClientTarget.java:1919)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeDebugClientTarget.handleDebugTargetTerminate(RuntimeDebugClientTarget.java:1065)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeEventDispatchJob.processDebugTargetTerminateEvent(RuntimeEventDispatchJob.java:366)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeEventDispatchJob.processEvent(RuntimeEventDispatchJob.java:229)
	at com._1c.g5.v8.dt.internal.debug.core.model.RuntimeEventDispatchJob.run(RuntimeEventDispatchJob.java:155)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by hamec** [comment]
Боюсь сглазить, но вроде на 2024.2.1 пропало, наблюдаю дальше

**Comment by MaksimDzyuba** [comment]
Удивительно, если честно, вообще ничего не делали(

**Comment by MaksimDzyuba** [comment]
А можно еще раз логи, может там теперь видно, что за исключение летело, что оно так себя вело

**Comment by hamec** [comment]
Вот сейчас покликал по схеме, вроде все нормально.
Логи прикладываю

[trace.log](https://github.com/user-attachments/files/18547868/trace.log)

[ — копия (2).log](https://github.com/user-attachments/files/18547869/2.log)

**Comment by MaksimDzyuba** [comment]
проблема так больше и не проявилась, можно закрывать ошибку?
