### ISSUE TITLE
Ошибка Импорта(обновления) проекта Расширения из конфигурации 1С

### ISSUE THREAD

**Issue by 1C-AB** [1C-Company/1c-edt-issues#1579]
### Описание ошибки

Ошибка сравнения узла <MAIN: 'Subsystem.АБ_WZ_Wazzup'; OTHER: 'Subsystem.АБ_WZ_Wazzup'>

Расширение для УНФ, ранее импортировано вместе с УНФ в два проекта (расширение связанное с основной конфигурацией)

В конфигураторе 1С связанном с проектом, был ряд доработок(что характерно не связано с подсистемой).
После попытки импортировать вылазить ошибка сравнения.
Куда копать не понимаю.

Полный текст ошибки

```
eclipse.buildId=2024.1.2.50
java.version=17.0.12
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data E:\EDT\UNF

com._1c.g5.v8.dt.compare
Ошибка
Sun Nov 10 13:34:07 MSK 2024
Ошибка сравнения узла <MAIN: 'Subsystem.АБ_WZ_Wazzup'; OTHER: 'Subsystem.АБ_WZ_Wazzup'>

java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
	at com._1c.g5.v8.dt.internal.md.extension.MdPropertyTypeProvider.hasPropertyType(MdPropertyTypeProvider.java:91)
	at com._1c.g5.v8.dt.md.extension.IMdPropertyTypeProvider$pbryglu.hasPropertyType(Unknown Source)
	at com._1c.g5.v8.dt.internal.md.compare.MdCompareUtils.isExcludedFromComparison(MdCompareUtils.java:697)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.isExcludedFromComparison(MdObjectComparisonParticipant.java:1100)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.computeClassFeatures(AbstractEmfBasedComparisonParticipant.java:3272)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.lambda$0(AbstractEmfBasedComparisonParticipant.java:344)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.getClassFeatures(AbstractEmfBasedComparisonParticipant.java:343)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.getClassFeatures(MdObjectComparisonParticipant.java:1484)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.getClassFeatures(MdObjectComparisonParticipant.java:1)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.getClassFeatures(AbstractEmfBasedComparisonParticipant.java:322)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.getClassFeatures(MdObjectComparisonParticipant.java:1477)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.indexChildren(MdObjectComparisonParticipant.java:2232)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.obtainResourceForTopNode(MdObjectComparisonParticipant.java:2218)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.getMdObjectResource(MdObjectComparisonParticipant.java:2195)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.compareMdNode(MdObjectComparisonParticipant.java:2253)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.compare(MdObjectComparisonParticipant.java:402)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.lambda$0(ComparisonManager.java:409)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager$13.execute(ComparisonManager.java:3252)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.executeTask(ComparisonManager.java:3424)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.runComparisonTreeBmModelTask(ComparisonManager.java:1031)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.runCompareNodeTask(ComparisonManager.java:3242)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.compare(ComparisonManager.java:398)
	at com._1c.g5.v8.dt.internal.compare.queue.ComparisonQueueProcessor.compare(ComparisonQueueProcessor.java:85)
	at com._1c.g5.v8.dt.internal.compare.queue.ComparisonExecutor.run(ComparisonExecutor.java:116)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Как воспроизвести

1. Правая кнопка на проекта, Импорт
2. Выбор ИБ , после считывания данных, нажать ОБНОВИТЬ
3. Ошибка
Если нужны конфигурации, могу выслать тому кто будет разбираться.

### Скриншоты

![image](https://github.com/user-attachments/assets/81a9725d-e7c0-4d98-a9f5-2ffee81bdc8e)

### Ожидаемое поведение

корректное сравнение объединение

### Лог рабочей области

[trace.log](https://github.com/user-attachments/files/17691115/trace.log)

[log.txt](https://github.com/user-attachments/files/17691120/log.txt)

### Версия 1С:EDT

2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1738

### Дополнительная информация

УНФ 3.0.9.191

**Comment by Erik773** [comment]
Здравствуйте @1C-AB.
Могли бы Вы, пожалуйста, предоставить конфигурации для воспроизведения проблемы.
Файлы можно отправить письмом на edt@1c.ru указав номер задачи в гитхабе или, если объем файлов большой, то можно написать письмо v8@1c.ru и попросить предоставить ftp, тут инструкция https://partners.v8.1c.ru/topics/81, после отправки данных прислать номер зарегистрированного обращения.

**Comment by 1C-AB** [comment]
отправил на edt@1c.ru
с почтового ящика glaal@1ab.ru

**Comment by vadimeg** [comment]
@1C-AB Добрый день, вы прислали платформенную выгрузку расширения. Это выгрузка из конфигуратора или из EDT? А в рабочей области EDT были открыты и базовая конфигурация УНФ и ее расширение или только расширение?

**Comment by 1C-AB** [comment]
1. В архиве файлы это экспорт в файлы Расширения из EDT
![image](https://github.com/user-attachments/assets/4371719e-e82b-4412-8867-b44e9966fa01)

2. CFU это выгрузка конфигурации Расширения из Конфигуратора 1С
3. Что значит открыты базовая конфигурация УНФ и расширение?
В письме был скриншот, дублирую. Вот так выглядит.
![image](https://github.com/user-attachments/assets/9797144f-598f-4e24-9657-efc9d8cb4847)

**Comment by vadimeg** [comment]
Ошибку подтверждаю

**Comment by MaksimDzyuba** [comment]
@1C-AB Здравствуйте, обращение на v8.1c.ru я закрыл, файлы получили, спасибо большое, статус по задаче просьба отслеживать тут

**Comment by vadimeg** [comment]
Исправлено в 2024.1.3
