### ISSUE TITLE
Оптимизация формата хранения выполняется не полностью без вывода сообщений об ошибке

### ISSUE THREAD

**Issue by alxint** [1C-Company/1c-edt-issues#1596]
### Описание ошибки

При запуске оптимизации формата хранения исходники обрабатываются не полностью

![image](https://github.com/user-attachments/assets/1f4a6f73-08b3-421d-b745-f556731701ef)

Справа конфигурация вендора, загруженная и оптимизированная, слева конфигурация с изменениями (конфигурация вендора выгруженная из нее же), загруженная в другую ветку и тоже оптимизированная

Очистка проекта делалась, проект пересоздавался, повторно пытался оптимизировать

### Как воспроизвести

Загрузить конфигурацию вендора, оптимизировать, загрузить измененную, оптимизировать, сравнить, получить различия во всех формах

### Ожидаемое поведение

Оптимизация действует одинаково или выводит сообщение об ошибках

### Лог рабочей области

java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:470)
	at com._1c.g5.v8.dt.internal.migration.ui.CleanUpProjectSourcesHandler.execute(CleanUpProjectSourcesHandler.java:51)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:298)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:232)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:366)
	at com._1c.g5.v8.dt.internal.ui.editor.ProjectVersionSection.executeCleanUp(ProjectVersionSection.java:172)
	at org.eclipse.ui.forms.events.IHyperlinkListener$3.linkActivated(IHyperlinkListener.java:107)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:215)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:309)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.lambda$3(AbstractHyperlink.java:117)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5854)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5064)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4516)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.NullPointerException: Cannot invoke "com._1c.g5.v8.dt.mcore.TypeDescription.getTypes()" because "tdp" is null
	at com._1c.g5.v8.dt.form.service.FormUtil.ofTypeCategory(FormUtil.java:516)
	at com._1c.g5.v8.dt.form.service.FormUtil.isValueTable(FormUtil.java:543)
	at com._1c.g5.v8.dt.internal.form.cleanup.FormItemsCleanUpTaskProvider$TableSetRowFilterCleanUpTask.execute(FormItemsCleanUpTaskProvider.java:325)
	at com._1c.g5.v8.dt.internal.form.cleanup.FormItemsCleanUpTaskProvider$TableSetRowFilterCleanUpTask.execute(FormItemsCleanUpTaskProvider.java:1)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.LegacyTaskWrapper.execute(LegacyTaskWrapper.java:48)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:842)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:777)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeInBatchSession(Reactor.java:719)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.BmModel.executeInBatchSession(BmModel.java:285)
	at com._1c.g5.v8.dt.internal.migration.cleanup.CleanUpProjectSourcesManager.executeBmObjectCleanUp(CleanUpProjectSourcesManager.java:128)
	at com._1c.g5.v8.dt.internal.migration.cleanup.CleanUpProjectSourcesManager.cleanUp(CleanUpProjectSourcesManager.java:77)
	at com._1c.g5.v8.dt.internal.migration.ui.CleanUpProjectSourcesHandler.lambda$0(CleanUpProjectSourcesHandler.java:47)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Root exception:
java.lang.NullPointerException: Cannot invoke "com._1c.g5.v8.dt.mcore.TypeDescription.getTypes()" because "tdp" is null
	at com._1c.g5.v8.dt.form.service.FormUtil.ofTypeCategory(FormUtil.java:516)
	at com._1c.g5.v8.dt.form.service.FormUtil.isValueTable(FormUtil.java:543)
	at com._1c.g5.v8.dt.internal.form.cleanup.FormItemsCleanUpTaskProvider$TableSetRowFilterCleanUpTask.execute(FormItemsCleanUpTaskProvider.java:325)
	at com._1c.g5.v8.dt.internal.form.cleanup.FormItemsCleanUpTaskProvider$TableSetRowFilterCleanUpTask.execute(FormItemsCleanUpTaskProvider.java:1)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.LegacyTaskWrapper.execute(LegacyTaskWrapper.java:48)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:842)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeTask(Reactor.java:777)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.reactor.Reactor.executeInBatchSession(Reactor.java:719)
	at com._1c.g5.v8.dt.internal.core.platform.bm.integration.BmModel.executeInBatchSession(BmModel.java:285)
	at com._1c.g5.v8.dt.internal.migration.cleanup.CleanUpProjectSourcesManager.executeBmObjectCleanUp(CleanUpProjectSourcesManager.java:128)
	at com._1c.g5.v8.dt.internal.migration.cleanup.CleanUpProjectSourcesManager.cleanUp(CleanUpProjectSourcesManager.java:77)
	at com._1c.g5.v8.dt.internal.migration.ui.CleanUpProjectSourcesHandler.lambda$0(CleanUpProjectSourcesHandler.java:47)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

### Версия 1С:EDT

Ruby 2024.1.2

### Операционная система

Linux

### Версия платформы 1С:Предприятие 8

8.3.24.1761

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

Судя по всему ошибка возникает при обработке некорректных форм, каких именно пока не понятно. Исходники могу предоставить в приват.

**Comment by alxint** [comment]
В ЕДТ 2023.3.6 оптимизация проходит нормально

**Comment by tretyakevich** [comment]
Добрый день. Для воспроизведения необходима информация о используемой конфигурации (если типовая).

**Comment by alxint** [comment]
Добрый день, типовая Управление торговлей 11.4.14.181 + типовая ДатаМобайл онлайн 2.19. Отдельно УТ оптимизируется успешно. Если из объединенной удалить все формы конфигурации ДатаМобайл тоже успешно проходит оптимизация.

Воспроизводится на пустых базах, с нуля. Загрузили УТ из cf, импортировали в ЕДТ, объединили конфигурацию с ДатаМобайл, импортировали в ЕДТ, оптимизировали оба проекта в ЕДТ, сравнили, получили различия почти во всех формах

**Comment by alxint** [comment]
P.S. То, что в успешно оптимизированной конфигурации некоторые наименования элементов не переименовываются это ожидаемое поведение? 

![image](https://github.com/user-attachments/assets/7acffd1e-c9d8-4665-b5f2-1c57935db29e)

**Comment by alxint** [comment]
После исправления в формах ошибок form-legacy-check-command-handler и form-legacy-check-event-handler и form-data-path оптимизация форм проходит, но не проходит до конца оптимизация макетов

![image](https://github.com/user-attachments/assets/91205fcb-4fa4-4e15-a882-3be47508ad3d)

**Comment by tretyakevich** [comment]
Мы исправили поведение механизма очистки в 2024.2, теперь отдельные ошибки очистки не будут останавливать процесс дальнейшей очистки.

Оригинальная проблема вызвана невалидными производными данными (расчет типов), что, в свою очередь, указывает на проблему в EDT и/или проблему валидности данных комбинации указанных конфигураций.
К сожалению, воспроизвести проблему в данный момент невозможно по причине того, что ДатаМобайл онлайн 2.19 является коммерческим продуктом, и получить ее в виде исходной конфигурации 1С:Предприятие мы не можем.

**Comment by alxint** [comment]
> проблему в EDT и/или проблему валидности данных комбинации указанных конфигураций

Приветствую, а в логе ошибок будет указание на конкретный объект на котором возникает ошибка?

**Comment by tretyakevich** [comment]
> Приветствую, а в логе ошибок будет указание на конкретный объект на котором возникает ошибка?

Да, в большинстве сценариев (которые имеют конкретную локацию по объекту) информация о проблемном объекте будет  отображаться в журнале.

**Comment by tretyakevich** [comment]
Частично исправлено в 2024.2 (изоляция сценариев очистки по объектам друг от друга и расширенное логирование возникших проблем, с координатами проблемных объектов)
