### ISSUE TITLE
В версии EDT Ruby 2024.1.2 сравнение расширений, разработанных для разных конфигураций, завершается ошибкой

### ISSUE THREAD

**Issue by Dmitriy83** [1C-Company/1c-edt-issues#1597]
### Описание ошибки

В версии EDT Ruby 2024.1.2 сравнение расширений, разработанных для разных конфигураций, завершается ошибкой, если в расширении есть объект, которого нет в конфигурациии, с которой выполняется сравнение.
При этом сравнение различных конфигураций работает корректно. В предыдущей версии EDT также корректно работало и сравнение расширений, разработанных для различных конфигураций.

### Как воспроизвести

1. Создать расширение 1 для конфигурации 1.
2. Создать расширение 2 для конфигурации 2.
3. В расширении 1 заимствовать какой-то объект метаданных, которого нет в конфигурации 2.
4. Выполнить команду Compare/merge - сравнить расширение 1 с расширением 2.
5. Сравнение завершится с ошибкой (см. лог).

### Ожидаемое поведение

При сравнении расширений, разработанных для различных конфигураций не должно появляться ошибки.

### Лог рабочей области

!ENTRY com._1c.g5.v8.dt.compare 1 0 2024-11-24 19:51:02.046
!MESSAGE Comparison process started

!ENTRY com._1c.g5.v8.dt.compare 1 0 2024-11-24 19:51:02.047
!MESSAGE Starting Main data source...

!ENTRY com._1c.g5.v8.dt.compare 1 0 2024-11-24 19:51:02.047
!MESSAGE Starting Other data source...

!ENTRY com._1c.g5.v8.dt.compare 1 0 2024-11-24 19:51:02.047
!MESSAGE All data sources are running

!ENTRY com._1c.g5.v8.dt.compare 1 0 2024-11-24 19:51:02.058
!MESSAGE Comparison finished

!ENTRY org.eclipse.core.jobs 4 2 2024-11-24 19:51:02.059
!MESSAGE An internal error occurred during: "c3_edt.TestExtension and TMWE.TestExtension projects comparison".
!STACK 0
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
	at com._1c.g5.v8.dt.internal.md.extension.MdPropertyTypeProvider.hasPropertyType(MdPropertyTypeProvider.java:91)
	at com._1c.g5.v8.dt.md.extension.IMdPropertyTypeProvider$pbryglu.hasPropertyType(Unknown Source)
	at com._1c.g5.v8.dt.internal.md.compare.MdCompareUtils.isExcludedFromComparison(MdCompareUtils.java:697)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.isExcludedFromComparison(MdObjectComparisonParticipant.java:1100)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.computeClassFeatures(AbstractEmfBasedComparisonParticipant.java:3272)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.lambda$0(AbstractEmfBasedComparisonParticipant.java:344)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.getClassFeatures(AbstractEmfBasedComparisonParticipant.java:343)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.getClassFeatures(MdObjectComparisonParticipant.java:1484)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.createChildMdNodes(MdObjectComparisonParticipant.java:2760)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.createTopMdChildren(MdObjectComparisonParticipant.java:2715)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.createTopNodes(MdObjectComparisonParticipant.java:2451)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.compareRootNode(MdObjectComparisonParticipant.java:2264)
	at com._1c.g5.v8.dt.internal.md.compare.participant.MdObjectComparisonParticipant.compare(MdObjectComparisonParticipant.java:397)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager$5.execute(ComparisonManager.java:2033)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager$5.execute(ComparisonManager.java:1)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.executeTask(ComparisonManager.java:3424)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.performTopObjectMatching(ComparisonManager.java:2014)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.performComparisonProcess(ComparisonManager.java:515)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager$ComparisonProcessJob.runBatchComparing(ComparisonManager.java:3898)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager$ComparisonProcessJob.run(ComparisonManager.java:3864)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### Версия 1С:EDT

Ruby 2024.1.2

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24

**Comment by vadimeg** [comment]
Дубликат https://github.com/1C-Company/1c-edt-issues/issues/1579
