### ISSUE TITLE
Ошибка обновление ИБ

### ISSUE THREAD

**Issue by kastortroy2006** [1C-Company/1c-edt-issues#1598]
### Описание ошибки

При обновлении ИБ, выбираю базу, ввожу логин и пароль получаю окно.
(логин и пароль верный, потому что тут же из EDT могу открыть конфигуратор это базы из списки ИБ)
![2024-11-24 21_17_28-Window](https://github.com/user-attachments/assets/642c22de-0325-47ef-aa65-d672cd6fc7b6)

С другими проектами такого поведения нет.
Проект создал импортом из gitlab. Первый раз на платформе 8.3.24.1691. Версия EDT - 2024.1.1

### Как воспроизвести

1. Перейдите в панель информационных баз
2. Кликните по нужной ИБ правой кнопкой мыши.  Обновить ИБ

### Ожидаемое поведение

ИБ начнет обновляться.

### Лог рабочей области

com._1c.g5.v8.dt.platform.services.core.runtimes.execution.InfobaseUserAuthenticationException: Error interacting with the 1C:Enterprise Platform 8.3.24.1691:
Infobase authentication error. Try to configure infobase access.
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.connectWithRetry(DesignerSessionPool.java:634)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.createConnection(DesignerSessionPool.java:477)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool$1.compute(DesignerSessionPool.java:313)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool$1.compute(DesignerSessionPool.java:1)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.computeExclusively(DesignerSessionPool.java:869)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.acquire(DesignerSessionPool.java:289)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.lambda$9(DesignerSessionThickClientLauncher.java:311)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeInSubTask(ProgressMonitors.java:412)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.openDesignerSession(DesignerSessionThickClientLauncher.java:308)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.DesignerSessionInfobaseConnection.openSession(DesignerSessionInfobaseConnection.java:299)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.DesignerSessionInfobaseConnection.connect(DesignerSessionInfobaseConnection.java:99)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.connect(ParticipantAwareInfobaseConnection.java:74)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.connect(ReconnectableInfobaseConnection.java:108)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.connectAndRestoreState(InfobaseSynchronization.java:211)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.connectAndRestoreState(InfobaseSynchronizationManager.java:1115)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.lambda$2(InfobaseSynchronizationManager.java:325)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeWithSubMonitor(ProgressMonitors.java:277)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.updateInfobase(InfobaseSynchronizationManager.java:307)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.updateInfobase(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployConfiguration(DeployConfigurationWizard.java:937)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.createAndDeployNewApplication(DeployConfigurationWizard.java:759)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.lambda$3(DeployConfigurationWizard.java:1177)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeInSubTask(ProgressMonitors.java:412)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.lambda$1(DeployConfigurationWizard.java:1175)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runWithSubMonitor(ProgressMonitors.java:360)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.finishFragmentsAndDeploy(DeployConfigurationWizard.java:1150)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.lambda$0(DeployConfigurationWizard.java:1111)
	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runAsTask(ProgressMonitors.java:190)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.run(DeployConfigurationWizard.java:1105)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: com._1c.g5.designer.ssh.client.AuthenticationException: Authentication failure while establishing SSH session with Desginer agent.
	at com._1c.g5.designer.ssh.client.DesignerClient.connect(DesignerClient.java:109)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.createClientAndConnect(DesignerSessionPool.java:726)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.connectWithRetry(DesignerSessionPool.java:615)
	... 29 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at com._1c.g5.designer.ssh.client.DesignerClient.connect(DesignerClient.java:86)
	... 31 more

### Версия 1С:EDT

Ruby 2024.1.1

### Операционная система

Windows

### Версия платформы 1С:Предприятие 8

8.3.24.1691

**Comment by Erik773** [comment]
Здравствуйте @kastortroy2006.
Могли бы Вы, пожалуйста, проверить сценарий, используя минимальную требуемую версию платформы 1С:Предприятия 8.3.24.1731. Подробнее о минимальных требованиях можно ознакомиться на странице https://edt.1c.ru/docs/intro/requirements.php

**Comment by andersonru** [comment]
Аналогичная ошибка
EDT Ruby 2024.1.3
1С:Предприятия 8.3.24.1761
ОС Linux Mint 22 Cinnamon

ИБ без пользователей обновляется
ИБ с пользователями с авторизацией по логину/паролю не обновляется. Пароль сбрасывал на пустой - аналогично

![изображение](https://github.com/user-attachments/assets/99f794ba-ecd2-45d4-aba8-974b2d9fe527)

PS: Еще орфоргафическая ошибка в тексте ошибки. Authentication failure while establishing SSH session with  **Desginer** agent.


> com._1c.g5.v8.dt.platform.services.core.runtimes.execution.InfobaseUserAuthenticationException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.24.1761:
> Ошибка аутентификации информационной базы. Попробуйте настроить доступ к информационной базе.
> 	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.connectWithRetry(DesignerSessionPool.java:634)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.createConnection(DesignerSessionPool.java:477)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool$1.compute(DesignerSessionPool.java:313)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool$1.compute(DesignerSessionPool.java:1)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.computeExclusively(DesignerSessionPool.java:869)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.acquire(DesignerSessionPool.java:289)
> 	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.lambda$9(DesignerSessionThickClientLauncher.java:311)
> 	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeInSubTask(ProgressMonitors.java:412)
> 	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.openDesignerSession(DesignerSessionThickClientLauncher.java:308)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.DesignerSessionInfobaseConnection.openSession(DesignerSessionInfobaseConnection.java:299)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.DesignerSessionInfobaseConnection.connect(DesignerSessionInfobaseConnection.java:99)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.connect(ParticipantAwareInfobaseConnection.java:74)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.ensureConnected(ReconnectableInfobaseConnection.java:222)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.lambda$6(InfobaseSynchronizationManager.java:455)
> 	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runWithSubMonitor(ProgressMonitors.java:360)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.connectInfobase(InfobaseSynchronizationManager.java:438)
> 	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.connectInfobase(Unknown Source)
> 	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationBehaviourDelegate.prepare(InfobaseApplicationBehaviourDelegate.java:265)
> 	at com.e1c.g5.dt.internal.applications.ApplicationManager.lambda$13(ApplicationManager.java:526)
> 	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
> 	at com.e1c.g5.dt.internal.applications.ApplicationManager.lambda$12(ApplicationManager.java:524)
> 	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runWithSubMonitor(ProgressMonitors.java:360)
> 	at com.e1c.g5.dt.internal.applications.ApplicationManager.prepare(ApplicationManager.java:520)
> 	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.prepare(Unknown Source)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployConfiguration(DeployConfigurationWizard.java:986)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.lambda$6(DeployConfigurationWizard.java:729)
> 	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeInStep(ProgressMonitors.java:515)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployExistingApplications(DeployConfigurationWizard.java:728)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.lambda$2(DeployConfigurationWizard.java:1171)
> 	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.computeInSubTask(ProgressMonitors.java:412)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.lambda$1(DeployConfigurationWizard.java:1169)
> 	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runWithSubMonitor(ProgressMonitors.java:360)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.finishFragmentsAndDeploy(DeployConfigurationWizard.java:1150)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.lambda$0(DeployConfigurationWizard.java:1111)
> 	at com._1c.g5.v8.dt.common.runtime.ProgressMonitors.runAsTask(ProgressMonitors.java:190)
> 	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard$DeployWithProgressOperation.run(DeployConfigurationWizard.java:1105)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
> Caused by: com._1c.g5.designer.ssh.client.AuthenticationException: Authentication failure while establishing SSH session with Desginer agent.
> 	at com._1c.g5.designer.ssh.client.DesignerClient.connect(DesignerClient.java:109)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.createClientAndConnect(DesignerSessionPool.java:726)
> 	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.connectWithRetry(DesignerSessionPool.java:615)
> 	... 36 more
> Caused by: com.jcraft.jsch.JSchException: Auth fail
> 	at com.jcraft.jsch.Session.connect(Session.java:519)
> 	at com._1c.g5.designer.ssh.client.DesignerClient.connect(DesignerClient.java:86)
> 	... 38 more

**Comment by Erik773** [comment]
Попробуйте, пожалуйста, очистить хранилище защищенное хранилище. Очистить данные в Параметры → Общие → Защита → Защищенное хранилище → Оглавление → Default Secure Storage → com._1c.g5… → infobaseBinding
Если не поможет и проблема останется, то могли бы Вы, пожалуйста, предоставить базу для воспроизведения ошибки. Файлы можно отправить письмом на edt@1c.ru указав номер задачи в гитхабе или, если объем файлов большой, то можно написать письмо v8@1c.ru и попросить предоставить ftp, тут инструкция https://partners.v8.1c.ru/topics/81, после отправки данных прислать номер зарегистрированного обращения.

**Comment by andersonru** [comment]
> Попробуйте, пожалуйста, очистить хранилище защищенное хранилище. Очистить данные в Параметры → Общие → Защита → Защищенное хранилище → Оглавление → Default Secure Storage → com._1c.g5… → infobaseBinding 

Этот способ помог. Спасибо
