### ISSUE TITLE
EDT зависла после ошибки сравнения-объединения

### ISSUE THREAD

**Issue by Desar14** [1C-Company/1c-edt-issues#206]
### Описание ошибки

После попытки слить ветку с удаленной веткой гит едт красиво зависла намертво

### Как воспроизвести

сложно понять, на другом ПК всё спокойно слилось

### Ожидаемое поведение

Не происходит ошибки слития, не зависает едт

### Лог рабочей области

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/7722649/trace.log)
[log.log](https://github.com/1C-Company/1c-edt-issues/files/7722654/log.log)

### Версия 1С:EDT

2021.2.10

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

### Дополнительная информация

[threaddump.txt](https://github.com/1C-Company/1c-edt-issues/files/7722626/threaddump.txt)
https://1drv.ms/u/s!AlcrfVxA74ml4i4FS2THV3RPN09e?e=AFxMPz - ссылка на мемори дамп

**Comment by tretyakevich** [comment]
[threaddump - targets.txt](https://github.com/1C-Company/1c-edt-issues/files/7748944/threaddump.-.targets.txt)
Потоки, которые имеют отношение к зависанию

**Comment by tretyakevich** [comment]
`!ENTRY com._1c.g5.v8.dt.compare 4 0 2021-12-15 23:41:34.162
!MESSAGE Failed to perform phase STORAGE_INITIALIZATION for context ProjectContext: .virtual.2
!STACK 0
com._1c.g5.v8.dt.lifecycle.LifecycleException: Failed to perform phase STORAGE_INITIALIZATION for context ProjectContext: .virtual.2
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.performPhase(ServicesOrchestrator.java:278)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startContext(ServicesOrchestrator.java:206)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startServices(ServicesOrchestrator.java:77)
	at com._1c.g5.v8.dt.lifecycle.IServicesOrchestrator$pbryglu.startServices(Unknown Source)
	at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startContext(WorkspaceOrchestrator.java:720)
	at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startProject(WorkspaceOrchestrator.java:203)
	at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startProject(WorkspaceOrchestrator.java:154)
	at com._1c.g5.v8.dt.core.platform.IWorkspaceOrchestrator$pbryglu.startProject(Unknown Source)
	at com._1c.g5.v8.dt.internal.compare.datasource.OverlayComparisonDataSource.onStart(OverlayComparisonDataSource.java:399)
	at com._1c.g5.v8.dt.internal.compare.datasource.DtProjectDataSource.startIfNecessary(DtProjectDataSource.java:387)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.startDataSource(ComparisonManager.java:3036)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.initSourcesIfNecessary(ComparisonManager.java:3020)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.initComparisonSession(ComparisonManager.java:2923)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.performComparisonProcess(ComparisonManager.java:459)
	at com._1c.g5.v8.dt.internal.compare.ComparisonProcessJob.runBatchComparing(ComparisonProcessJob.java:88)
	at com._1c.g5.v8.dt.internal.compare.ComparisonProcessJob.run(ComparisonProcessJob.java:62)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.RuntimeException: com._1c.g5.v8.bm.core.internal.WaitTransactionFinishTimeoutException: Not all transactions finished
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:223)
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:1)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.performPhase(ServicesOrchestrator.java:267)
	... 16 more
Caused by: com._1c.g5.v8.bm.core.internal.WaitTransactionFinishTimeoutException: Not all transactions finished
	at com._1c.g5.v8.bm.core.internal.transaction.TransactionServiceLifecycleHelper.suspend(TransactionServiceLifecycleHelper.java:233)
	at com._1c.g5.v8.bm.core.internal.transaction.LightweightReadOnlyTransactionService.suspend(LightweightReadOnlyTransactionService.java:244)
	at com._1c.g5.v8.bm.core.internal.SequenceExecutionHelper.executeForward(SequenceExecutionHelper.java:51)
	at com._1c.g5.v8.bm.core.internal.transaction.DelegatingTransactionService.suspend(DelegatingTransactionService.java:232)
	at com._1c.g5.v8.bm.core.internal.engine.BmEngine.createOverlayEngine(BmEngine.java:464)
	at com._1c.g5.v8.dt.internal.core.platform.bm.BmModelManager.initOverlayStorage(BmModelManager.java:760)
	at com._1c.g5.v8.dt.internal.core.platform.bm.BmModelManager.initStorage(BmModelManager.java:597)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:213)
	... 18 more
`

Ошибка при инициализации источника сравнения, связанная с ранее выложенным дампом - при запуске сравнения были активные операции в основной БМ. Скорее всего это заблокированные транзакции проверок модуля, вызываемые из редактора BSL (см. треддамп).

**Comment by tretyakevich** [comment]
Возможная картина развития событий
1. Произведено редактирование модуля/обновлен ресурс модуля (какой-то внешней операцией)
2. Начата валидация из редактора (запущен org.eclipse.xtext.ui.editor.validation.ValidationJob)
3. Идет расчет длительных проверок (достаточно длительных для того, чтобы успел выполниться пункт 4)
4. Параллельно стартует процесс сравнения, которому для начала процесса необходимо временно заблокировать движок БМ участвующей в сравнении конфигурации. Создание новых транзакций БМ временно заблокировано
5. Проверки, выполняемые в legacy-режиме (без стабильных транзакций БМ) при работе из редактора BSL, блокируются, поскольку создание новых транзакций временно приостановлено. 
6. Кто-то или что-то пытается закрыть данный редактор BSL, при этом закрытие блокируется потому, что идет валидация (read-only операция на том же документе, по правилам Xtext - блокируется). Поскольку закрытие идет синхронно в UI потоке - идет "подвисание" UI.

Пока не ясно, какая именно транзакция не была завершена и вследствие чего. Нужно проверить саму ValidationJob, а также проверить, не может ли транзакция остаться открытой в случае cancel-а CheckExecutor.validateLanguage. Альтернативно - транзакция была "потеряна" в уже завершившемся процессе (что затрядняет ее поиск)

**Comment by tretyakevich** [comment]
Множественные переработки в данной области. Закрываем, в случае, если повторится - переоткрыть.
