### ISSUE TITLE
Не удается импортировать изменения общего модуля из серверной базы 2021.3.2/8.3.21

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#417]
### Описание ошибки

Не удается импортировать изменения общего модуля из серверной базы 8.3.21 в проект EDT 2021.3.2 с той же версией платформы. При этом база обновляется из EDT без проблем.

### Как воспроизвести

.

### Ожидаемое поведение

.

### Лог рабочей области

com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeExecutionException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.21.1197:
Операция конфигурирования завершена неуспешно

Ошибка при выполнении файловой операции 

	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:145)

	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.execInDesignerSession(DesignerSessionThickClientLauncher.java:933)

	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.exportObjectsToXml(DesignerSessionThickClientLauncher.java:302)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.InfobaseConnectionConflictResolveAssist.dumpInfobaseObjects(InfobaseConnectionConflictResolveAssist.java:96)

	at com._1c.g5.v8.dt.platform.services.ui.infobases.sync.CompareEditorMergingConflictResolveAssist.dumpInfobaseObjects(CompareEditorMergingConflictResolveAssist.java:125)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ConflictResolveOption$SyncrhonizationStateChangingResolveAssist.dumpInfobaseObjects(ConflictResolveOption.java:136)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.MergingConflictResolver.resolveConflict(MergingConflictResolver.java:159)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ConflictResolveOption$SyncrhonizationStateChangingConflictResolver.resolveConflict(ConflictResolveOption.java:95)

	at com._1c.g5.v8.dt.platform.services.ui.infobases.sync.InfobaseUpdateDialogBasedCallback.onInfobaseChanges(InfobaseUpdateDialogBasedCallback.java:170)

	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard$DelegatingInfobaseUpdateCallback.onInfobaseChanges(ImportConfigurationWizard.java:909)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ConflictResolveOption.onConflict(ConflictResolveOption.java:68)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.checkConflict(AbstractInfobaseConnection.java:950)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.pullChanges(AbstractInfobaseConnection.java:424)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.pullChanges(ParticipantAwareInfobaseConnection.java:100)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.pullChanges(ReconnectableInfobaseConnection.java:150)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobasePullChangesRequested(OnDemandSynchronizationStrategy.java:181)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.pullConnectedInfobaseChanges(InfobaseSynchronization.java:632)

	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.pullInfobaseChanges(InfobaseSynchronizationManager.java:329)

	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.pullInfobaseChanges(Unknown Source)

	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.pullInfobaseChanges(ImportConfigurationWizard.java:571)

	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.updateInfobase(ImportConfigurationWizard.java:500)

	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$1(ImportConfigurationWizard.java:222)

	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

Caused by: com._1c.g5.designer.ssh.client.DesignerClientException: Ошибка при выполнении файловой операции 

	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.processExecutionResponses(AbstractQuery.java:153)

	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.execute(AbstractQuery.java:134)

	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.exec(AbstractQuery.java:85)

	at com._1c.g5.internal.designer.ssh.client.operation.AbstractTransferingQuery.callOperation(AbstractTransferingQuery.java:104)

	at com._1c.g5.internal.designer.ssh.client.operation.TransferingDumpFilesQuery.exec(TransferingDumpFilesQuery.java:48)

	at com._1c.g5.internal.designer.ssh.client.operation.TransferingDumpFilesQuery.exec(TransferingDumpFilesQuery.java:24)

	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.lambda$5(DesignerSessionThickClientLauncher.java:320)

	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:95)

	... 22 more

### Версия 1С:EDT

2021.3.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by tormozit** [comment]
Перевод сервера 1С и проекта EDT на платформу 8.3.20 решил проблему. До этого я тоже делал попытки работы с 8.3.21 и они заканчивались той же проблемой.

**Comment by sfaqer** [comment]
В версиях 2021.3.4 / 8.3.21.1302 всё ещё актуально

**Comment by Mezijas** [comment]
По сути проблема проявляется в процессе сравнения конфигурации проекта и иб. Судя по моему примеру проблема проявляется на любых изменениях конфигурации иб (в моем случае был изменен реквизит общей формы).

**Comment by sfaqer** [comment]
> По сути проблема проявляется в процессе сравнения конфигурации проекта и иб. Судя по моему примеру проблема проявляется на любых изменениях конфигурации иб (в моем случае был изменен реквизит общей формы).

Проблема проявляется в том что платформа падает в ошибку при выгрузке конфигурации в файлы, после того как конфигурация была импортирована из едт.
До этапа сравнения оно даже не доходит
