### ISSUE TITLE
Проект не отображается в виде обычного дерева конфигурации 1С: только корень и папки .settings, DT-INF, src и unknown

### ISSUE THREAD

**Issue by yegor-novinsky** [1C-Company/1c-edt-issues#438]
### Описание ошибки

После установки 2021.3.4 при каждом открытии выполняется конвертация проекта, после чего в Навигаторе появляется дерево из папок. В процессе конвертации нормальный вид дерева конфигурации мелькает, но в конце все равно только иерархия папок.
Пробовал конвертировать конфигурацию с нуля - эффект тот же.

### Как воспроизвести

Т.к. вижу в дереве папку unknown, содержащую интерфейсы (остались в конфигурации со старых времен), возможно, нужно добавить в конфигурацию интерфейс, и конвертировать ее. Но, точнее сказать не могу. на 2021.3.3 дерево конфигурации вполне отображалось.

### Скриншоты

![EDT_2021_3_4](https://user-images.githubusercontent.com/20304311/163910528-bcb6ec15-37fa-4cb8-9c90-676cdad721c4.png)

### Ожидаемое поведение

После открытия и инициализации EDT в навигаторе появляется дерево конфигурации

### Лог рабочей области

[last.log](https://github.com/1C-Company/1c-edt-issues/files/8509463/last.log)
[bak_1.log](https://github.com/1C-Company/1c-edt-issues/files/8509467/bak_1.log)
[bak_2.log](https://github.com/1C-Company/1c-edt-issues/files/8509468/bak_2.log)
[bak_0.log](https://github.com/1C-Company/1c-edt-issues/files/8509469/bak_0.log)

[trace.log](https://github.com/1C-Company/1c-edt-issues/files/8509453/trace.log)
О

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Версия платформы 8.3.20.1674, версия платформы проекта 8.3.20. Редактор проекта не открывается с такой ошибкой

org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.core.expressions.EvaluationContext.<init>(EvaluationContext.java:49)
	at com._1c.g5.v8.dt.internal.ui.editor.ProjectEditorSectionDescriptor.isEnabled(ProjectEditorSectionDescriptor.java:122)
	at com._1c.g5.v8.dt.internal.ui.editor.ProjectEditorPagesFactory.lambda$0(ProjectEditorPagesFactory.java:61)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com._1c.g5.v8.dt.internal.ui.editor.ProjectEditorPagesFactory.createPages(ProjectEditorPagesFactory.java:62)
	at com._1c.g5.v8.dt.internal.ui.editor.ProjectEditor.addPages(ProjectEditor.java:90)
	at org.eclipse.ui.forms.editor.FormEditor.createPages(FormEditor.java:143)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:333)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:999)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:964)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:405)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:332)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:999)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:765)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:730)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:714)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:104)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4742)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:660)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:624)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:786)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:400)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1260)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3195)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3100)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3068)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3051)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:606)
	at com._1c.g5.v8.dt.internal.ui.editor.OpenProjectEditorAction.runWithEvent(OpenProjectEditorAction.java:54)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

**Comment by yegor-novinsky** [comment]
На всякий случай. Конфигурацию предоставить не могу.

**Comment by vadimeg** [comment]
Без конфигурации, наверное, будет сложно воспроизвести.
Похоже, что-то недогрузилось из файлов конфигурации.

Потерялся гитовый файл:
E:\EDT\workspace\.metadata\.plugins\org.eclipse.core.resources\.projects\testmozhaysk\org.eclipse.egit.core\GitProjectData.properties

См.
https://www.eclipse.org/forums/index.php/t/240167/
Looks like your workspace lost the file storing the information which projects are shared with EGit.

**Comment by yegor-novinsky** [comment]
Если я ему этот файл подсуну, все заработает?

**Comment by vadimeg** [comment]
Не знаю, если это единственная причина, то заработает)
Просто сейчас весь лог забит ошибками, связанными с настройками гита.
Потом попробуйте закрыть EDT, удалить лог, запустить EDT.

**Comment by yegor-novinsky** [comment]
Зачем удалять лог-файлы?

**Comment by vadimeg** [comment]
Чтобы ничего лишнего от предыдущих запусков не мешалось. Если проблема останется, просто прикрепите новый .log

**Comment by yegor-novinsky** [comment]
Удалил папку E:\EDT\workspace.metadata.plugins\org.eclipse.core.resources.projects\testmozhaysk совсем. Попробую вычистить все упоминания о testmozhaysk.
НО... легче не стало. Забыл сказать, при каждом открытии оно начинаем импортировать проект заново.

**Comment by yegor-novinsky** [comment]
Ничего не получилось - дерево все равно не отображается

**Comment by yegor-novinsky** [comment]
Первая запись при попытке запуска такая (проект, который предполагается живым, - testmozhaysk1)
!MESSAGE Необходима очистка данных проекта testmozhaysk1 по причине изменения модели форм

**Comment by yegor-novinsky** [comment]
Прикладываю часть лога, относящуюся к вчерашней попытке запуска ED
[log.txt](https://github.com/1C-Company/1c-edt-issues/files/8536383/log.txt)
T

**Comment by vadimeg** [comment]
А есть в конфигурации "тяжелые" файлы, ну, чтоб прям несколько десятков Мб? Если есть, то что это за файлы?

**Comment by yegor-novinsky** [comment]
А есть какая-то команда в windows, которая по иерархии подпапок это выведет?

**Comment by vadimeg** [comment]
https://superuser.com/questions/653860/list-files-recursively-showing-only-full-path-and-file-size-from-windows-command

**Comment by yegor-novinsky** [comment]
Это максимальный (размер, как понимаю, в байтах)
 101332324 Template.mxlx
потом 
54475523 Template.mxlx
потом 
45590445 Template.addin
потом
36575250 Template.bin

**Comment by yegor-novinsky** [comment]
Самый тяжелый файл это макет табличного документа с большим количеством цветных картинок. Из-за этого макета 2021.2.сколько-то проект не конвертировала совсем.

**Comment by vadimeg** [comment]
@yegor-novinsky А можете этот тяжелый макет прислать?

**Comment by yegor-novinsky** [comment]
Нет

**Comment by vadimeg** [comment]
Есть ограничение на размер в хранилище EDT.
Как вариант решения можно попробовать не напрямую в табличный документ толкать картинки, а создавать общие картинки и их уже использовать в табличном документе.
В будущем, возможно, проблема будет решена.

**Comment by yegor-novinsky** [comment]
А почему в пошлых версиях работало?

**Comment by vadimeg** [comment]
Без конфигурации сложно сказать. Предлагаемое решение с табличным документом - тоже не 100% гарантия, это одна из ошибок (найденная в логе), которая могла привести к такой ситуации.

**Comment by yegor-novinsky** [comment]
Ну, раз никто не проголосовал, то извините за беспокойство. ...
Предлагаю создать некий list of features, которые присутствуют в конфигураторе, но которые не планируется включать в функционал EDT. Например, поддержку макетов большого размера.

**Comment by FSmile** [comment]
[WS1.zip](https://github.com/1C-Company/1c-edt-issues/files/8855766/WS1.zip)
Аналогичная ситуация проект с пустой базой. Во вложении workspace
![Бага](https://user-images.githubusercontent.com/12209724/172459532-0af615a3-431e-4422-b04b-a07b055b5d61.png)

**Comment by MaksimDzyuba** [comment]
> [WS1.zip](https://github.com/1C-Company/1c-edt-issues/files/8855766/WS1.zip) Аналогичная ситуация проект с пустой базой. Во вложении workspace ![Бага](https://user-images.githubusercontent.com/12209724/172459532-0af615a3-431e-4422-b04b-a07b055b5d61.png)

да, это известная ошибка, что при переоткрытии edt данный редактор не корректно отображает содержимое, если его переоткрыть, то становится все норм.

**Comment by tretyakevich** [comment]
В версии 2023.1 пересмотрено хранилище, после выхода рекомендуется проверить данный сценарий на этой версии.
Поскольку тестовые данные не могут быть предоставлены - критичность понижена.

**Comment by Erik773** [comment]
Задача закрыта из-за невозможности воспроизведения.
Если появится дополнительная информация, которая может способствовать воспроизведению проблемы, задачу можно переоткрыть.
