### ISSUE TITLE
В EDT не отображается ошибка "Записи регистра сведений стали неуникальными" при реструктуризации базы 1С

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#441]
### Описание ошибки

В окне "Обновление конфигурации в приложении" нажимаю "Готово". Жду и получаю окно с ошибкой "Ошибка файловой операции с базой" и в логе вижу все непонятное. Проблема эта давнишняя.

### Как воспроизвести

1. Перейдите в `...`
2. Кликните по `....`
3. Прокрутите вниз до `....`
4. Смотрите ошибку в `....`

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11896251/164451384-9501f273-cb1d-46ea-aed0-fdb9db2a6802.png)

![изображение](https://user-images.githubusercontent.com/11896251/164451783-75b0db0b-3760-40fe-bf71-97c0a9ce72ba.png)

### Ожидаемое поведение

 Надо показывать понятную информацию в этой ситуации.

### Лог рабочей области

com.e1c.g5.dt.applications.ApplicationException: Ошибка исполнения 1С:Предприятия
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationBehaviourDelegate.publish(InfobaseApplicationBehaviourDelegate.java:109)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.publish(ApplicationManager.java:275)
	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.publish(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployConfiguration(DeployConfigurationWizard.java:569)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployExistingApplications(DeployConfigurationWizard.java:210)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.lambda$0(DeployConfigurationWizard.java:163)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: com._1c.g5.v8.dt.platform.services.core.infobases.sync.InfobaseSynchronizationException: Ошибка исполнения 1С:Предприятия
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:294)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadConfiguration(ParticipantAwareInfobaseConnection.java:89)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadConfiguration(ReconnectableInfobaseConnection.java:142)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:104)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.updateConnectedInfobase(InfobaseSynchronization.java:609)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.reloadInfobase(InfobaseSynchronizationManager.java:295)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.reloadInfobase(Unknown Source)
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationBehaviourDelegate.publish(InfobaseApplicationBehaviourDelegate.java:95)
	... 6 more
Caused by: com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeCoreException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.21.1197:
Операция конфигурирования завершена неуспешно
Ошибка обновления конфигурации базы данных
Записи регистра сведений стали неуникальными: ОчередьСобытий
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:127)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.execInDesignerSession(DesignerSessionThickClientLauncher.java:933)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.importConfigurationFromXml(DesignerSessionThickClientLauncher.java:372)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.ThickClientLauncher.importConfigurationFromXml(ThickClientLauncher.java:392)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.importConfigurationFromXml(DesignerSessionThickClientLauncher.java:433)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:263)
	... 13 more
Caused by: com._1c.g5.designer.ssh.client.DatabaseRestructureException: Ошибка обновления конфигурации базы данных
	at com._1c.g5.internal.designer.ssh.client.operation.UpdateConfigurationQuery.processExecutionResponses(UpdateConfigurationQuery.java:118)
	at com._1c.g5.internal.designer.ssh.client.operation.UpdateConfigurationQuery.processExecutionResponses(UpdateConfigurationQuery.java:39)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.execute(AbstractQuery.java:134)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.exec(AbstractQuery.java:85)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.execUpdateInfobase(DesignerSessionThickClientLauncher.java:908)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.lambda$7(DesignerSessionThickClientLauncher.java:422)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:87)
	... 18 more

### Версия 1С:EDT

2021.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8

**Comment by mrshadow300373** [comment]
Такая проблема не только с не уникальностью РС. Любая проблема при обновлении конфигурации ИБ приводит к такому. Писал про это здесь: [1C:Enterprise Development Tools →   Момент установки состояния ИБ "синхронизировано"]( https://partners.v8.1c.ru/forum/t/1854626/m/1854727), после этого. даже если в рунтайме уберешь записи, в конфигураторе зайдёшь и руками обновишь ИБ всё равно потом приходится заново всё собирать.

**Comment by tormozit** [comment]
В EDT 2025.2 эта информации теперь отображается, а точнее весь текст из окна принятия изменений.
