### ISSUE TITLE
Команда "Импорт" при загрузке конфигурации в проект выдает ошибку

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#481]
### Описание ошибки

Ошибка взаимодействия с платформой 1С:Предприятия 8.3.21.1197:
Операция конфигурирования завершена неуспешно
Ошибка при выполнении файловой операции 

### Как воспроизвести

Платформа 8.3.21
1. В панели "1С Навигатор" через контекстное меню выполнить "Импорт..."
2. Выбрать тип проекта "Конфигурация"
3. Указать имя несуществующего проекта
4. Нажать кнопку "Импорт"
5. Возникает ошибка

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11896251/170267332-1680e2dc-55bc-4603-a052-72d946128d5b.png)

### Ожидаемое поведение

отсутствие ошибки

### Лог рабочей области

java.lang.reflect.InvocationTargetException
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$8(ImportConfigurationWizard.java:709)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.RuntimeOperationSupport.execRuntimeOperation(RuntimeOperationSupport.java:96)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.importConfiguration(ImportConfigurationWizard.java:637)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$1(ImportConfigurationWizard.java:222)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.util.concurrent.ExecutionException: com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeExecutionException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.21.1197:
Операция конфигурирования завершена неуспешно
Ошибка при выполнении файловой операции 
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com._1c.g5.v8.dt.platform.services.core.ProgressMonitorAwareExecutor.syncExec(ProgressMonitorAwareExecutor.java:95)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$8(ImportConfigurationWizard.java:646)
	... 4 more
Caused by: com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeExecutionException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.21.1197:
Операция конфигурирования завершена неуспешно
Ошибка при выполнении файловой операции 
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:145)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.execInDesignerSession(DesignerSessionThickClientLauncher.java:933)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.exportConfigurationToXml(DesignerSessionThickClientLauncher.java:244)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportConfigurationWizard.lambda$9(ImportConfigurationWizard.java:648)
	at com._1c.g5.v8.dt.platform.services.core.ProgressMonitorAwareExecutor.lambda$0(ProgressMonitorAwareExecutor.java:61)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com._1c.g5.designer.ssh.client.DesignerClientException: Ошибка при выполнении файловой операции 
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.processExecutionResponses(AbstractQuery.java:153)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.execute(AbstractQuery.java:134)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.exec(AbstractQuery.java:85)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractTransferingQuery.callOperation(AbstractTransferingQuery.java:104)
	at com._1c.g5.internal.designer.ssh.client.operation.TransferingDumpFilesQuery.exec(TransferingDumpFilesQuery.java:48)
	at com._1c.g5.internal.designer.ssh.client.operation.TransferingDumpFilesQuery.exec(TransferingDumpFilesQuery.java:24)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.lambda$4(DesignerSessionThickClientLauncher.java:265)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:87)
	... 8 more

eclipse.buildId=2021.3.4.10
java.version=11.0.12
java.vendor=BellSoft
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\EDTAFW

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

**Comment by tormozit** [comment]
Проблема находится на стороне платформы 1С. Она не может выгрузить конфигурацию поддержки БСП. Ошибка выполнения файловой операции воспроизводится при выгрузке конфигурации в файлы в конфигураторе.

![изображение](https://user-images.githubusercontent.com/11896251/170426776-cf7aba3c-fa29-4cb1-a8cf-5169db0d1edb.png)

![изображение](https://user-images.githubusercontent.com/11896251/170426785-2311285e-89c3-4269-a590-7130640922cd.png)
