### ISSUE TITLE
Работа с удаленным автономным сервером

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/1c-edt-issues#489]
### Описание ошибки

Понимаю, что возможно "бегу впереди паровоза", но на всякий случай размещу тут этот кейс
ошибка при попытке запуска отладки приложения на удаленном автономном сервере
![image](https://user-images.githubusercontent.com/32670094/171800889-ec44881b-42c9-432a-8a36-bc483da83090.png)

дано 
- автономный сервер, расположенный удалённо с указанием сервера отладки
- там же расположен dbgs сервер отладки 
- на локальной машине есть ЕДТ с проектом
- в проекте подключено приложение на автономном сервере

в окне приложение (или в общем меню)  жму "запустить" либо "отладка" (тонкий клиент) и получаю  ошибку
при этом загрузки-выгрузки конфигурации в ИБ из проекта и обратно прекрасно работают

если запустить конфигуратор и запустить отладку там (на пустой базе, как указано в ИТС по оотлкдке с автономным сервером... указать сервер отладки, имя базы итд) то  отладка там работает 

пробовал в ЕДТ настройках отладки делать "подключение к удаленному серверу" и подклчюаться к запущенному клиенту , вобщем-то в точку останова на сервере я в ЕДТ попадаю, но при этом не виден клиент и серверный сеанс.. т.е остановка срабатывает и на этом всё, управлять отладкой не получается

настройки автономного сервера:
`server:
  address: any
  port: 8314
database:
  dbms: PostgreSQL
  server: localhost
  name: aun_test
  user: xxxxx
  password: xxxxx
infobase:
  name: aun_test
  distribute-licenses: yes
  schedule-jobs: deny
http:
  base: /aun_test
gates:
  ssh:
    default:
      address: any
      port: 8282
      host-key: /xxxx`

### Как воспроизвести

Подключить приложение на автономном удаленном сервере и попробовать запустить отладку

### Скриншоты

![image](https://user-images.githubusercontent.com/32670094/171800425-8917516b-2622-417f-8008-607457b35742.png)
![image](https://user-images.githubusercontent.com/32670094/171800444-8cea4575-af83-4d20-aff6-dca7f6a35530.png)

### Ожидаемое поведение

ожидается запуск тонкого клиента для отладки на компьютере разработчика и нормальное подключение отладчика ЕДТ к серверу и клиенту отладки 

### Лог рабочей области

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:48:43.064
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.debug.core 4 1100 2022-06-01 14:48:43.341
!MESSAGE Произошла ошибка в течение запуска 1С:Предприятия:
1C:Enterprise platform Удаленное 1С:Предприятие  ssh://pp1cserver:8282 has no Тонкий клиент component installed
!STACK 0
com.e1c.g5.dt.applications.ApplicationException: 1C:Enterprise platform Удаленное 1С:Предприятие  ssh://pp1cserver:8282 has no Тонкий клиент component installed
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationClientDelegate.open(InfobaseApplicationClientDelegate.java:111)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.lambda$10(ApplicationManager.java:317)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.open(ApplicationManager.java:317)
	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.open(Unknown Source)
	at com._1c.g5.v8.dt.internal.launching.core.launchconfigurations.RuntimeClientLaunchDelegate.doLaunch(RuntimeClientLaunchDelegate.java:212)
	at com._1c.g5.v8.dt.debug.core.launchconfigurations.CustomErrorHandlingLaunchDelegate.launch(CustomErrorHandlingLaunchDelegate.java:56)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:48:43.379
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:49:10.031
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:49:10.043
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:49:18.135
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:49:31.339
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:49:31.341
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:49:31.388
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:49:31.425
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:49:57.407
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:56:24.873
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:56:24.888
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:56:29.924
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:56:40.709
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:56:40.711
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:56:40.725
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 14:59:16.438
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 15:00:25.338
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 15:00:27.227
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 15:00:27.237
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 15:00:27.239
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2022-06-01 15:00:27.242
!MESSAGE Updating connections up to associations...

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 15:00:27.250
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.debug.core 4 1100 2022-06-01 15:00:27.251
!MESSAGE Произошла ошибка в течение запуска 1С:Предприятия:
1C:Enterprise platform Удаленное 1С:Предприятие  ssh://pp1cserver:8282 has no Тонкий клиент component installed
!STACK 0
com.e1c.g5.dt.applications.ApplicationException: 1C:Enterprise platform Удаленное 1С:Предприятие  ssh://pp1cserver:8282 has no Тонкий клиент component installed
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationClientDelegate.open(InfobaseApplicationClientDelegate.java:111)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.lambda$10(ApplicationManager.java:317)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.open(ApplicationManager.java:317)
	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.open(Unknown Source)
	at com._1c.g5.v8.dt.internal.launching.core.launchconfigurations.RuntimeClientLaunchDelegate.doLaunch(RuntimeClientLaunchDelegate.java:212)
	at com._1c.g5.v8.dt.debug.core.launchconfigurations.CustomErrorHandlingLaunchDelegate.launch(CustomErrorHandlingLaunchDelegate.java:56)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 15:01:11.080
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 15:01:12.998
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 15:01:18.569
!MESSAGE Не удалось получить версию для информационной базы "AUN_test", для работы будет использоваться версия 8.3.21.

!ENTRY com._1c.g5.v8.dt.platform.services.core 2 0 2022-06-01 15:01:18.573

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `Название плагина...`

**Comment by goodwinvu** [comment]
Опытным путём выяснено, что EDT пытается запустить тонкого клиента в сеансе SSH (гейт управления авт.сервером) в случае если НЕ УКАЗАНА ТОЧНО ВЕРСИЯ ПЛАТФОРМЫ в конфигурации отладки :)
лечение - указать версию платформы и всё ок (прям точно 4 цифры)

**Comment by goodwinvu** [comment]
а не, достаточно 3 цифры версии платформы
