### ISSUE TITLE
Не работают настройки публикации на на встроенном сервере Apache 2.4 

### ISSUE THREAD

**Issue by goodwinvu** [1C-Company/1c-edt-issues#524]
### Описание ошибки

При публикации информационной базы на встроенном сервере Apache 2.4 не учитываются настройки 
- месторасположение публикации
- каталог временных файлов
Также на встроенном веб-сервере не публикуются http сервисы расширений.

### Как воспроизвести

ПКМ по проекту - выбираем пункт "Опубликовать информационную базу"
В открывшемся мастере ввыбираем вебсервер - "Встроенный Apache 2.4" и указываем настройки (путь, отладку итд)
и жмём "Готово"
![image](https://user-images.githubusercontent.com/32670094/175234185-58b2c455-a713-4a84-909f-c79c59355e80.png)

при публикации путь, каталог временных итд - остаются по умолчанию:
ПапкаПроекта\.metadata\.plugins\com.company1c.link.ide.edt.lanweb\web-config\

более того, если после публикации открыть её настройк из панели "Веб-серверы"
то там указанные поля тоже пустые (окно, кстати СРАЗУ открывается со "звездочкой" т.е с признаком редактированиях)
![image](https://user-images.githubusercontent.com/32670094/175235063-975868ed-e352-4f84-86e8-9c322db5b66a.png)

При этом не учитываются например настройки публикации HTTPсервисов расширений, галка в окне настроек стоит , а в если посмотреть в файл публикации, то там нужный тэг отсутствует.
![image](https://user-images.githubusercontent.com/32670094/175235593-a13d7ce2-cbea-4e7f-8847-baa7465caf97.png)
![image](https://user-images.githubusercontent.com/32670094/175235678-33538fad-b65a-467b-a380-a1a59d9c4daa.png)

### Ожидаемое поведение

Настройки в мастере публикации и в свойствах сервера должны работать и применяться корректно.

### Лог рабочей области

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2022-06-22 16:54:32.516
!MESSAGE Updating connections up to associations...

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2022-06-22 16:54:32.650
!MESSAGE Updating connections up to associations...

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2022-06-22 16:54:32.777
!MESSAGE Updating connections up to associations...

!ENTRY com.company1c.link.agent.publicator 0 0 2022-06-23 09:53:27.847
!MESSAGE Starting Apache X86: C:\Users\vyacheslav.belyaev\.p2\pool\plugins\com.company1c.link.agent.publicator.win32_3.0.3\binaries\httpd_2.4.41-x86\bin\httpd.exe -f C:\EDTdata\ALL\.metadata\.plugins\com.company1c.link.ide.edt.lanweb\web-config\httpd-60619.conf

!ENTRY com.company1c.link.agent.publicator 0 0 2022-06-23 09:53:28.360
!MESSAGE Apache HTTPD X86 has failed to start
!STACK 0
com.company1c.link.agent.exceptions.LinkAgentRuntimeException: httpd.exe: Syntax error on line 41 of C:/EDTdata/ALL/.metadata/.plugins/com.company1c.link.ide.edt.lanweb/web-config/httpd-60619.conf: Cannot load C:\\Program Files\\1cv8\\8.3.21.1302\\bin\\wsap24.dll into server: %1 \xed\xe5 \xff\xe2\xeb\xff\xe5\xf2\xf1\xff \xef\xf0\xe8\xeb\xee\xe6\xe5\xed\xe8\xe5\xec Win32.  

	at com.company1c.link.agent.publicator.arch.WindowsApacheHttpdUtils.lambda$1(WindowsApacheHttpdUtils.java:80)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

!ENTRY com.company1c.link.agent.publicator 0 0 2022-06-23 09:53:28.362
!MESSAGE Starting Apache X86_64: C:\Users\vyacheslav.belyaev\.p2\pool\plugins\com.company1c.link.agent.publicator.win32_3.0.3\binaries\httpd_2.4.41-x86_64\bin\httpd.exe -f C:\EDTdata\ALL\.metadata\.plugins\com.company1c.link.ide.edt.lanweb\web-config\httpd-60619.conf

!ENTRY com.company1c.link.agent.publicator 1 0 2022-06-23 09:53:38.853
!MESSAGE Apache HTTPD X86_64 started on port 60619, command line: C:\Users\vyacheslav.belyaev\.p2\pool\plugins\com.company1c.link.agent.publicator.win32_3.0.3\binaries\httpd_2.4.41-x86_64\bin\httpd.exe -f C:\EDTdata\ALL\.metadata\.plugins\com.company1c.link.ide.edt.lanweb\web-config\httpd-60619.conf

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, 1C:Language Tool, Другие сторонние плагины `Название плагина...`

### Дополнительная информация

установлены плагины 
-  Disable Editing plugin for 1C:EDT	0.4.0.20220109-0712
-  DevStyle (includes Darkest Dark Theme)	1.11.0.202206131352

**Comment by AvalorOFF** [comment]
Существует как-либо решение этого вопроса? Мб в ручную что-нибудь сделать?
