### ISSUE TITLE
Не создается новая форма для планов обмена

### ISSUE THREAD

**Issue by zubovas** [1C-Company/1c-edt-issues#601]
### Описание ошибки

Ошибка повторяется в течении последних 6 месяцев. Поскольку в других проектах все работает, нет очевидного решения где искать ошибку. Очистки проекта и обновления версий EDT не помогают.

**Описание ошибки**

1. При создании новой формы планов обмена, после выполнения действия "Формы-Создать-Форма" ничего не происходит. Форма не создается.

![image](https://user-images.githubusercontent.com/37978992/184384044-a7f6b30f-8e1a-48f7-861b-720f9dc0080d.png)

2. Уже существующие формы открываются "пустыми", нет элементов формы

![image](https://user-images.githubusercontent.com/37978992/184384251-92b80330-5a2f-4866-b057-a1d950781a44.png)

Эта же форма в конфигураторе 1С

![image](https://user-images.githubusercontent.com/37978992/184384526-f9aea2b5-d2ca-466c-bf06-4b7060795f5d.png)

**Дополнительные сведенья**
При экспорте файлов конфигурации, падает ошибка

![image](https://user-images.githubusercontent.com/37978992/184387755-24d3e0ee-861e-4dcd-9769-09f104043625.png)

XML-файлы форм планов обмена сохранены не корректно.

![image](https://user-images.githubusercontent.com/37978992/184595875-d3d223ea-1864-4071-b443-ec439565d0c2.png)

Через утилиту ring экспорт конфигурации в файлы идет нормально. Без ошибок.

### Как воспроизвести

1. В ветке объектов метаданных "Планы обмена", перейдите к любому плану обмена и откройте список форм
2. Кликните ПКМ на ветке "Формы"
3. Выберете пункт меню "Создать-Форма"
4. Ничего не происходит. Форма не создается

### Ожидаемое поведение

Создаваемые формы должны создаваться.
Открываемые формы должны отображать элементы форм

### Лог рабочей области

**Создание новой формы**

eclipse.buildId=2022.1.0.437
java.version=11.0.12
java.vendor=BellSoft
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data D:\1С\EDT_PROJ\LogisticDev

This is a continuation of log file D:\1С\EDT_PROJ\LogisticDev\.metadata\.bak_0.log
Created Time: 2022-08-12 18:05:55.175

org.eclipse.ui
Ошибка
Mon Aug 15 10:49:38 MSK 2022
Unhandled event loop exception

java.lang.IllegalArgumentException: Cannot find DbViewField with "ThisNode" name from source "null"
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at com._1c.g5.v8.dt.internal.form.datasourceinfo.property.MdObjectPropertyInfoProvider.createPropertyInfoByDbViewField(MdObjectPropertyInfoProvider.java:115)
	at com._1c.g5.v8.dt.internal.form.datasourceinfo.property.ExchangePlanPropertyInfoProvider.addFieldsPropertyInfos(ExchangePlanPropertyInfoProvider.java:64)
	at com._1c.g5.v8.dt.internal.form.datasourceinfo.property.ExchangePlanPropertyInfoProvider.getPropertyInfo(ExchangePlanPropertyInfoProvider.java:37)
	at com._1c.g5.v8.dt.form.model.impl.PropertyInfoProviderRegistryImpl.getPropertyInfo(PropertyInfoProviderRegistryImpl.java:136)
	at com._1c.g5.v8.dt.internal.form.generator.FormFieldsGenerator.getObjectFormGeneratorFields(FormFieldsGenerator.java:194)
	at com._1c.g5.v8.dt.internal.form.generator.FormFieldsGenerator.getFormGeneratorFields(FormFieldsGenerator.java:162)
	at com._1c.g5.v8.dt.form.ui.wizard.FormWizard$FormModel$1.modelChanged(FormWizard.java:392)
	at com._1c.g5.aef2.models.Model.notifyModelChanged(Model.java:109)
	at com._1c.g5.aef2.models.value.Value.notifyValueChanged(Value.java:153)
	at com._1c.g5.aef2.models.value.Value$1.run(Value.java:171)
	at com._1c.g5.aef2.engines.IRunnableQueue$1.queueRunnable(IRunnableQueue.java:22)
	at com._1c.g5.aef2.models.value.Value.queueNotifyValueChanged(Value.java:166)
	at com._1c.g5.aef2.models.value.Value.set(Value.java:51)
	at com._1c.g5.v8.dt.form.ui.wizard.FormWizard$FormModel.<init>(FormWizard.java:479)
	at com._1c.g5.v8.dt.form.ui.wizard.FormWizard.createWizardModel(FormWizard.java:249)
	at com._1c.g5.v8.dt.form.ui.wizard.FormWizard.getMdObjectModel(FormWizard.java:226)
	at com._1c.g5.v8.dt.md.ui.wizards.base.aef.DtAefMdNewWizard.getModelForPageComponent(DtAefMdNewWizard.java:142)
	at com._1c.g5.v8.dt.form.ui.wizard.FormWizard.getModelForPageComponent(FormWizard.java:239)
	at com._1c.g5.v8.dt.md.ui.wizards.base.aef.DtAefNewWizard$AefPage.initializeComponentModel(DtAefNewWizard.java:110)
	at com._1c.g5.v8.dt.md.ui.wizards.base.aef.DtAefNewWizardPage.createPageControls(DtAefNewWizardPage.java:77)
	at com._1c.g5.v8.dt.ui.wizards.DtNewWizardPage.createControl(DtNewWizardPage.java:58)
	at com._1c.g5.v8.dt.md.ui.wizards.base.DtNewWizard.createPageControls(DtNewWizard.java:215)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:743)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:635)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.ui.internal.navigator.wizards.WizardShortcutAction.run(WizardShortcutAction.java:99)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

### Версия 1С:EDT

Ruby EDT 2022.1

### Операционная система

Windows

**Comment by vadimeg** [comment]
Добрый день!
Несколько вопросов и замечаний.
1. Лог приложен для версии EDT 2021.2.12.2, а баге указано, что версия Ruby EDT 2022.1. Где-то нестыковка - или лог не тот или версия не так в баге указана.
2. На картинке, где написано, что формы "пустые", это файл метаданных формы. Сама форма внутри каталога ФормаУзла/Ext
3. Какая использовалась версия платформы?
4. Можете прислать конфигурацию? Если нет, то можно создать рядом с вашей конфигурацией пустую тестовую конфу и копипастом скопировать туда план обмена, формы которого не создаются. Только для той же версии платформы создавайте. Создаются ли в тестовой конфигурации формы плана обмена в скопированном плане? Если нет, то можете тогда прислать эту тестовую конфу?

**Comment by zubovas** [comment]
Приветствую.
Спасибо за оперативный ответ.

По вопросам:

   1. Версия в логах почему-то не так, которая отображается в информации о
   программе. Такое ощущение что обновления устанавливаются в каталог со
   старой версией EDT
   2. Поправил скрин.
   3. 8.3.9
   4. По конфигурации уточню возможность отправки. Не нарушает ли правила
   безопасности. Скорее всего пришлю.


вс, 14 авг. 2022 г. в 15:03, Vadim Geraskin ***@***.***>:

**Comment by zubovas** [comment]
По конфигурации попросили запросить НДА. По неразглашению информации. Это
возможно?

пн, 15 авг. 2022 г. в 10:57, Andrey Zubov ***@***.***>:

**Comment by vadimeg** [comment]
> По конфигурации попросили запросить НДА. По неразглашению информации. Это возможно?
Насчет NDA уточню, пока не знаю. А не пробовали, по пункту 4, скопировать план обмена в пустую конфигурацию и попытаться открыть форму? Есть подозрение, что именно в плане обмена какие-то настройки, которые приводят к такой ситуации.

У себя попробовал для 8.3.9 создать план обмена с формой, все работает и открывается

**Comment by vadimeg** [comment]
Да, и еще, какая полная версия платформы. У меня 8.3.9.2309

**Comment by zubovas** [comment]
Добрый день.

1. Создал новый проект с пустой конфигурацией. Скопировал туда план обмена
из проблемного проекта. Все заработало. Но в проблемном проекте с этой
ошибкой работают все планы обмена, а не какой-то конкретный.
2. Версия платформы 8.3.9.2233

пн, 15 авг. 2022 г. в 17:24, Vadim Geraskin ***@***.***>:

**Comment by vadimeg** [comment]
А новый проект создавали для версии 8.3.9?
Формы не создаются только для планов обмена? Для других объектов все ОК?

**Comment by vadimeg** [comment]
И еще проверьте, что в форме узла оригинальной конфигурации (не тестовой) в объекту присутствует поле ЭтотУзел
![image](https://user-images.githubusercontent.com/17178862/184836349-c8592160-3bbd-4dd0-adc6-9f8ddab54cf8.png)

**Comment by zubovas** [comment]
Да. 8.3.9. Проблема только с планами обмена

вт, 16 авг. 2022 г., 11:22 Vadim Geraskin ***@***.***>:

**Comment by zubovas** [comment]
Не раскрывается список полей у объекта на форме

вт, 16 авг. 2022 г., 11:39 Vadim Geraskin ***@***.***>:

**Comment by vadimeg** [comment]
> Не раскрывается список полей у объекта на форме
Хм, похоже где-то в проекте нарушена целостность данных. Без конфигурации, на которой воспроизводится проблема, сложно выяснить в чем дело. С NDA у нас такой практики нет, чтобы разработчики что-то подписывали для получения конфы. Возможно удастся сделать простую конфигурацию, где проблема воспроизведется. Может быть стоит поискать отличия (между основной конфигурацией и тестовой, где проблема не воспроизводится) в файле конфигурации (Configuration.mdo).

А если создать не форму внутри существующего плана обмена, а сначала создать новый план, а в нем форму, то та же проблема?

**Comment by zubovas** [comment]
Ссылка на архив с проблемным проектом.
 main.7z
<https://drive.google.com/file/d/1yErW4_8wJ38V_AfGOL1uvoRZvrWglTSX/view?usp=drive_web>


вт, 16 авг. 2022 г. в 13:44, Vadim Geraskin ***@***.***>:

**Comment by vadimeg** [comment]
Проблема в режиме совместимости конфигурации, который был выставлен в 8.3.2. В EDT такой режим можно выставить либо вручную (изменив файл конфигурации), либо загрузив базу из конфигуратора. В UI EDT допустимый режим совместимости совместимости начинается в 8.3.6.
Для планов обмена поле ЭтотУзел доступно начиная с версии 8.3.5.
Проблему закрываю и заведу внутренний баг на исправление.

**Comment by zubovas** [comment]
Так тоже не работает

вт, 16 авг. 2022 г., 13:44 Vadim Geraskin ***@***.***>:

**Comment by vadimeg** [comment]
> Так тоже не работает

Не работает, если у конфигурации поменять режим совместимости на 8.3.6?
