### ISSUE TITLE
Невозможно загрузить WSDL схему из web источника

### ISSUE THREAD

**Issue by vl-sher** [1C-Company/1c-edt-issues#609]
### Описание ошибки

Невозможно загрузить WSDL схему из web источника, в логе ошибка
Ошибка доступа к файлу 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl'

### Как воспроизвести

1. Создать новую ws-ссылку
2. Задать имя CBR
3. Задать URL источника http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl
4. Нажать Открыть или открыть закладку WS-ссылка - WSDL описание пустое. В логе ошибка
`Ошибка доступа к файлу 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl'`

### Ожидаемое поведение

После указания URL источника WSDL описание должно быть заполнено.

### Лог рабочей области

!ENTRY com._1c.g5.v8.dt.ws.ui 4 0 2022-08-22 11:58:38.439
!MESSAGE Ошибка доступа к файлу 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl'
!STACK 0
com._1c.g5.v8.dt.ws.common.WSDefinitionLoaderException: Ошибка доступа к файлу 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl'
	at com._1c.g5.v8.dt.ws.common.WSDefinitionLoader.needUrlAuthentification(WSDefinitionLoader.java:158)
	at com._1c.g5.v8.dt.internal.ws.WsDefinitionsNewWizardRelatedModelsFactory.createModels(WsDefinitionsNewWizardRelatedModelsFactory.java:59)
	at com._1c.g5.v8.dt.md.ui.wizards.base.DtNewWizard.createRelatedModels(DtNewWizard.java:667)
	at com._1c.g5.v8.dt.md.ui.wizards.base.DtNewWizard$1.execute(DtNewWizard.java:639)
	at com._1c.g5.v8.dt.md.ui.wizards.base.DtNewWizard$1.execute(DtNewWizard.java:1)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:706)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:667)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTaskInEditingContext(Reactor.java:176)
	at com._1c.g5.v8.bm.integration.internal.context.GlobalEditingContext.execute(GlobalEditingContext.java:40)
	at com._1c.g5.v8.dt.md.ui.wizards.base.DtNewWizard.integrateModel(DtNewWizard.java:402)
	at com._1c.g5.v8.dt.md.ui.wizards.base.DtNewWizard.lambda$0(DtNewWizard.java:238)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1033)
	at com._1c.g5.v8.dt.md.ui.wizards.base.DtNewWizard.performFinish(DtNewWizard.java:235)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.navigator.wizards.WizardShortcutAction.run(WizardShortcutAction.java:102)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

Также невозможно загрузить ws-ссылку из файла, если он содержит импорт типов, например:
`<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GeoAPI" targetNamespace="http://tempuri.org/">
   <wsdl:types>
      <xsd:schema targetNamespace="http://tempuri.org/Imports">
         <xsd:import schemaLocation="https://reg-prijemce.dpd.cz/GeoAPI_v1_4_0/GeoAPI.svc?xsd=xsd0" namespace="http://tempuri.org/" />
         <xsd:import schemaLocation="https://reg-prijemce.dpd.cz/GeoAPI_v1_4_0/GeoAPI.svc?xsd=xsd3" namespace="http://schemas.datacontract.org/2004/07/GeoAPI" />
      </xsd:schema>
   </wsdl:types>
</wsdl:definitions>`

**Comment by vl-sher** [comment]
При попытке "подложить" описание схемы в файл WsDefinitions.wsdl и открыть схему в EDT в логе ошибка:
`!ENTRY org.eclipse.ui 4 0 2022-08-22 12:11:44.220
!MESSAGE Unhandled event loop exception
!STACK 0
java.nio.file.InvalidPathException: Illegal char <:> at index 5: https://reg-prijemce.dpd.cz/GeoAPI_v1_4_0/GeoAPI.svc?xsd=xsd0
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.resolve(Path.java:515)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.getExternalXsdFile(WSDefinitionsSerializer.java:751)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readXDTO(WSDefinitionsSerializer.java:696)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readDefinitions(WSDefinitionsSerializer.java:180)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.readRoot(WSDefinitionsSerializer.java:126)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionsSerializer.deserialize(WSDefinitionsSerializer.java:114)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionResource.doLoad(WSDefinitionResource.java:59)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at com._1c.g5.v8.dt.ws.resource.WSDefinitionResourceFactory.createWorkingCopy(WSDefinitionResourceFactory.java:69)
	at com._1c.g5.v8.dt.internal.ws.ui.editors.WsReferenceGranularEditorModelFactory.createSingleModel(WsReferenceGranularEditorModelFactory.java:40)
	at com._1c.g5.aef2.standard.definitions.models.AbstractMultiFeatureFieldModelFactory.createModel(AbstractMultiFeatureFieldModelFactory.java:47)
	at com._1c.g5.aef2.standard.definitions.models.IModelFactory.createModel(IModelFactory.java:45)
	at com._1c.g5.aef2.standard.definitions.AbstractDefinition.createComponent(AbstractDefinition.java:264)
	at com._1c.g5.aef2.standard.definitions.components.DefinitionDrivenComponent.createComponents(DefinitionDrivenComponent.java:147)
	at com._1c.g5.aef2.components.Component.getComponents(Component.java:121)
	at com._1c.g5.aef2.scenes.Scene.fillEventClassToComponentMap(Scene.java:358)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1033)
	at com._1c.g5.aef2.scenes.Scene.fillEventClassToComponentMap(Scene.java:358)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1033)
	at com._1c.g5.aef2.scenes.Scene.fillEventClassToComponentMap(Scene.java:358)
	at com._1c.g5.aef2.scenes.Scene.refresh(Scene.java:125)
	at com._1c.g5.aef2.scenes.Scene.setComponent(Scene.java:88)
	at com._1c.g5.aef2.engines.Engine.createScene(Engine.java:86)
	at com._1c.g5.v8.dt.md.ui.editor.aef.AbstractDtGranularEditorAefPage.createPageControls(AbstractDtGranularEditorAefPage.java:400)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.createFormContentInternal(DtGranularEditorPage.java:553)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.lambda$2(DtGranularEditorPage.java:394)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4742)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.lambda$1(DtGranularEditorPage.java:393)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.createFormContent(DtGranularEditorPage.java:390)
	at org.eclipse.ui.forms.editor.FormPage.lambda$0(FormPage.java:166)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.forms.editor.FormPage.createPartControl(FormPage.java:166)
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:480)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.pageChange(DtGranularEditor.java:1043)
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1030)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:612)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:518)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.showEditorInput(DtGranularEditor.java:788)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.showEditorInput(DtGranularEditor.java:825)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3151)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3100)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3068)
	at com._1c.g5.v8.dt.ui.util.OpenHelper.open(OpenHelper.java:588)
	at com._1c.g5.v8.dt.ui.util.OpenHelper.openObjectEditorMatching(OpenHelper.java:462)
	at com._1c.g5.v8.dt.ui.util.OpenHelper.openEditor(OpenHelper.java:240)
	at com._1c.g5.v8.dt.ui.util.OpenHelper.openEditor(OpenHelper.java:217)
	at com._1c.g5.v8.dt.md.ui.aef.components.OpenEditorByLinkComponent.handleLinkClicked(OpenEditorByLinkComponent.java:44)
	at com._1c.g5.aef2.standard.components.LinkComponent$1.eventReceived(LinkComponent.java:32)
	at com._1c.g5.aef2.components.Component$3.run(Component.java:272)
	at com._1c.g5.aef2.internal.RunnableQueue$QueueRunnable.run(RunnableQueue.java:284)
	at com._1c.g5.aef2.internal.RunnableQueue.queueAndWait(RunnableQueue.java:103)
	at com._1c.g5.aef2.engines.EngineFactory$WrappingRunnableQueue.queueAndWait(EngineFactory.java:107)
	at com._1c.g5.aef2.engines.Engine.queueAndWaitRunnable(Engine.java:104)
	at com._1c.g5.aef2.components.Component.queueAndWaitEvent(Component.java:260)
	at com._1c.g5.aef2.views.View.queueAndWaitEvent(View.java:256)
	at com._1c.g5.aef2.standard.lwt.views.LwtLinkView.access$2(LwtLinkView.java:1)
	at com._1c.g5.aef2.standard.lwt.views.LwtLinkView$1.linkActivated(LwtLinkView.java:37)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:215)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:309)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.lambda$3(AbstractHyperlink.java:117)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

!ENTRY com._1c.g5.aef2.Aef2Plugin 4 0 2022-08-22 12:11:44.228
!MESSAGE Exception while executing runnable in queue 'DT_GRANULAR_EDITOR_ENGINE': null
!STACK 0
java.lang.NullPointerException
	at com._1c.g5.v8.dt.md.ui.editor.aef.AbstractDtGranularEditorAefPage.showEditorInput(AbstractDtGranularEditorAefPage.java:152)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditorPage.showEditorInput(DtGranularEditorPage.java:203)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.showEditorInput(DtGranularEditor.java:806)
	at com._1c.g5.v8.dt.md.ui.editor.base.DtGranularEditor.showEditorInput(DtGranularEditor.java:825)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3151)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3100)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3068)
	at com._1c.g5.v8.dt.ui.util.OpenHelper.open(OpenHelper.java:588)
	at com._1c.g5.v8.dt.ui.util.OpenHelper.openObjectEditorMatching(OpenHelper.java:462)
	at com._1c.g5.v8.dt.ui.util.OpenHelper.openEditor(OpenHelper.java:240)
	at com._1c.g5.v8.dt.ui.util.OpenHelper.openEditor(OpenHelper.java:217)
	at com._1c.g5.v8.dt.md.ui.aef.components.OpenEditorByLinkComponent.handleLinkClicked(OpenEditorByLinkComponent.java:44)
	at com._1c.g5.aef2.standard.components.LinkComponent$1.eventReceived(LinkComponent.java:32)
	at com._1c.g5.aef2.components.Component$3.run(Component.java:272)
	at com._1c.g5.aef2.internal.RunnableQueue$QueueRunnable.run(RunnableQueue.java:284)
	at com._1c.g5.aef2.internal.RunnableQueue.queueAndWait(RunnableQueue.java:103)
	at com._1c.g5.aef2.engines.EngineFactory$WrappingRunnableQueue.queueAndWait(EngineFactory.java:107)
	at com._1c.g5.aef2.engines.Engine.queueAndWaitRunnable(Engine.java:104)
	at com._1c.g5.aef2.components.Component.queueAndWaitEvent(Component.java:260)
	at com._1c.g5.aef2.views.View.queueAndWaitEvent(View.java:256)
	at com._1c.g5.aef2.standard.lwt.views.LwtLinkView.access$2(LwtLinkView.java:1)
	at com._1c.g5.aef2.standard.lwt.views.LwtLinkView$1.linkActivated(LwtLinkView.java:37)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:215)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:309)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.lambda$3(AbstractHyperlink.java:117)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
`

**Comment by MaksimDzyuba** [comment]
Здравствуйте, ошибку подтверждаю, будем чинить, для обхода проблема, просьба загрузить схему через конфигуратор, а потом импортировать в edt

**Comment by vl-sher** [comment]
Невозможно импортировать - при обновлении конфы с такой ссылкой,
загруженной через конфигуратор, даёт ту же ошибку, потому что в схеме
ссылки на внешние ресурсы.

**Comment by MaksimDzyuba** [comment]
я что-то не понял, я зашел в конфигуратор, создал там новую ссылку с этим урлом, а потом импортировал все обратно в edt
![image](https://user-images.githubusercontent.com/77277424/186713709-d2a9202c-4aa5-4126-88ee-bb4db64da9b6.png)
можно чуть подробнее, что Вы делали?

**Comment by vl-sher** [comment]
Зашел в конфигуратор, создал там новую ссылку с этим урлом, а потом импортировал все обратно в edt. А после этого нажал Обновить приложение и получил ошибку 
![image](https://user-images.githubusercontent.com/1232534/186725779-bc66a920-36e6-4247-b3e1-63d403fccfa9.png)
и в логе 
!ENTRY com._1c.g5.v8.dt.platform.services.ui 4 0 2022-08-25 19:58:12.002
!MESSAGE Произошла внутренняя ошибка
!STACK 0
com.e1c.g5.dt.applications.ApplicationException: Ошибка исполнения 1С:Предприятия
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationBehaviourDelegate.publish(InfobaseApplicationBehaviourDelegate.java:109)
	at com.e1c.g5.dt.internal.applications.ApplicationManager.publish(ApplicationManager.java:275)
	at com.e1c.g5.dt.applications.IApplicationManager$pbryglu.publish(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployConfiguration(DeployConfigurationWizard.java:569)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.deployExistingApplications(DeployConfigurationWizard.java:210)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.deploy.DeployConfigurationWizard.lambda$0(DeployConfigurationWizard.java:163)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: com._1c.g5.v8.dt.platform.services.core.infobases.sync.InfobaseSynchronizationException: Ошибка исполнения 1С:Предприятия
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:294)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.loadConfiguration(ParticipantAwareInfobaseConnection.java:89)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.loadConfiguration(ReconnectableInfobaseConnection.java:142)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.strategies.OnDemandSynchronizationStrategy.infobaseDatabaseUpdateRequested(OnDemandSynchronizationStrategy.java:104)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.updateConnectedInfobase(InfobaseSynchronization.java:609)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.updateInfobase(InfobaseSynchronizationManager.java:257)
	at com._1c.g5.v8.dt.platform.services.core.infobases.sync.IInfobaseSynchronizationManager$pbryglu.updateInfobase(Unknown Source)
	at com.e1c.g5.dt.internal.applications.infobases.ui.InfobaseApplicationBehaviourDelegate.publish(InfobaseApplicationBehaviourDelegate.java:85)
	... 6 more
Caused by: com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeCoreException: Ошибка взаимодействия с платформой 1С:Предприятия 8.3.19.1467:
Операция конфигурирования завершена неуспешно
Ошибка загрузки/выгрузки конфигурации
Ошибка импорта схемы 
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:112)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.execInDesignerSession(DesignerSessionThickClientLauncher.java:933)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.importConfigurationFromXml(DesignerSessionThickClientLauncher.java:372)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.AbstractInfobaseConnection.loadConfiguration(AbstractInfobaseConnection.java:263)
	... 13 more
Caused by: com._1c.g5.designer.ssh.client.ConfigurationLoadException: Ошибка загрузки/выгрузки конфигурации
	at com._1c.g5.internal.designer.ssh.client.operation.LoadFilesQuery.processExecutionResponses(LoadFilesQuery.java:92)
	at com._1c.g5.internal.designer.ssh.client.operation.LoadFilesQuery.processExecutionResponses(LoadFilesQuery.java:43)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.execute(AbstractQuery.java:134)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractQuery.exec(AbstractQuery.java:85)
	at com._1c.g5.internal.designer.ssh.client.operation.AbstractTransferingQuery.callOperation(AbstractTransferingQuery.java:104)
	at com._1c.g5.internal.designer.ssh.client.operation.TransferingLoadFilesQuery.exec(TransferingLoadFilesQuery.java:54)
	at com._1c.g5.internal.designer.ssh.client.operation.TransferingLoadFilesQuery.exec(TransferingLoadFilesQuery.java:30)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.lambda$7(DesignerSessionThickClientLauncher.java:416)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execInDesignerSession(DesignerSessionOperationSupport.java:95)
	... 16 more

**Comment by MaksimDzyuba** [comment]
а можно полные логи прислать, пожалуйста, пока не понятно, что именно ему не нравится. Попробовал Ваш сценарий, все ок прошло, так что жду логи

**Comment by vl-sher** [comment]
Исходную конфу приложил в зипе. Дальше по шагам (с этого начинается лог):
- Приложение/Запустить конфигуратор
- в нем:
- - добавляем ссылку
- - сертификаты не предоставляем и не проверяем
- - обновляем конфигурацию, закрываем конфигуратор
- в EDT Приложение/Обновить конфигурацию
- окно изменения конфигурации
Новый объект: WSReference.WSСсылка1
Новый объект: WSReference.WSСсылка1.WSDefinition
Объект изменен: Configuration.Minitest
- Импортировать 
- Сопоставление по UID - OK
- видим новую ссылку - Объединить
- Запустить процедуру объединения - Да
- Приложение Minitest - Обновить конфигурацию - Готово
![image](https://user-images.githubusercontent.com/1232534/186732292-c24deefc-4a8a-4863-abfb-bb66245be027.png)

[minitest_update.log](https://github.com/1C-Company/1c-edt-issues/files/9427080/minitest_update.log)
[Minitest.zip](https://github.com/1C-Company/1c-edt-issues/files/9427082/Minitest.zip)

**Comment by vl-sher** [comment]
Если удалить импортированную ссылку в EDT, а потом обновить конфу - все работает.

**Comment by vl-sher** [comment]
@MaksimDzyuba сорри, ссылка ЦБ работает нормально (в ней нет внешних ссылок), проблемы с 
http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl
Или с файлом из https://github.com/1C-Company/1c-edt-issues/issues/609#issuecomment-1222078018

**Comment by MaksimDzyuba** [comment]
да, понял теперь сценарий, спасибо, ошибку будем править

**Comment by MaksimDzyuba** [comment]
исправили, исправление будет в ближайшей исправительной версии
