### ISSUE TITLE
Ошибка сравнения конфигураций при добавлении формы плана обмена

### ISSUE THREAD

**Issue by tormozit** [1C-Company/1c-edt-issues#653]
### Описание ошибки

Ошибка сравнения конфигураций при добавлении формы плана обмена:
Ошибка сравнения узла <MAIN: null; OTHER: 'ExchangePlan.ОбменSCAP.Form.ФормаСписка.Form'>
Платформа 8.3.21

### Как воспроизвести

1. Восстановить базу из приложенной выгрузки
2. Импортировать проект конфигурации из этой базы
3. Добавить в конфигураторе 1С план обмена путем копирования любого существующего в ней.
4. Импортировать изменения конфигурации из базы в проект EDT
5. Возникнет ошибка сравнения конфигураций

### Скриншоты

![изображение](https://user-images.githubusercontent.com/11896251/190658292-9405a6ae-237b-4453-a9b8-b0dfee22b20a.png)

### Ожидаемое поведение

Отсутствие ошибки

### Лог рабочей области

java.lang.NullPointerException
	at com._1c.g5.v8.dt.internal.form.compare.FormComparisonParticipant.isExcludedFromComparison(FormComparisonParticipant.java:807)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.computeClassFeatures(AbstractEmfBasedComparisonParticipant.java:3296)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.lambda$0(AbstractEmfBasedComparisonParticipant.java:346)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.getClassFeatures(AbstractEmfBasedComparisonParticipant.java:345)
	at com._1c.g5.v8.dt.internal.form.compare.FormComparisonParticipant.getClassFeatures(FormComparisonParticipant.java:1097)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.compareEmfObject(AbstractEmfBasedComparisonParticipant.java:702)
	at com._1c.g5.v8.dt.md.compare.participant.AbstractMdAwareComparisonParticipant.compareEmfObject(AbstractMdAwareComparisonParticipant.java:218)
	at com._1c.g5.v8.dt.internal.form.compare.FormComparisonParticipant.compareEmfObject(FormComparisonParticipant.java:964)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.compareManyContainmentChildObjects(AbstractEmfBasedComparisonParticipant.java:2183)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.compareManyContainment(AbstractEmfBasedComparisonParticipant.java:2113)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.compareEmfContainment(AbstractEmfBasedComparisonParticipant.java:593)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.compareOneSideObject(AbstractEmfBasedComparisonParticipant.java:802)
	at com._1c.g5.v8.dt.compare.participant.AbstractEmfBasedComparisonParticipant.compareEmfObject(AbstractEmfBasedComparisonParticipant.java:731)
	at com._1c.g5.v8.dt.md.compare.participant.AbstractMdAwareComparisonParticipant.compareEmfObject(AbstractMdAwareComparisonParticipant.java:218)
	at com._1c.g5.v8.dt.internal.form.compare.FormComparisonParticipant.compareEmfObject(FormComparisonParticipant.java:964)
	at com._1c.g5.v8.dt.internal.form.compare.FormComparisonParticipant.compare(FormComparisonParticipant.java:402)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.lambda$0(ComparisonManager.java:389)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager$14.execute(ComparisonManager.java:3236)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:706)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:667)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:154)
	at com._1c.g5.v8.bm.integration.internal.BmModel.execute(BmModel.java:209)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.runComparisonTreeBmModelTask(ComparisonManager.java:998)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.runCompareNodeTask(ComparisonManager.java:3226)
	at com._1c.g5.v8.dt.internal.compare.ComparisonManager.compare(ComparisonManager.java:375)
	at com._1c.g5.v8.dt.internal.compare.queue.ComparisonQueueProcessor.compare(ComparisonQueueProcessor.java:85)
	at com._1c.g5.v8.dt.internal.compare.queue.ComparisonExecutor.run(ComparisonExecutor.java:116)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

[1Cv8.zip](https://github.com/1C-Company/1c-edt-issues/files/9584779/1Cv8.zip)

**Comment by tormozit** [comment]
Аналогичная проблема с документом в чистой базе
[1Cv8 документ.zip](https://github.com/1C-Company/1c-edt-issues/files/9585010/1Cv8.zip)

**Comment by tormozit** [comment]
В исходной ситуации, где ошибка эта возникала при сравнении двух проектов, удалось ее обойти путем добавления проблемных объектов в конфигурацию-источник перед сравнением.

**Comment by AlmazNasibullin** [comment]
@tormozit 
Добрый день.

На версии EDT 2022.1.2 ошибка не воспроизводится, как в первом сценарии, так и во втором. Можете, пожалуйста, проверить у себя эти сценарии на версии 2022.1.2?

**Comment by tormozit** [comment]
А вы проверьте на 2021.3.4 . Если там воспроизведется, то значит уже исправили. Иначе будет смысл мне снова проверять.

**Comment by AlmazNasibullin** [comment]
@tormozit 
Проверил, на версии 2021.3.4 проблема тоже не воспроизводится.

**Comment by AlmazNasibullin** [comment]
@tormozit 
Добрый день. Подскажите, пожалуйста, вам удалось проверить сценарий из задачи на версии 2022.1?

**Comment by AlmazNasibullin** [comment]
Закрываю задачу, поскольку не удалось воспроизвести проблему.
