### ISSUE TITLE
Не работает "Войти с помощью портала ИТС"

### ISSUE THREAD

**Issue by unichkin** [1C-Company/1c-edt-issues#768]
### Описание ошибки

Нужно добавить новый проект. При этом возникает окно авторизации, но ИТС по кнопке не открывается. Не могу авторизоваться, соответственно не могу добавить проект, работа заблокирована.

### Как воспроизвести

Описано

### Скриншоты

![image](https://user-images.githubusercontent.com/10799597/202680141-1cdf73e3-64fb-4cfc-a435-252f8beb8a69.png)

Закрываю это окно, и далее не могу указать тип проекта для создания:

![image](https://user-images.githubusercontent.com/10799597/202680957-dfbbd667-acf4-4a9f-a562-dab32c2502a5.png)

### Ожидаемое поведение

Лучше вообще необходимость авторизации убрать. 

### Лог рабочей области

-

### Версия 1С:EDT

Ruby 2021.3.4

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support

**Comment by Kellendros007** [comment]
В Linux(Ubuntu) наблюдается аналогичная проблема. (Так же и на машине с Windows 10)
Так же невозможно обновить EDT из Start'ера

Аналогичная проблема при запуске EDT
![image](https://user-images.githubusercontent.com/32325196/202929475-719ed355-54e4-40bc-a60a-d656025d92b6.png)

(P.s. возможно как то связано с установкой рядом платформы версии 8.3.21.1622 или исправлением бага который связан с форсированием обновления некоторых версий, которые должны были перестать работать с какой то даты.)

**Comment by vadimeg** [comment]
@unichkin [unichkin](https://github.com/) Добрый день! Проблема еще воспроизводится?

**Comment by unichkin** [comment]
Добрый день. В виду того что технически проблема была в упавшем сайте ИТС - нет, на тек. день не воспроизводится. Но я считаю это следует концептуально решать на уровне EDT. Система должна отрабатывать подобные нештатные ситуации.
Зачем ему вообще нужна эта авторизация? Видимо, чтобы опрашивать  некие статусы обновлений. 
Ну так давайте сделаем ping - если доступны нужные ресурсы, поведение не меняется.
Если не доступны - система все-равно должна позволить работать в локальном режиме. 
Возможно стоит добавить глобальную опцию в EDT старт - типа "Проверять доступность ИТС". Чтобы пользователь мог ее выключить и работать себе оффлайн спокойно. 
Некогда было уведомление что EDT весь бесплатный, и регистрации на ИТС для своей работы не требует. А выходит что требует.

**Comment by dmitryklinyshev** [comment]
Проблема все еще актуальна. Win 10. Шаги воспроизведения аналогичны.

**Comment by NikitaLysenkoA** [comment]
Проблема актуальна на Win 10.
В логах ошибка: 
```
2024-02-13 11:01:54 [starter-suspendableJobScheduler-thread-0] INFO  c.e.g.d.c.i.s.h.Java11HttpClientProxy - Application uses User-Agent=1C:EDT Start/0.7.0.180 (Windows 10; 10.0; amd64) JAVA (BellSoft; 11.0.15+10-LTS), Accept-Language=ru
2024-02-13 11:01:55 [starter-networkJobExecutor-thread-1] INFO  c.e.g.d.c.l.a.impl.MonitoringManager - 1C:Pult service host is https://pult.1c.ru/. Statistic collection is enabled.
2024-02-13 11:01:55 [starter-applicationJobExecutor-thread-0] INFO  c.e.g.d.c.i.a.c.core.AuthClientImpl - Access token is not present. Authenticate to obtain one.
2024-02-13 11:01:55 [EventAdmin Async Event Dispatcher Thread] WARN  c.e.g.d.c.l.a.c.LauncherController - The application has offline status.
2024-02-13 11:01:55 [starter-networkJobExecutor-thread-0] INFO  c.e.g.d.c.i.a.c.core.AuthClientImpl - Access token is not present. Authenticate to obtain one.
2024-02-13 11:01:55 [ForkJoinPool.commonPool-worker-3] ERROR c.e.g.d.c.l.r.NotificationRepository - javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
java.util.concurrent.CompletionException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.stopOnError(SSLFlowDelegate.java:934)
```

**Comment by Zorbotron** [comment]
Проблема актуальная, как решить пока не понятно 
![image](https://github.com/1C-Company/1c-edt-issues/assets/130638908/83bf5279-a27e-4795-b23e-4027e01524aa)

**Comment by airaketa** [comment]
@NikitaLysenkoA судя по логу ошибки, проблема с проверкой сертификатов.
возможно, поможет вот этот ответ https://github.com/1C-Company/1c-edt-issues/issues/1012#issuecomment-1576836622

**Comment by airaketa** [comment]
@unichkin надпись "отсутствует подключение к сервису" на приложенном скриншоте говорит о том, что не было доступа к сервисам  1C:EDT Start (сервисы, с которых 1C:EDT Start скачивает версии EDT при установке и обновлении, независимые от Портала 1С:ИТС)
то есть проблема могла быть более широкой (недоступен был и Портал и сервисы 1C:EDT Start), либо были недоступны только сервисы 1C:EDT Start
при отсутствии лога сложно сказать о причине недоступности, но общие советы диагностики описаны в этой ветке
https://github.com/1C-Company/1c-edt-issues/issues/1012#issuecomment-1579061871 - при диагностике ошибки можно ориентироваться на URL https://services.1c.dev/setups/v1 (попробовать открыть в браузере)

при недоступности сервисов 1C:EDT Start или Портала установить новые версии EDT или обновить уже установленные не получится, но создавать и запускать проекты на уже установленных версиях (или установленных с помощью offline-дистрибутива) ничего не мешает
