### ISSUE TITLE
Ошибка "Процесс не может получить доступ к файлу, так как этот файл занят другим процессом" при импорте расширения из базы

### ISSUE THREAD

**Issue by MoVled** [1C-Company/1c-edt-issues#794]
### Описание ошибки

При импорте из базы данных расширения происходит ошибка:

java.lang.reflect.InvocationTargetException
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportExtensionsWizard.lambda$1(ImportExtensionsWizard.java:257)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.RuntimeOperationSupport.execRuntimeOperation(RuntimeOperationSupport.java:96)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportExtensionsWizard.importExtensions(ImportExtensionsWizard.java:241)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportExtensionsWizard.lambda$0(ImportExtensionsWizard.java:117)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.core.runtime.CoreException: Каталог проекта "СППР__для_проекта_EDT.рарусДоработки" уже существует
	at com._1c.g5.v8.dt.internal.core.platform.AbstractDependentProjectManager.create(AbstractDependentProjectManager.java:284)
	at com._1c.g5.v8.dt.internal.core.platform.AbstractDependentProjectManager.create(AbstractDependentProjectManager.java:246)
	at com._1c.g5.v8.dt.internal.core.platform.ExtensionProjectManager.create(ExtensionProjectManager.java:145)
	at com._1c.g5.v8.dt.core.platform.IExtensionProjectManager$pbryglu.create(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.AbstractImportWizard.importExtension(AbstractImportWizard.java:233)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases._import.ImportExtensionsWizard.lambda$1(ImportExtensionsWizard.java:250)
	... 4 more

### Как воспроизвести

1. В списке "Информационные базы", контекстное меню "Импортировать расширения"
2. Указать базовый проект, выбрать расширение, нажать "Готово"

### Скриншоты

![image](https://user-images.githubusercontent.com/90936490/207307654-1f4bc8ee-0e5b-4b27-91c8-ec51f3cf442e.png)

### Ожидаемое поведение

Расширение должно было импортироваться в проект

### Лог рабочей области

[ — копия.log](https://github.com/1C-Company/1c-edt-issues/files/10217452/default.log)
[trace.log](https://github.com/1C-Company/1c-edt-issues/files/10217453/trace.log)

### Версия 1С:EDT

Ruby 2022.1.3

### Операционная система

Windows

### Установленные плагины

Нет плагинов

### Дополнительная информация

платформа 8.3.21.1624

Импортировать пытаюсь расширение к типовой СППР (режим совместимости Версия 8.3.17). Причём, пустое расширение импортируется нормально. Сама конфигурация, без расширения, тоже импортируется.

**Comment by vadimeg** [comment]
Добрый день,
В логе ошибка
C:\Users\MAKOLE~1.RAR\AppData\Local\Temp\1cedt\xml-import-79293\xml.zip: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом

Какой-то процесс держит файл импорта.
И еще:
Каталог проекта "СППР__для_проекта_EDT.рарусДоработки" уже существует
Похоже, что после неудачной попытки импортирования каталог с проектом создался.
Попробуйте на чистом воркспейсе сделать импорт из ИБ. Там в диалоге импорта сразу можно указать какие расширения импортировать, если они есть в базе.

**Comment by MoVled** [comment]
Добрый день!
Ошибка изначально проявилась у коллеги. Я попробовал развернуть чистый проект и импортировать конфигурацию и расширение - ошибка повторилась и у меня. Скорее всего, в логах вы видите существующий проект, т.к. я пробовал запустить импорт повторно.
Т.е. рекомендация `Попробуйте на чистом воркспейсе сделать импорт из ИБ` выполнена изначально. Да, если в диалоге импорта не выбрать расширение, то сама конфигурация импортируется нормально

**Comment by vadimeg** [comment]
> Да, если в диалоге импорта не выбрать расширение, то сама конфигурация импортируется нормально
А если на чистом воркспейсе запустить импорт не расширений, а импорт конфигурации и в диалоге в списке расширений не отключать проект-расширение, то импорт тоже не пройдет?

![image](https://user-images.githubusercontent.com/17178862/208731559-7ba48b8e-b3c1-4867-9811-60707d2326e5.png)

**Comment by MoVled** [comment]
> А если на чистом воркспейсе запустить импорт не расширений, а импорт конфигурации и в диалоге в списке расширений не отключать проект-расширение, то импорт тоже не пройдет?
Именно так и делали.
Сейчас вопрос можно закрыть: на последней версии EDT ошибка не воспроизводится. Спасибо!
