### ISSUE TITLE
The object has been processed

### ISSUE THREAD

**Issue by AndreyDanilov-nn** [1C-Company/1c-edt-issues#812]
### Описание ошибки

При удалении объектов метаданных, периодически вылетает ошибка `The object has been processed`. При этом удаляется только файл `*.mdo` у объекта. Остальные папки/файлы объекта остаются. Из Configuration.mdo, подсистем, ролей и т.п. удаление не происходит.

### Как воспроизвести
Удалить например обработку/документ/справочник.  
При открытии мастера `Удаление объекта` появляется ошибка `The object has been processed`. Если продолжить удаление, то удалится только `*.mdo`

Хз какие условия, что бы стабильно воспроизвести

### Скриншоты

![image](https://user-images.githubusercontent.com/53249626/209531582-ae2ad3ca-f632-40b5-ba36-db06f4ca2160.png)

### Ожидаемое поведение

Объект удаляется корректно

### Лог рабочей области
```
java.lang.IllegalStateException: The object has been processed
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectDeleteVisitorCallback.saveReferences(BmObjectDeleteVisitorCallback.java:371)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectDeleteVisitorCallback.processReferences(BmObjectDeleteVisitorCallback.java:214)
	at com._1c.g5.v8.dt.core.findref.AbstractBmReferencesCollectorVisitorCallback.visit(AbstractBmReferencesCollectorVisitorCallback.java:74)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectDeleteVisitorCallback.visit(BmObjectDeleteVisitorCallback.java:104)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectVisitor.visit(BmObjectVisitor.java:100)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectVisitor.visit(BmObjectVisitor.java:121)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectVisitor.visit(BmObjectVisitor.java:121)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectVisitor$VisitorTask.execute(BmObjectVisitor.java:172)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectVisitor$VisitorTask.execute(BmObjectVisitor.java:1)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:757)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:700)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeReadOnlyTask(Reactor.java:146)
	at com._1c.g5.v8.bm.integration.internal.BmModel.executeReadonlyTask(BmModel.java:227)
	at com._1c.g5.v8.bm.integration.internal.BmModel.executeReadonlyTask(BmModel.java:221)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectVisitor.visit(BmObjectVisitor.java:69)
	at com._1c.g5.v8.dt.internal.refactoring.core.RefactoringService.initiateDelete(RefactoringService.java:121)
	at com._1c.g5.v8.dt.refactoring.core.IRefactoringService$pbryglu.initiateDelete(Unknown Source)
	at com._1c.g5.v8.dt.internal.md.refactoring.MdRefactoringService.createMdObjectDeleteRefactoring(MdRefactoringService.java:118)
	at com._1c.g5.v8.dt.md.refactoring.IMdRefactoringService$pbryglu.createMdObjectDeleteRefactoring(Unknown Source)
	at com._1c.g5.v8.dt.internal.md.ui.handlers.MdObjectDeleteHandler.lambda$1(MdObjectDeleteHandler.java:62)
	at com._1c.g5.v8.dt.refactoring.ui.RefactoringUIHelper.lambda$4(RefactoringUIHelper.java:129)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

### Версия 1С:EDT

2022.1.2

### Операционная система

Windows

### Установленные плагины

1C:Code style V8, 1C:SSL-support, Другие сторонние плагины `  BSL LS connector for EDT 0.2.1.20201211-0307`,   `Disable Editing plugin for 1C:EDT 0.4.0.20220617-0924`

### Дополнительная информация

8.3.21.1484

**Comment by Jimmo910** [comment]
У меня в логе возникает вот такая ошибка.
версия 2022.2.4

```
!ENTRY com._1c.g5.v8.dt.refactoring.core 4 0 2023-03-09 14:11:44.671
!MESSAGE null argument:
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at com._1c.g5.v8.dt.internal.dcs.refactoring.DcsDeleteRefactoringContributor.createParticipatingOperation(DcsDeleteRefactoringContributor.java:52)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectDeleteVisitorCallback.visit(BmObjectDeleteVisitorCallback.java:114)
	at com._1c.g5.v8.dt.core.model.EObjectVisitor.visit(EObjectVisitor.java:71)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectVisitor.visit(BmObjectVisitor.java:93)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectVisitor.visit(BmObjectVisitor.java:78)
	at com._1c.g5.v8.dt.internal.refactoring.core.BmObjectVisitor.visit(BmObjectVisitor.java:78)
	at com._1c.g5.v8.dt.internal.refactoring.core.RefactoringService.initiateDelete(RefactoringService.java:121)
	at com._1c.g5.v8.dt.refactoring.core.IRefactoringService$pbryglu.initiateDelete(Unknown Source)
	at com._1c.g5.v8.dt.internal.md.refactoring.MdRefactoringService.createMdObjectDeleteRefactoring(MdRefactoringService.java:119)
	at com._1c.g5.v8.dt.md.refactoring.core.IMdRefactoringService$pbryglu.createMdObjectDeleteRefactoring(Unknown Source)
	at com._1c.g5.v8.dt.internal.md.ui.handlers.MdObjectDeleteHandler.lambda$1(MdObjectDeleteHandler.java:68)
	at com._1c.g5.v8.dt.refactoring.ui.RefactoringUIHelper.lambda$4(RefactoringUIHelper.java:130)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY com._1c.g5.v8.dt.core 4 0 2023-03-09 14:11:47.321
!MESSAGE NullPointerException
!STACK 0
java.lang.NullPointerException
	at com._1c.g5.v8.dt.form.service.FormUtil.collectFormItems(FormUtil.java:552)
	at com._1c.g5.v8.dt.internal.form.service.extension.FormExtensionService.updateExportedFormElements(FormExtensionService.java:1049)
	at com._1c.g5.v8.dt.internal.form.service.extension.FormExtensionService.filterExtensionBelongingObject(FormExtensionService.java:209)
	at com._1c.g5.v8.dt.internal.form.resource.FormExporter.cloneObject(FormExporter.java:135)
	at com._1c.g5.v8.dt.core.provider.BasicBmObjectExporter$1.execute(BasicBmObjectExporter.java:107)
	at com._1c.g5.v8.dt.core.provider.BasicBmObjectExporter$1.execute(BasicBmObjectExporter.java:1)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:757)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:700)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeReadOnlyTask(Reactor.java:146)
	at com._1c.g5.v8.bm.integration.internal.BmModel.executeReadonlyTask(BmModel.java:227)
	at com._1c.g5.v8.bm.integration.internal.BmModel.executeReadonlyTask(BmModel.java:221)
	at com._1c.g5.v8.dt.core.provider.BasicBmObjectExporter.export(BasicBmObjectExporter.java:102)
	at com._1c.g5.v8.dt.internal.core.platform.bm.ProjectSynchronizationManager.lambda$1(ProjectSynchronizationManager.java:448)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2315)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2340)
	at com._1c.g5.v8.dt.internal.core.platform.bm.ProjectSynchronizationManager.saveInternal(ProjectSynchronizationManager.java:435)
	at com._1c.g5.v8.dt.internal.core.platform.bm.ProjectSynchronizationManager.processSaveTasks(ProjectSynchronizationManager.java:186)
	at com._1c.g5.v8.dt.internal.core.platform.bm.SynchronizationManager$ExportChangesJob.run(SynchronizationManager.java:951)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by AndreyDanilov-nn** [comment]
https://t.me/e1c_edt/67873

исправлено в 2022.2.5
