### ISSUE TITLE
Не выполняется конвертация из EDT в xml на версии 2022.1.5

### ISSUE THREAD

**Issue by vanleo85** [1C-Company/1c-edt-issues#876]
### Описание ошибки

Конвертация из EDT в xml через "ring edt workspace export" зависает и не возвращает никакого результата.
Проблема возникла 7-10 февраля, до этого в течение нескольких месяцев конвертация работала стабильно.
Зависание происходит 3-4 раза из 5 попыток, на Linux Ubuntu 20.04 и на Windows Server 2016.
Конвертация выполняется командой в режиме CI:
ring edt workspace export --workspace-location /tmp --project $PWD --configuration-files $PWD/out/xml

Наблюдается тенденция: если в течение 1-2 минут конвертация не завершается, то очень велика вероятность, что она зависла.
До возникновения этой проблемы конвертация могла выполняться успешно за 4-5 минут.

### Как воспроизвести

1. Перейти в командную строку и в контексте каталога с проектом EDT запустить команду конвертации
ring edt workspace export --workspace-location /tmp --project $PWD --configuration-files $PWD/out/xml

2. Появится лог выполнения команды, команда зависает
<img width="485" alt="image" src="https://user-images.githubusercontent.com/33088229/219348331-616986c5-ca15-42f9-ac0f-40f84ccfe7b7.png">

### Ожидаемое поведение

<img width="485" alt="image" src="https://user-images.githubusercontent.com/33088229/219348565-1b77ea2f-56ad-44c9-ae85-f797ff682a30.png">

### Лог рабочей области

!SESSION 2023-02-16 13:36:33.365 -----------------------------------------------
eclipse.buildId=2022.1.5.13
java.version=11.0.17
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=ru_RU

!ENTRY com._1c.g5.v8.dt.core 1 0 2023-02-16 13:36:33.375
!MESSAGE java.vm.name=OpenJDK 64-Bit Server VM

!ENTRY com._1c.g5.v8.dt.core 1 0 2023-02-16 13:36:33.449
!MESSAGE java.vm.info=mixed mode, sharing

!ENTRY com._1c.g5.v8.dt.platform.services.core 1 0 2023-02-16 13:36:33.936
!MESSAGE Trying to re-establish all non-closed SSH connecton...

!ENTRY com._1c.g5.v8.dt.core 1 0 2023-02-16 13:36:40.276
!MESSAGE Project context is being started: bb-mobile (CLEAN_IMPORT)

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.428
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.429
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.429
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.429
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.429
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.429
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.430
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.430
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.430
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.431
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:40.431
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.182
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.182
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.182
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.182
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.182
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.183
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.183
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.183
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.183
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.183
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.183
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.183
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.183
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.184
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.184
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.184
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.190
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.check.qfix.components.SingleVariantModelBasicFix$SingleVariantModelFixChangeProcessor for the change type class com.e1c.g5.v8.dt.check.qfix.components.SingleVariantModelBasicFix$SingleVariantModelFixChange which is already served by the processor com.e1c.g5.v8.dt.check.qfix.components.SingleVariantModelBasicFix$SingleVariantModelFixChangeProcessor@52054121

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.191
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.191
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.192
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.192
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.193
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.195
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.195
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.v8.dt.check 1 0 2023-02-16 13:36:41.195
!MESSAGE The attempt to change processor class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor for the change type class com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChange which is already served by the processor com.e1c.g5.v8.dt.bsl.check.qfix.SingleVariantXtextBslModuleFix$SingleVariantModuleFixChangeProcessor@39bee397

!ENTRY com.e1c.g5.dt.applications.infobases.ui 4 0 2023-02-16 13:36:46.141
!MESSAGE Skipping the lifecycle event because workbench is not running

!ENTRY com._1c.g5.v8.dt.core 1 0 2023-02-16 13:36:46.469
!MESSAGE Project context is started: bb-mobile

!ENTRY org.eclipse.core.jobs 4 2 2023-02-16 13:37:11.059
!MESSAGE Произошла внутренняя ошибка: "Импорт ресурсов проекта: bb-mobile".
!STACK 0
com._1c.g5.wiring.ServiceUnavailableException: org.ops4j.peaberry.ServiceUnavailableException: java.lang.IllegalStateException: Контекст комплекта больше не действителен com._1c.g5.v8.dt.binary.ui_2.0.2400.v202301130934 [58]
	at com._1c.g5.internal.wiring.ConfigurableImportDecorator$ConfigurableImport.get(ConfigurableImportDecorator.java:101)
	at org.ops4j.peaberry.util.DelegatingImport.get(DelegatingImport.java:44)
	at org.ops4j.peaberry.util.decorators.StickyDecorator$StickyImport.get(StickyDecorator.java:81)
	at com._1c.g5.v8.dt.core.filesystem.IQualifiedNameFilePathConverter$pbryglu.getFqn(Unknown Source)
	at com._1c.g5.v8.dt.core.provider.BaseSingleResourceObjectImporter.resolveFqn(BaseSingleResourceObjectImporter.java:94)
	at com._1c.g5.v8.dt.core.provider.BaseSingleResourceObjectImporter.createTasks(BaseSingleResourceObjectImporter.java:51)
	at com._1c.g5.v8.dt.internal.core.platform.bm.ProjectSynchronizationManager.executeImport(ProjectSynchronizationManager.java:1009)
	at com._1c.g5.v8.dt.internal.core.platform.bm.ProjectSynchronizationManager.importPendingChanges(ProjectSynchronizationManager.java:351)
	at com._1c.g5.v8.dt.internal.core.platform.bm.SynchronizationManager$ImportChangesJob.doRun(SynchronizationManager.java:1013)
	at com._1c.g5.v8.dt.internal.core.platform.bm.SynchronizationManager$ImportChangesJob.run(SynchronizationManager.java:999)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.ops4j.peaberry.ServiceUnavailableException: java.lang.IllegalStateException: Контекст комплекта больше не действителен com._1c.g5.v8.dt.binary.ui_2.0.2400.v202301130934 [58]
	at org.ops4j.peaberry.cache.AbstractServiceImport.get(AbstractServiceImport.java:74)
	at org.ops4j.peaberry.internal.ConcurrentImport.get(ConcurrentImport.java:57)
	at org.ops4j.peaberry.util.DelegatingImport.get(DelegatingImport.java:44)
	at com._1c.g5.internal.wiring.ConfigurableImportDecorator$ConfigurableImport.get(ConfigurableImportDecorator.java:73)
	... 10 more
Caused by: java.lang.IllegalStateException: Контекст комплекта больше не действителен com._1c.g5.v8.dt.binary.ui_2.0.2400.v202301130934 [58]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:1026)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:651)
	at org.ops4j.peaberry.osgi.OSGiServiceImport.acquireService(OSGiServiceImport.java:60)
	at org.ops4j.peaberry.cache.AbstractServiceImport.get(AbstractServiceImport.java:72)
	... 13 more

### Версия 1С:EDT

2022.1.5+13-x86_64

### Операционная система

Windows, Linux

### Установленные плагины

Нет плагинов

**Comment by fenixnow** [comment]
Если мы будем нужны, мы всегда онлайн - телеграмм @fenixnow @Van1eo

**Comment by MaksimDzyuba** [comment]
Здравствуйте, похоже на то, что у Вас как что-то случилось с установкой EDT, рекомендую, затереть все имеющиеся и поставить заново. Может Вы пробовали устанавливать версии старше или младше?
Кроме того, если опять зависнет,то просьба снять дамп файл

**Comment by vanleo85** [comment]
Проблема повторяется на любой из перечисленных версий EDT: 2021.3.4, 2022.1.3, 2022.1.5
На другом проекте конвертация на этих версиях выполняется корректно.
Проблема с конвертацией на "проблемном" проекте возникла недавно, до этого в течение нескольких месяцев конвертация выполнялась успешно.

**Comment by MaksimDzyuba** [comment]
а сам проект не могли бы предоставить?

**Comment by fenixnow** [comment]
> а сам проект не могли бы предоставить?

Максим, подскажите, как найти вас в телеграм? Или напишите мне @fenixnow - ник в телеграм, я предоставлю или архив проекта или ссылку, как будет удобнее

**Comment by vanleo85** [comment]
@MaksimDzyuba Threaddump и Memorydump выложил в облако - https://disk.yandex.ru/d/C9yGxQL5NDtnTg

**Comment by KalyakinAG** [comment]
попробуйте выполнить конвертацию с использованием 1cedtcli
