### ISSUE TITLE
Защищенное хранилище на macOS

### ISSUE THREAD

**Issue by Jimmo910** [1C-Company/1c-edt-issues#943]
### Описание ошибки

Ошибка в том что, постоянно приходится удалять "Защищенное хранилище" при запуске другого проекта. Так как ЕДТ почему то забывает логин\пароль от базы.
Все базы используются ДЕМО (ЕРП/КА/УТ). т.е. во всех использую одного пользователя admin без пароля.

### Как воспроизвести

1. Перейдите на MacOS (у меня версия 12.5)
2. Разверните 3 ДЕМО базы которые поставляются в полном Дистрибутиве 1С. ЕРП КА и УТ (последнии версии)
3. Создайте проект из ЕРП. введя логин от базы admin без пароля
4. После развертываения закройте проект ЕРП.
5. Создайте новый проект используя базу КА.
6. При вводе логин и пароля от базу используйте тот же admin без пароля.
7. Тут он вроде как не напишет ошибку, а может и напишет я щас уже не помню.
8. Далее нажимая на кнопку Импартировать. Он сново попросит пароль от базы. Вы введете, и он уже точно напишет ошибку авторизации.

### Ожидаемое поведение

одиновый лог\пас от разных баз на macOS - должны работать в ЕДТ.

### Лог рабочей области

[1.log — копия](https://github.com/1C-Company/1c-edt-issues/files/11135435/1.log)
лог не с этого сценария воспроизведения.
в этом логе ошибка импорта внешней обработки - из-за того что конфигуратор не может ЕДТ запустить, якобы лог пас не подходят.

### Версия 1С:EDT

2022.2.5

### Операционная система

macOS

### Дополнительная информация

MasOS - 12.5

**Comment by Jimmi910** [comment]
!ENTRY com._1c.g5.v8.dt.platform.services.core 4 0 2023-04-07 09:44:59.186
!MESSAGE Ошибка сохранения во внутреннее хранилище
!STACK 0
org.eclipse.equinox.security.storage.StorageException: No password provided.
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getModulePassword(SecurePreferencesRoot.java:311)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getPassword(SecurePreferencesRoot.java:230)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.put(SecurePreferences.java:229)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesWrapper.put(SecurePreferencesWrapper.java:128)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.InfobaseAccessManager.storeSettings(InfobaseAccessManager.java:385)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.InfobaseAccessManager.updateSettings(InfobaseAccessManager.java:319)
	at com._1c.g5.v8.dt.platform.services.core.infobases.IInfobaseAccessManager$pbryglu.updateSettings(Unknown Source)
	at com._1c.g5.v8.dt.internal.platform.services.ui.infobases.InfobaseAccessSettingsRequestor.requestAndUpdateAccessSettingsIfAppropriate(InfobaseAccessSettingsRequestor.java:94)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.ExtensionBasedInfobaseAccessSettingsRequestor.requestAndUpdateAccessSettingsIfAppropriate(ExtensionBasedInfobaseAccessSettingsRequestor.java:57)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.connect(DesignerSessionPool.java:522)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.createConnection(DesignerSessionPool.java:367)
	at com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionPool.acquire(DesignerSessionPool.java:247)
	at com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.openDesignerSession(DesignerSessionThickClientLauncher.java:207)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.DesignerSessionInfobaseConnection.openSession(DesignerSessionInfobaseConnection.java:179)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.DesignerSessionInfobaseConnection.connect(DesignerSessionInfobaseConnection.java:74)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ParticipantAwareInfobaseConnection.connect(ParticipantAwareInfobaseConnection.java:66)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.connections.ReconnectableInfobaseConnection.connect(ReconnectableInfobaseConnection.java:92)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronization.connectAndRestoreState(InfobaseSynchronization.java:196)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.connectAndRestoreState(InfobaseSynchronizationManager.java:1036)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.connectAndRestoreState(InfobaseSynchronizationManager.java:1011)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.connectIfAssociated(InfobaseSynchronizationManager.java:900)
	at com._1c.g5.v8.dt.internal.platform.services.core.infobases.sync.InfobaseSynchronizationManager.start(InfobaseSynchronizationManager.java:701)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:214)
	at com._1c.g5.v8.dt.internal.lifecycle.AnnotationRegistration$LifecyclePhaseParticipantMethodInvocation.accept(AnnotationRegistration.java:1)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.performPhase(ServicesOrchestrator.java:267)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startContext(ServicesOrchestrator.java:206)
	at com._1c.g5.v8.dt.internal.lifecycle.ServicesOrchestrator.startServices(ServicesOrchestrator.java:77)
	at com._1c.g5.v8.dt.lifecycle.IServicesOrchestrator$pbryglu.startServices(Unknown Source)
	at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startContext(WorkspaceOrchestrator.java:763)
	at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.startWorkspaceProjects(WorkspaceOrchestrator.java:371)
	at com._1c.g5.v8.dt.internal.core.lifecycle.DtProjectResourceLifecycleBootstrap$DefaultContextsStartJob.run(DtProjectResourceLifecycleBootstrap.java:696)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by Jimmi910** [comment]
[11.log.zip](https://github.com/1C-Company/1c-edt-issues/files/11176632/11.log.zip)

**Comment by nikolay-martynov** [comment]
@Jimmi910 Здравствуйте, Артём. Сделайте пожалуйста следующее:

- Зайдите в Окно / Параметры / Общие / Защита / Защищенное хранилище
- Сделайте снимок экрана для вкладки Пароль
- На вкладке Оглавление раскройте Default Secure Storage / com._1c.g5.v8.dt.platform.services.core / infobaseBinding
- Откроется список элементов, которые выглядят как a6bf7bbc-643f-11ee-8c99-0242ac120002
- Выберите один из них и сделайте снимок экрана
- Перейдите на вкладку Расширенные и сделайте снимок экрана

Пожалуйста приложите снимки к ответу.

**Comment by nikolay-martynov** [comment]
@Jimmo910 Не могли бы вы помочь с запрошенной информацией?

**Comment by Jimmo910** [comment]
@nikolay-martynov ОК сделаю на днях.

**Comment by nikolay-martynov** [comment]
@Jimmo910 Здравствуйте. Удалось ли вам проверить настройки защищенного хранилища? Или проблема более не воспроизводится?

**Comment by Zakharovzvv** [comment]
<img width="1725" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/1ec9dbc1-8689-4404-a35e-21ee3efc08f8">

**Comment by Zakharovzvv** [comment]
<img width="1724" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/68952793/a8ee05d5-1117-4fd7-9250-2a2b31831b5e">

**Comment by Viktor-Gostyaikin** [comment]
> <img alt="image" width="1725" src="https://private-user-images.githubusercontent.com/68952793/303266665-1ec9dbc1-8689-4404-a35e-21ee3efc08f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4OTE5MDUsIm5iZiI6MTcwODg5MTYwNSwicGF0aCI6Ii82ODk1Mjc5My8zMDMyNjY2NjUtMWVjOWRiYzEtODY4OS00NDA0LWEzNWUtMjFlZTNlZmMwOGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDIwMDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyODE5MTNlNzNjNjcxMDhmZGM3YTE2YzllMzNhMGRhZmFjYWM3OTM0MzhlMjk5MTA0ZjRkZDVmNGRhZDRmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1-qs8GSiGUm8kw1u6VkPsOylrof6hOfn0c0_xKf4kjI">

Мне помогло удаление этих значений и перезапуск EDT.

**Comment by nikolay-martynov** [comment]
Коллеги, подскажите пожалуйста, когда вы наблюдали "No password provided" вы работали с двумя экземплярами EDT? Или может быть помимо EDT использовали ещё какое-то приложение, основанное на Eclipse? Например, DBeaver или ADT и тому подобное?

**Comment by Jimmo910** [comment]
я точно использовал только EDT

**Comment by Jimmo910** [comment]
@nikolay-martynov а у вас не удается воспроизвести проблему? если надо я готов подключить вас к своему маку, на столько по времени на сколько это будет необходимо.

**Comment by nikolay-martynov** [comment]
@Jimmi910 Здравствуйте, Артём. Проблема в установлении причин и условий, которые ведут к появлению проблем c OS X Keychain. Вы запускаете несколько экземпляров EDT одновременно? Вы устанавливали какие-либо дополнительные плагины в EDT после первого соединения с какой-либо информационной базой?

**Comment by Jimmo910** [comment]
@nikolay-martynov нет не было запуска нескольких EDT одновременно, ЕДТ запускали по очереди. Нет не было каких то либо установок плагинов или чего то другова.

Проблема воспроизводилась согласно описанному примеру воспроизведения проблемы в шапке этого issues. Блок "Как воспроизвести"

**Comment by Jimmo910** [comment]
@nikolay-martynov я сейчас просто хотел заного воспроизвести проблему. скачал последнию тестовую версию ЕДТ. 
Создал Пустой проект. Создал пустую конфигурацию. Попытался создать приложение и от туда Базу файловую. Так мне тоже выдало ошибку с паролем....
<img width="1162" alt="image" src="https://github.com/1C-Company/1c-edt-issues/assets/122779512/85369385-e191-49f8-88a3-2ca375741eb9">
[metadata.zip](https://github.com/1C-Company/1c-edt-issues/files/15248335/metadata.zip)

**Comment by Roffild** [comment]
Работает с "мастер-паролем" для Подсказка.
![bug](https://github.com/1C-Company/1c-edt-issues/assets/38705255/81e8206a-222d-409e-991d-c171d22b7668)

**Comment by Oxotka** [comment]
На EDT 2024.1.2 и macOS 15.1 (24B83) тоже воспроизводится
